//! Exact canonical "gap region" derivation and candidate-containment testing
//! for a partial irregular layout.
//!
//! TS source ported here in full (238 lines):
//! `src/workers/algorithm/irregular/intrinsicGapRegions.ts`. Grounding
//! source: `docs/planning/rust-irregular-backend/characterization/
//! strict-decoder-gap-family.md` §2.2/§3.7/§4.3/§5 items 5-8/§6.5-6.6/§9
//! item 5/§12 hazard 1 (this file's own dedicated sections).
//!
//! Per that document's §1.3, the entire contents of `intrinsicGapRegions.ts`
//! are production-reachable (exclusively through `intrinsicStrictDecoder.ts`,
//! a sibling module's assignment) and must be ported in full, including both
//! exported functions and every private helper.
//!
//! # Reused (GREEN) modules — never duplicated here
//!
//! - `crate::canonical_grid::{canonical_grid_absolute_doubled_area,
//!   canonical_grid_clockwise, canonical_grid_convex_hull,
//!   canonical_grid_counter_clockwise, canonical_grid_point_on_segment,
//!   canonical_grid_signed_doubled_area, doubled_grid_area_to_mm2, to_grid_mm,
//!   CanonicalGridPath, CanonicalGridPoint}` — the TS counterpart's
//!   `canonicalGridMath.ts`/`clipper2OffsetPolicy.ts` imports
//!   (`intrinsicGapRegions.ts:14-24`).
//! - `crate::clipper::core::{ClipType, FillRule, Path64, Paths64, Point64}`
//!   and `crate::clipper::engine::{boolean_op_with_poly_tree,
//!   poly_tree_to_paths64, PolyTree64}` — the vendored Clipper2 port (ruling
//!   R10) this file's TS counterpart calls directly (`booleanOpWithPolyTree`,
//!   `ClipType`, `FillRule`, `Path64`, `PolyPath64`, `polyTreeToPaths64`,
//!   `PolyTree64`, `intrinsicGapRegions.ts:1-9`).
//! - `crate::checkpoints::canonical_json::locale_compare_keys` — the
//!   collator-equivalent ruling R8/the characterization doc's §12 hazard 1
//!   requires for this file's two genuine `.localeCompare()` call sites
//!   (the top-level region sort, `intrinsicGapRegions.ts:70`, and the
//!   per-region hole sort, `:148`).
//! - `crate::js_number::{cmp_js_code_units, js_math, number_to_js_string}` —
//!   this file's own local `canonicalRing` (`:229-238`) uses a **default**
//!   (no-comparator) `.toSorted()`, which per the characterization doc's §12
//!   hazard 4 is the *safe*, ordinal counterpart to hazard 1 — reproduced
//!   here via [`cmp_js_code_units`], not `locale_compare_keys`. `pathBounds`'s
//!   `Math.min`/`Math.max` (`:221-224`) route through [`js_math`]. Point
//!   coordinate stringification (`` `${x},${y}` ``, `:233`) routes through
//!   [`number_to_js_string`].
//! - `crate::domain::{IrregularPlacedPiece, IrregularPoint,
//!   TransformedCollisionGeometry}` — the TS counterpart's
//!   `@shared/irregular/domain.js` imports (`intrinsicGapRegions.ts:10-13`).
//!
//! # `booleanOpWithPolyTree`'s TS `try`/`catch` has no Rust equivalent
//!
//! Every `try { booleanOpWithPolyTree(...) } catch { return <sentinel> }`
//! and `try { child = parent.child(index) } catch { return <sentinel> }` in
//! the TS source (`:53-64,93-104,115-119,127-130,196-200`) is dropped here
//! with no `Result`/`catch_unwind` wrapper, for the same reason already
//! established by `crate::geometry::free_material` and
//! `crate::canonical_grid::layout` for the identical vendored-engine call
//! shape: `crate::clipper::engine`'s own module doc proves every exception
//! TS could throw from the reachable (closed-paths-only) subset is
//! unreachable dead code in this port, and `PolyTree64::child`'s own doc
//! proves its "index out of range" throw is unreachable given every caller
//! here (like every caller in the TS source) iterates `0..count`.
//!
//! # `CanonicalIntrinsicGapRegion.aabb` is grid units, not millimeters
//!
//! Per the characterization doc §3.7: `pathBounds` (`:213-227`) operates
//! directly on the already-grid-quantized `Path64`, with no `fromGrid`
//! conversion — this field's `min_x`/`min_y`/`max_x`/`max_y` are raw 0.001mm
//! grid integers, unlike `area_mm2`. This unit split is preserved verbatim
//! (do not "fix" it); nothing in this file reads `aabb` itself, but the
//! field is part of the public shape.
//!
//! This module's own differential vectors live in
//! `tests/vectors/gap-family.json` (generated by
//! `scripts/rust-parity/dump-gap-family.ts`), shared with
//! [`crate::search::strict_family`] per that module's own doc comment.

use std::cmp::Ordering;

use num_bigint::BigInt;

use crate::canonical_grid::{
    canonical_grid_absolute_doubled_area, canonical_grid_clockwise, canonical_grid_convex_hull,
    canonical_grid_counter_clockwise, canonical_grid_point_on_segment,
    canonical_grid_signed_doubled_area, doubled_grid_area_to_mm2, to_grid_mm, CanonicalGridPath,
    CanonicalGridPoint,
};
use crate::checkpoints::canonical_json::locale_compare_keys;
use crate::clipper::core::{ClipType, FillRule, Path64, Paths64, Point64};
use crate::clipper::engine::{boolean_op_with_poly_tree, poly_tree_to_paths64, PolyTree64};
use crate::domain::{IrregularPlacedPiece, IrregularPoint, TransformedCollisionGeometry};
use crate::js_number::{cmp_js_code_units, js_math, number_to_js_string};

// ===========================================================================
// Output types (TS: `intrinsicGapRegions.ts:26-39`).
// ===========================================================================

/// TS: `intrinsicGapRegions.ts:27` (`kind: 'enclosed-cavity' | 'hull-open-gap'`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CanonicalIntrinsicGapRegionKind {
    EnclosedCavity,
    HullOpenGap,
}

/// TS: `intrinsicGapRegions.ts:32-37` (`CanonicalIntrinsicGapRegion['aabb']`).
/// Grid units (0.001 mm integers), **not** millimeters — see this module's
/// doc comment.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct CanonicalIntrinsicGapRegionAabb {
    pub min_x: f64,
    pub min_y: f64,
    pub max_x: f64,
    pub max_y: f64,
}

/// TS: `intrinsicGapRegions.ts:26-39` (`CanonicalIntrinsicGapRegion`).
#[derive(Debug, Clone, PartialEq)]
pub struct CanonicalIntrinsicGapRegion {
    pub kind: CanonicalIntrinsicGapRegionKind,
    pub boundary: CanonicalGridPath,
    pub holes: Vec<CanonicalGridPath>,
    pub area_mm2: f64,
    /// `BigInt`-as-decimal-string, net of holes (TS: `doubledAreaGrid2`).
    pub doubled_area_grid2: String,
    pub aabb: CanonicalIntrinsicGapRegionAabb,
    pub canonical_key: String,
}

// ===========================================================================
// Clipper2 <-> canonical-grid point conversion (see this module's doc
// comment: each cluster file keeps its own copy of this trivial glue rather
// than sharing one, matching `crate::canonical_grid::layout`'s and
// `crate::geometry::free_material`'s established convention).
// ===========================================================================

fn to_clipper_path(path: &[CanonicalGridPoint]) -> Path64 {
    path.iter()
        .map(|point| Point64::new(point.x, point.y, 0.0))
        .collect()
}

fn to_canonical_grid_path(path: &[Point64]) -> CanonicalGridPath {
    path.iter()
        .map(|point| CanonicalGridPoint::new(point.x, point.y))
        .collect()
}

// ===========================================================================
// Public API
// ===========================================================================

/// Exact canonical convex-hull-minus-occupied-union regions.
///
/// TS: `intrinsicGapRegions.ts:42-72` (`deriveCanonicalIntrinsicGapRegions`).
pub fn derive_canonical_intrinsic_gap_regions(
    placed: &[IrregularPlacedPiece],
) -> Option<Vec<CanonicalIntrinsicGapRegion>> {
    let mut occupied: Vec<CanonicalGridPath> = Vec::with_capacity(placed.len());
    for piece in placed {
        occupied.push(placed_path(piece)?);
    }
    let flattened: Vec<CanonicalGridPoint> = occupied.iter().flatten().copied().collect();
    let hull = canonical_grid_convex_hull(&flattened)?;
    if hull.len() < 3 {
        return Some(Vec::new());
    }

    let subject_paths: Paths64 = occupied.iter().map(|path| to_clipper_path(path)).collect();
    let mut occupied_tree = PolyTree64::new();
    boolean_op_with_poly_tree(
        ClipType::Union,
        Some(&subject_paths),
        None,
        &mut occupied_tree,
        FillRule::EvenOdd,
    );

    let oriented_hull = canonical_grid_counter_clockwise(&hull).unwrap_or_else(|| hull.clone());
    let hull_subject: Paths64 = vec![to_clipper_path(&oriented_hull)];
    let occupied_union = poly_tree_to_paths64(&occupied_tree);
    let mut gap_tree = PolyTree64::new();
    boolean_op_with_poly_tree(
        ClipType::Difference,
        Some(&hull_subject),
        Some(&occupied_union),
        &mut gap_tree,
        FillRule::NonZero,
    );

    let mut regions: Vec<CanonicalIntrinsicGapRegion> = Vec::new();
    if !collect_regions(&gap_tree, PolyTree64::ROOT, &hull, &mut regions) {
        return None;
    }

    regions.sort_by(|first, second| {
        let first_area = first
            .doubled_area_grid2
            .parse::<BigInt>()
            .expect("doubled_area_grid2 is always a valid decimal BigInt string");
        let second_area = second
            .doubled_area_grid2
            .parse::<BigInt>()
            .expect("doubled_area_grid2 is always a valid decimal BigInt string");
        match first_area.cmp(&second_area) {
            Ordering::Equal => locale_compare_keys(&first.canonical_key, &second.canonical_key),
            other => other,
        }
    });
    Some(regions)
}

/// Exact zero-positive-area test for candidate minus one gap solid.
///
/// TS: `intrinsicGapRegions.ts:75-106` (`candidateContainedInIntrinsicGap`).
pub fn candidate_contained_in_intrinsic_gap(
    moving: &TransformedCollisionGeometry,
    point: IrregularPoint,
    region: &CanonicalIntrinsicGapRegion,
) -> bool {
    let mut candidate_path: CanonicalGridPath = Vec::with_capacity(moving.polygon.points.len());
    for source_point in &moving.polygon.points {
        let Some(x) = to_grid_mm(source_point.x + point.x) else {
            return false;
        };
        let Some(y) = to_grid_mm(source_point.y + point.y) else {
            return false;
        };
        candidate_path.push(CanonicalGridPoint::new(x, y));
    }

    let Some(boundary) = canonical_grid_counter_clockwise(&region.boundary) else {
        return false;
    };
    let mut holes: Vec<CanonicalGridPath> = Vec::with_capacity(region.holes.len());
    for hole in &region.holes {
        let Some(clockwise_hole) = canonical_grid_clockwise(hole) else {
            return false;
        };
        holes.push(clockwise_hole);
    }

    let mut solid: Paths64 = Vec::with_capacity(1 + holes.len());
    solid.push(to_clipper_path(&boundary));
    for hole in &holes {
        solid.push(to_clipper_path(hole));
    }

    let subject_path = canonical_grid_counter_clockwise(&candidate_path).unwrap_or(candidate_path);
    let subject: Paths64 = vec![to_clipper_path(&subject_path)];

    let mut difference = PolyTree64::new();
    boolean_op_with_poly_tree(
        ClipType::Difference,
        Some(&subject),
        Some(&solid),
        &mut difference,
        FillRule::NonZero,
    );

    total_positive_doubled_area(&difference, PolyTree64::ROOT) == Some(BigInt::from(0))
}

// ===========================================================================
// Private helpers (TS: `intrinsicGapRegions.ts:108-238`).
// ===========================================================================

/// TS: `intrinsicGapRegions.ts:108-163` (`collectRegions`).
fn collect_regions(
    tree: &PolyTree64,
    parent: usize,
    hull: &CanonicalGridPath,
    result: &mut Vec<CanonicalIntrinsicGapRegion>,
) -> bool {
    for index in 0..tree.count(parent) {
        let child = tree.child(parent, index);
        if !tree.is_hole(child) {
            if let Some(child_polygon) = tree.poly(child) {
                let child_path = to_canonical_grid_path(child_polygon);
                let Some(outer_doubled_area) = canonical_grid_absolute_doubled_area(&child_path)
                else {
                    return false;
                };
                let mut net_doubled_area = outer_doubled_area;
                let mut holes: Vec<CanonicalGridPath> = Vec::new();
                for hole_index in 0..tree.count(child) {
                    let hole = tree.child(child, hole_index);
                    if tree.is_hole(hole) {
                        if let Some(hole_polygon) = tree.poly(hole) {
                            let hole_path = to_canonical_grid_path(hole_polygon);
                            let Some(hole_doubled_area) =
                                canonical_grid_absolute_doubled_area(&hole_path)
                            else {
                                return false;
                            };
                            holes.push(hole_path);
                            net_doubled_area -= hole_doubled_area;
                        }
                    }
                }

                let aabb = path_bounds(&child_path);
                let area_mm2 = doubled_grid_area_to_mm2(&net_doubled_area);
                let boundary = canonical_grid_counter_clockwise(&child_path);
                if net_doubled_area <= BigInt::from(0)
                    || aabb.is_none()
                    || area_mm2.is_none()
                    || boundary.is_none()
                {
                    return false;
                }
                let aabb = aabb.expect("checked above");
                let area_mm2 = area_mm2.expect("checked above");
                let boundary = boundary.expect("checked above");

                let holes_len = holes.len();
                let mut ordered_holes: Vec<CanonicalGridPath> = holes
                    .into_iter()
                    .filter_map(|path| canonical_grid_clockwise(&path))
                    .collect();
                ordered_holes.sort_by(|first, second| {
                    locale_compare_keys(&canonical_ring(first), &canonical_ring(second))
                });
                if ordered_holes.len() != holes_len {
                    return false;
                }

                let kind = if path_touches_boundary(&boundary, hull) {
                    CanonicalIntrinsicGapRegionKind::HullOpenGap
                } else {
                    CanonicalIntrinsicGapRegionKind::EnclosedCavity
                };
                let canonical_key = format!(
                    "{}|{}",
                    canonical_ring(&boundary),
                    ordered_holes
                        .iter()
                        .map(|hole| canonical_ring(hole))
                        .collect::<Vec<_>>()
                        .join("|")
                );
                result.push(CanonicalIntrinsicGapRegion {
                    kind,
                    boundary,
                    holes: ordered_holes,
                    area_mm2,
                    doubled_area_grid2: net_doubled_area.to_string(),
                    aabb,
                    canonical_key,
                });
            }
        }
        if !collect_regions(tree, child, hull, result) {
            return false;
        }
    }
    true
}

/// TS: `intrinsicGapRegions.ts:165-175` (`pathTouchesBoundary`). Note the
/// caller's argument order: `path` is the candidate region's own boundary
/// ring, `boundary` is the enclosing hull.
fn path_touches_boundary(path: &[CanonicalGridPoint], boundary: &[CanonicalGridPoint]) -> bool {
    path.iter().any(|point| {
        boundary.iter().enumerate().any(|(index, start)| {
            let Some(end) = boundary.get((index + 1) % boundary.len()) else {
                return false;
            };
            canonical_grid_point_on_segment(*point, *start, *end)
        })
    })
}

/// TS: `intrinsicGapRegions.ts:177-189` (`placedPath`).
fn placed_path(placed: &IrregularPlacedPiece) -> Option<CanonicalGridPath> {
    let mut path: CanonicalGridPath =
        Vec::with_capacity(placed.collision_geometry.polygon.points.len());
    for point in &placed.collision_geometry.polygon.points {
        let x = to_grid_mm(point.x + placed.placement.transform.translate_x)?;
        let y = to_grid_mm(point.y + placed.placement.transform.translate_y)?;
        path.push(CanonicalGridPoint::new(x, y));
    }
    let signed_doubled_area = canonical_grid_signed_doubled_area(&path)?;
    if path.len() >= 3 && signed_doubled_area != BigInt::from(0) {
        canonical_grid_counter_clockwise(&path)
    } else {
        None
    }
}

/// TS: `intrinsicGapRegions.ts:191-211` (`totalPositiveDoubledArea`).
fn total_positive_doubled_area(tree: &PolyTree64, parent: usize) -> Option<BigInt> {
    let mut total = BigInt::from(0);
    if visit_total_positive_doubled_area(tree, parent, &mut total) {
        Some(total)
    } else {
        None
    }
}

fn visit_total_positive_doubled_area(tree: &PolyTree64, parent: usize, total: &mut BigInt) -> bool {
    for index in 0..tree.count(parent) {
        let child = tree.child(parent, index);
        if !tree.is_hole(child) {
            if let Some(child_polygon) = tree.poly(child) {
                let child_path = to_canonical_grid_path(child_polygon);
                let Some(doubled_area) = canonical_grid_absolute_doubled_area(&child_path) else {
                    return false;
                };
                *total += doubled_area;
            }
        }
        if !visit_total_positive_doubled_area(tree, child, total) {
            return false;
        }
    }
    true
}

/// TS: `intrinsicGapRegions.ts:213-227` (`pathBounds`).
fn path_bounds(path: &[CanonicalGridPoint]) -> Option<CanonicalIntrinsicGapRegionAabb> {
    let first = *path.first()?;
    let mut min_x = first.x;
    let mut min_y = first.y;
    let mut max_x = first.x;
    let mut max_y = first.y;
    for point in &path[1..] {
        min_x = js_math::min(min_x, point.x);
        min_y = js_math::min(min_y, point.y);
        max_x = js_math::max(max_x, point.x);
        max_y = js_math::max(max_y, point.y);
    }
    Some(CanonicalIntrinsicGapRegionAabb {
        min_x,
        min_y,
        max_x,
        max_y,
    })
}

/// TS: `intrinsicGapRegions.ts:229-238` (`canonicalRing`). Enumerates every
/// rotation x direction variant of the ring's point list and keeps the
/// **default**-sorted (ordinal, not locale-aware — characterization doc §12
/// hazard 4) smallest one; distinct from, and not to be confused with,
/// `crate::canonical_grid::layout`'s own (differently-implemented)
/// `canonical_ring` helper for a different TS source file.
fn canonical_ring(path: &[CanonicalGridPoint]) -> String {
    let reversed: CanonicalGridPath = path.iter().rev().copied().collect();
    let mut best: Option<String> = None;
    for sequence in [path, reversed.as_slice()] {
        for offset in 0..sequence.len() {
            let joined = sequence[offset..]
                .iter()
                .chain(sequence[..offset].iter())
                .map(|point| {
                    format!(
                        "{},{}",
                        number_to_js_string(point.x),
                        number_to_js_string(point.y)
                    )
                })
                .collect::<Vec<_>>()
                .join(";");
            best = Some(match best {
                None => joined,
                Some(current) => {
                    if cmp_js_code_units(&joined, &current) == Ordering::Less {
                        joined
                    } else {
                        current
                    }
                }
            });
        }
    }
    best.unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::{
        IrregularPlacement, IrregularPolygon, IrregularTransform, IrregularTransformCandidate,
        IrregularTransformReason, PieceId,
    };

    fn square_piece(id: &str, tx: f64, ty: f64, side_mm: f64) -> IrregularPlacedPiece {
        rect_piece(id, tx, ty, side_mm, side_mm)
    }

    fn rect_piece(
        id: &str,
        tx: f64,
        ty: f64,
        width_mm: f64,
        height_mm: f64,
    ) -> IrregularPlacedPiece {
        let polygon = IrregularPolygon::new(vec![
            IrregularPoint::new(0.0, 0.0),
            IrregularPoint::new(width_mm, 0.0),
            IrregularPoint::new(width_mm, height_mm),
            IrregularPoint::new(0.0, height_mm),
        ]);
        let bounds = crate::domain::IrregularBounds::new(0.0, 0.0, width_mm, height_mm);
        IrregularPlacedPiece {
            placement: IrregularPlacement {
                piece_id: None,
                source_piece_id: PieceId::new(id),
                placement_reference: None,
                transform: IrregularTransform {
                    translate_x: tx,
                    translate_y: ty,
                    rotation_deg: 0.0,
                    mirrored: false,
                },
            },
            collision_geometry: TransformedCollisionGeometry {
                source_piece_id: PieceId::new(id),
                transform: IrregularTransformCandidate {
                    index: 0.0,
                    rotation_deg: 0.0,
                    mirrored: false,
                    reason: IrregularTransformReason::Configured,
                },
                polygon,
                bounds,
            },
        }
    }

    #[test]
    fn empty_placed_list_yields_empty_region_list() {
        let regions = derive_canonical_intrinsic_gap_regions(&[]).expect("must succeed");
        assert!(regions.is_empty());
    }

    #[test]
    fn single_square_hull_degenerates_to_no_regions() {
        // A single square's convex hull equals its own occupied area exactly,
        // so the hull-minus-occupied difference is empty.
        let placed = vec![square_piece("a", 0.0, 0.0, 10.0)];
        let regions = derive_canonical_intrinsic_gap_regions(&placed).expect("must succeed");
        assert!(regions.is_empty());
    }

    #[test]
    fn two_diagonal_squares_produce_one_hull_open_gap() {
        // Two squares placed diagonally: their convex hull is a hexagon in
        // which both squares are corner-anchored (each touches two hull
        // edges), so the hull-minus-occupied difference is one single
        // connected band running between them (not two disjoint triangles),
        // and that band touches the hull boundary on both sides.
        let placed = vec![
            square_piece("a", 0.0, 0.0, 10.0),
            square_piece("b", 20.0, 20.0, 10.0),
        ];
        let regions = derive_canonical_intrinsic_gap_regions(&placed).expect("must succeed");
        assert_eq!(regions.len(), 1, "one connected open-gap band");
        assert_eq!(
            regions[0].kind,
            CanonicalIntrinsicGapRegionKind::HullOpenGap
        );
        assert!(regions[0].holes.is_empty());
        assert!(regions[0].area_mm2 > 0.0);
    }

    #[test]
    fn picture_frame_encloses_a_cavity() {
        // A closed rectangular frame (four rectangles fully surrounding a
        // 10x10 hole in the middle) has a hull equal to its own occupied
        // outer boundary, so the hole never touches the hull boundary: it
        // must be an enclosed cavity, not a hull-open gap.
        let placed = vec![
            rect_piece("top", 0.0, 20.0, 30.0, 10.0),
            rect_piece("bottom", 0.0, 0.0, 30.0, 10.0),
            rect_piece("left", 0.0, 10.0, 10.0, 10.0),
            rect_piece("right", 20.0, 10.0, 10.0, 10.0),
        ];
        let regions = derive_canonical_intrinsic_gap_regions(&placed).expect("must succeed");
        assert_eq!(
            regions.len(),
            1,
            "exactly one enclosed cavity in the middle"
        );
        assert_eq!(
            regions[0].kind,
            CanonicalIntrinsicGapRegionKind::EnclosedCavity
        );
        assert!(regions[0].holes.is_empty());
        // The cavity is exactly the 10x10 hole in grid units (0.001mm).
        assert_eq!(
            regions[0].doubled_area_grid2.parse::<BigInt>().unwrap(),
            BigInt::from(2) * BigInt::from(10_000) * BigInt::from(10_000)
        );
    }

    #[test]
    fn regions_are_sorted_ascending_by_doubled_area_then_canonical_key() {
        let placed = vec![
            square_piece("a", 0.0, 0.0, 10.0),
            square_piece("b", 30.0, 0.0, 10.0),
            square_piece("c", 0.0, 30.0, 20.0),
        ];
        let regions = derive_canonical_intrinsic_gap_regions(&placed).expect("must succeed");
        for window in regions.windows(2) {
            let first_area = window[0]
                .doubled_area_grid2
                .parse::<BigInt>()
                .expect("valid bigint");
            let second_area = window[1]
                .doubled_area_grid2
                .parse::<BigInt>()
                .expect("valid bigint");
            assert!(
                first_area < second_area
                    || (first_area == second_area
                        && locale_compare_keys(&window[0].canonical_key, &window[1].canonical_key)
                            != Ordering::Greater)
            );
        }
    }

    #[test]
    fn candidate_fully_inside_gap_region_is_contained() {
        let placed = vec![
            square_piece("a", 0.0, 0.0, 10.0),
            square_piece("b", 20.0, 0.0, 10.0),
        ];
        let regions = derive_canonical_intrinsic_gap_regions(&placed).expect("must succeed");
        assert_eq!(regions.len(), 1);
        let region = &regions[0];

        let moving = TransformedCollisionGeometry {
            source_piece_id: PieceId::new("c"),
            transform: IrregularTransformCandidate {
                index: 0.0,
                rotation_deg: 0.0,
                mirrored: false,
                reason: IrregularTransformReason::Configured,
            },
            polygon: IrregularPolygon::new(vec![
                IrregularPoint::new(0.0, 0.0),
                IrregularPoint::new(8.0, 0.0),
                IrregularPoint::new(8.0, 8.0),
                IrregularPoint::new(0.0, 8.0),
            ]),
            bounds: crate::domain::IrregularBounds::new(0.0, 0.0, 8.0, 8.0),
        };
        assert!(candidate_contained_in_intrinsic_gap(
            &moving,
            IrregularPoint::new(11.0, 0.5),
            region
        ));
    }

    #[test]
    fn candidate_overlapping_occupied_geometry_is_not_contained() {
        let placed = vec![
            square_piece("a", 0.0, 0.0, 10.0),
            square_piece("b", 20.0, 0.0, 10.0),
        ];
        let regions = derive_canonical_intrinsic_gap_regions(&placed).expect("must succeed");
        let region = &regions[0];

        let moving = TransformedCollisionGeometry {
            source_piece_id: PieceId::new("c"),
            transform: IrregularTransformCandidate {
                index: 0.0,
                rotation_deg: 0.0,
                mirrored: false,
                reason: IrregularTransformReason::Configured,
            },
            polygon: IrregularPolygon::new(vec![
                IrregularPoint::new(0.0, 0.0),
                IrregularPoint::new(20.0, 0.0),
                IrregularPoint::new(20.0, 8.0),
                IrregularPoint::new(0.0, 8.0),
            ]),
            bounds: crate::domain::IrregularBounds::new(0.0, 0.0, 20.0, 8.0),
        };
        // This 20x8 candidate spans past the occupied square at x=[0,10],
        // so it is not fully contained in the gap solid.
        assert!(!candidate_contained_in_intrinsic_gap(
            &moving,
            IrregularPoint::new(0.0, 1.0),
            region
        ));
    }

    #[test]
    fn canonical_ring_of_empty_path_is_empty_string() {
        assert_eq!(canonical_ring(&[]), "");
    }

    #[test]
    fn canonical_ring_is_invariant_to_rotation_and_direction() {
        let square = vec![
            CanonicalGridPoint::new(0.0, 0.0),
            CanonicalGridPoint::new(1.0, 0.0),
            CanonicalGridPoint::new(1.0, 1.0),
            CanonicalGridPoint::new(0.0, 1.0),
        ];
        let rotated: CanonicalGridPath = square[2..]
            .iter()
            .chain(square[..2].iter())
            .copied()
            .collect();
        let reversed: CanonicalGridPath = square.iter().rev().copied().collect();
        let key = canonical_ring(&square);
        assert_eq!(key, canonical_ring(&rotated));
        assert_eq!(key, canonical_ring(&reversed));
    }
}
