//! Repeated-collision-family grouping for the strict (E1) decoder cluster.
//!
//! TS source: `src/workers/algorithm/irregular/intrinsicStrictFamilyPortfolio.ts`
//! (536 lines). Grounding source: `docs/planning/rust-irregular-backend/
//! characterization/strict-decoder-gap-family.md` §1.2/§1.3/§2.3/§6.9/§15
//! item 1 (this file's own dedicated sections).
//!
//! # Scope: production-live subset only, per the characterization doc
//!
//! Per §1.2/§2.3 of that document (traced by grepping every `src/`/`scripts/`
//! caller, not assumed): **only** `groupIntrinsicCollisionFamilies`
//! (`:95-121`), `intrinsicCollisionFamilyKey` (`:124-130`), the
//! `IntrinsicCollisionFamily` type (`:41-48`), and their two private
//! dependencies `measureCollisionPolygon` (`:469-512`) and
//! `canonicalCyclicPolygonKey`/`cyclicKeys` (`:514-536`) are reachable from
//! `computeIrregularNesting.ts` (via `intrinsicPeriodicCells.ts:288-296` and
//! `intrinsicPeriodicFamilyPortfolio.ts:643-644,1079-1081`). Every other
//! export of that file — `buildIntrinsicFamilyPortfolioChromosomes`,
//! `runIntrinsicStrictFamilyPortfolio`, `selectIntrinsicFamilyPortfolioWinner`,
//! `orderIntrinsicFamilyPortfolioPieces`, `selectRepeatedElongatedFamilies`,
//! `sizeBands`, `familyRoundRobin`, `restrictOrientationTemplate`, and the
//! four-order x two-template chromosome-portfolio machinery built on top of
//! them — has zero production callers (only `tests/unit/
//! intrinsicStrictFamilyPortfolio.test.ts` and developer probe scripts under
//! `scripts/`, confirmed by the characterization doc's grep). Per that
//! document's §15 item 1 recommendation, this dead chromosome-portfolio
//! machinery is **intentionally not ported** here: it stays TypeScript-only
//! (migration prompt §4.1's "maintained reference backend" still covers it),
//! and this module's scope is limited to the four production-reachable
//! items above.
//!
//! # Reused (GREEN) modules — never duplicated here
//!
//! - `crate::canonical_grid::to_grid_mm` — the TS counterpart's
//!   `clipper2OffsetPolicy.ts` import (`intrinsicStrictFamilyPortfolio.ts:11`).
//! - `crate::js_number::{cmp_js_code_units, js_math, number_to_js_string}` —
//!   `canonicalCyclicPolygonKey`'s **default** (no-comparator) `.toSorted()`
//!   (`:527`) is the *safe*, ordinal counterpart to the cluster's
//!   `.localeCompare()` hazard (characterization doc §12 hazard 4),
//!   reproduced here via [`cmp_js_code_units`] — this file has **no**
//!   `.localeCompare()` call site of its own within the production-live
//!   subset (the two `.localeCompare()` uses in this TS file,
//!   `intrinsicStrictFamilyPortfolio.ts:188,442-443`, both live inside the
//!   out-of-scope dead-code paths `selectRepeatedElongatedFamilies` and
//!   `chromosomeIdentity`). `measureCollisionPolygon`'s `Math.min`/`Math.max`
//!   (`:497-500,504-505`) route through [`js_math`]; point-coordinate
//!   stringification (`` `${x},${y}` ``, `:520`) routes through
//!   [`number_to_js_string`].
//! - `crate::domain::{IrregularPoint, IrregularPreparedPiece}` — the TS
//!   counterpart's `@shared/irregular/domain.js` import
//!   (`intrinsicStrictFamilyPortfolio.ts:7-10`).
//!
//! # `JSON.stringify` on a two-string array — a narrow, independently-copied helper
//!
//! `intrinsicCollisionFamilyKey` (`:124-130`) calls plain
//! `JSON.stringify([interchangeabilityKey, canonicalCyclicPolygonKey(...)])`
//! (**not** `crate::checkpoints::canonical_json`'s encoders, which are a
//! different, JS-`Map`/`BigInt`-aware canonical-hash-preimage family used
//! only by the strict decoder's own checkpoint hashing — see that module's
//! §8.1 for why the two must not be conflated). [`json_stringify_string_pair`]
//! below reproduces the ECMA-262 `QuoteJSONString` algorithm for exactly this
//! two-string-array shape; it is a small, independent copy of the same
//! escaping algorithm `checkpoints::canonical_json`'s private
//! `json_string_literal` implements, kept local per this crate's established
//! convention of small trivial glue staying in each file rather than
//! depending on another module's private helper.
//!
//! This module's own differential vectors live in
//! `tests/vectors/gap-family.json` (generated by
//! `scripts/rust-parity/dump-gap-family.ts`), shared with
//! [`crate::search::gap_regions`] per that module's own doc comment.

use std::cmp::Ordering;
use std::collections::HashMap;

use crate::canonical_grid::to_grid_mm;
use crate::domain::{IrregularPoint, IrregularPreparedPiece};
use crate::js_number::{cmp_js_code_units, js_math, number_to_js_string};

// ===========================================================================
// Output type (TS: `intrinsicStrictFamilyPortfolio.ts:41-48`).
// ===========================================================================

/// TS: `intrinsicStrictFamilyPortfolio.ts:41-48` (`IntrinsicCollisionFamily`).
///
/// `collision_area_mm2`/`maximum_side_mm`/`aspect_ratio` are derived once
/// from `members[0]` only (`:109-119`), never averaged or re-validated
/// against other members — other members are *assumed*, not verified, to be
/// geometrically identical because [`intrinsic_collision_family_key`]
/// already encodes the canonical polygon shape. Do not "improve" this by
/// computing per-member statistics.
#[derive(Debug, Clone, PartialEq)]
pub struct IntrinsicCollisionFamily {
    pub key: String,
    pub members: Vec<IrregularPreparedPiece>,
    /// TS `number` (`firstBaselineIndex`); mirrored as `f64` per this
    /// crate's number-fidelity convention (`domain` module doc), not a
    /// narrower Rust integer type, even though every real value is a
    /// non-negative array index.
    pub first_baseline_index: f64,
    pub collision_area_mm2: f64,
    pub maximum_side_mm: f64,
    pub aspect_ratio: f64,
}

// ===========================================================================
// Public API
// ===========================================================================

/// Groups prepared copies by both declared interchangeability and exact
/// collision shape.
///
/// TS: `intrinsicStrictFamilyPortfolio.ts:95-121`
/// (`groupIntrinsicCollisionFamilies`). Output order is **first-occurrence
/// order** while scanning `pieces` left to right — a JS `Map`'s key
/// insertion order, which `.set()` on an existing key never disturbs
/// (characterization doc §5 item 9, §12 hazard 5). Reproduced here with an
/// explicit `Vec` (insertion order) alongside a `HashMap<String, usize>`
/// lookup index, never a bare hash map relied on for iteration order.
pub fn group_intrinsic_collision_families(
    pieces: &[IrregularPreparedPiece],
) -> Vec<IntrinsicCollisionFamily> {
    struct GroupBuilder {
        key: String,
        members: Vec<IrregularPreparedPiece>,
        first_baseline_index: f64,
    }

    let mut groups: Vec<GroupBuilder> = Vec::new();
    let mut index_by_key: HashMap<String, usize> = HashMap::new();

    for (index, piece) in pieces.iter().enumerate() {
        let key = intrinsic_collision_family_key(piece);
        match index_by_key.get(&key) {
            Some(&group_index) => {
                groups[group_index].members.push(piece.clone());
            }
            None => {
                index_by_key.insert(key.clone(), groups.len());
                groups.push(GroupBuilder {
                    key,
                    members: vec![piece.clone()],
                    first_baseline_index: index as f64,
                });
            }
        }
    }

    groups
        .into_iter()
        .map(|group| {
            let measurements = group.members.first().and_then(|first| {
                measure_collision_polygon(&first.collision_geometry.collision_polygon.points)
            });
            IntrinsicCollisionFamily {
                key: group.key,
                members: group.members,
                first_baseline_index: group.first_baseline_index,
                collision_area_mm2: measurements.as_ref().map_or(0.0, |m| m.area_mm2),
                maximum_side_mm: measurements.as_ref().map_or(0.0, |m| m.maximum_side_mm),
                aspect_ratio: measurements.as_ref().map_or(1.0, |m| m.aspect_ratio),
            }
        })
        .collect()
}

/// Stable collision-family key with source-copy identity intentionally
/// excluded.
///
/// TS: `intrinsicStrictFamilyPortfolio.ts:124-130` (`intrinsicCollisionFamilyKey`).
pub fn intrinsic_collision_family_key(piece: &IrregularPreparedPiece) -> String {
    let interchangeability_key = piece
        .interchangeability_key
        .as_deref()
        .unwrap_or_else(|| piece.source.id.as_str());
    let cyclic_key =
        canonical_cyclic_polygon_key(&piece.collision_geometry.collision_polygon.points);
    json_stringify_string_pair(interchangeability_key, &cyclic_key)
}

// ===========================================================================
// Private helpers (TS: `intrinsicStrictFamilyPortfolio.ts:469-536`).
// ===========================================================================

struct CollisionPolygonMeasurements {
    area_mm2: f64,
    maximum_side_mm: f64,
    aspect_ratio: f64,
}

/// TS: `intrinsicStrictFamilyPortfolio.ts:469-512` (`measureCollisionPolygon`).
///
/// `doubled_area_grid2` is accumulated as a **plain `f64`** (JS `number`),
/// not `BigInt` — unlike this cluster's exact shoelace-area primitives
/// elsewhere (`canonicalCollisionArea` in the strict decoder,
/// `canonical_grid_absolute_doubled_area` here), this is a plain
/// floating-point diagnostic measurement and must keep exactly that
/// precision behavior, not be "upgraded" to exact arithmetic.
fn measure_collision_polygon(points: &[IrregularPoint]) -> Option<CollisionPolygonMeasurements> {
    if points.len() < 3 {
        return None;
    }
    let mut doubled_area_grid2 = 0.0_f64;
    let mut min_x = f64::INFINITY;
    let mut min_y = f64::INFINITY;
    let mut max_x = f64::NEG_INFINITY;
    let mut max_y = f64::NEG_INFINITY;
    // TS's `points[index]`/`points[(index + 1) % points.length]` each carry
    // a defensive `=== undefined` guard that can never trigger for a
    // contiguous 0-based array indexed exactly this way (a proven-
    // unreachable branch omitted per the migration prompt's standard for
    // omitting proven-unreachable code, not silently dropped without
    // justification).
    for index in 0..points.len() {
        let first = points[index];
        let second = points[(index + 1) % points.len()];
        let first_x = to_grid_mm(first.x)?;
        let first_y = to_grid_mm(first.y)?;
        let second_x = to_grid_mm(second.x)?;
        let second_y = to_grid_mm(second.y)?;
        doubled_area_grid2 += first_x * second_y - second_x * first_y;
        min_x = js_math::min(min_x, first.x);
        min_y = js_math::min(min_y, first.y);
        max_x = js_math::max(max_x, first.x);
        max_y = js_math::max(max_y, first.y);
    }
    let width = max_x - min_x;
    let height = max_y - min_y;
    let shorter = js_math::min(width, height);
    let longer = js_math::max(width, height);
    if shorter <= 0.0
        || !width.is_finite()
        || !height.is_finite()
        || !doubled_area_grid2.is_finite()
    {
        return None;
    }
    Some(CollisionPolygonMeasurements {
        area_mm2: doubled_area_grid2.abs() / 2_000_000.0,
        maximum_side_mm: longer,
        aspect_ratio: longer / shorter,
    })
}

/// TS: `intrinsicStrictFamilyPortfolio.ts:514-528` (`canonicalCyclicPolygonKey`).
/// Structurally identical to `crate::search::gap_regions`'s own local
/// `canonicalRing` (both TS source functions enumerate every rotation x
/// direction variant and take the **default**-sorted smallest one), but an
/// independent copy: the two TS source functions are themselves independent
/// (different files, different callers), and this file's own module doc
/// cites the established convention of not sharing this kind of small glue
/// across cluster files.
fn canonical_cyclic_polygon_key(points: &[IrregularPoint]) -> String {
    let keys: Vec<String> = points
        .iter()
        .map(|point| match (to_grid_mm(point.x), to_grid_mm(point.y)) {
            (Some(x), Some(y)) => format!("{},{}", number_to_js_string(x), number_to_js_string(y)),
            _ => "invalid".to_string(),
        })
        .collect();
    if keys.is_empty() {
        return String::new();
    }
    let mut best: Option<String> = None;
    for start in 0..keys.len() {
        for variant in [cyclic_keys(&keys, start, 1), cyclic_keys(&keys, start, -1)] {
            best = Some(match best {
                None => variant,
                Some(current) => {
                    if cmp_js_code_units(&variant, &current) == Ordering::Less {
                        variant
                    } else {
                        current
                    }
                }
            });
        }
    }
    best.unwrap_or_default()
}

/// TS: `intrinsicStrictFamilyPortfolio.ts:530-536` (`cyclicKeys`). `direction`
/// is `1 | -1` in TS; mirrored as `i64` here purely for the signed modular
/// arithmetic, never any other value.
fn cyclic_keys(keys: &[String], start: usize, direction: i64) -> String {
    let len = keys.len() as i64;
    let mut result: Vec<&str> = Vec::with_capacity(keys.len());
    for offset in 0..keys.len() {
        // TS adds `keys.length * 2` before the modulo specifically to keep
        // the intermediate value non-negative for `direction === -1`
        // (JS `%` is a remainder operator, not Euclidean modulo, so a
        // negative dividend yields a negative result); `rem_euclid`
        // reproduces the same always-non-negative result directly.
        let index = (start as i64 + direction * offset as i64 + len * 2).rem_euclid(len);
        result.push(keys.get(index as usize).map(String::as_str).unwrap_or(""));
    }
    result.join(";")
}

/// `JSON.stringify([a, b])` for exactly two plain strings — see this
/// module's doc comment for why this is an independent copy of
/// `crate::checkpoints::canonical_json`'s private `json_string_literal`
/// escaping algorithm rather than a shared export.
fn json_stringify_string_pair(first: &str, second: &str) -> String {
    format!(
        "[{},{}]",
        json_string_literal(first),
        json_string_literal(second)
    )
}

/// `JSON.stringify(value)` for a `string` — the ECMA-262 `QuoteJSONString`
/// algorithm (escapes `"`, `\`, and every control character
/// `U+0000..=U+001F` using the six named short escapes plus lowercase-hex
/// `\u00xx` for the rest; every other code point passes through unescaped).
fn json_string_literal(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for ch in value.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\u{8}' => out.push_str("\\b"),
            '\u{c}' => out.push_str("\\f"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::{CollisionGeometry, ImportedPiece, IrregularBounds, IrregularPolygon};
    use crate::domain::{DxfGeometryEntityType, DxfGeometrySummary, PieceId, Rect, SourceFileId};

    fn square(side_mm: f64) -> IrregularPolygon {
        IrregularPolygon::new(vec![
            IrregularPoint::new(0.0, 0.0),
            IrregularPoint::new(side_mm, 0.0),
            IrregularPoint::new(side_mm, side_mm * 2.0),
            IrregularPoint::new(0.0, side_mm * 2.0),
        ])
    }

    fn prepared_piece(
        id: &str,
        interchangeability_key: Option<&str>,
        side_mm: f64,
    ) -> IrregularPreparedPiece {
        let polygon = square(side_mm);
        IrregularPreparedPiece {
            piece_id: Some(PieceId::new(id)),
            interchangeability_key: interchangeability_key.map(|s| s.to_string()),
            source: ImportedPiece {
                id: PieceId::new(id),
                source_file_id: SourceFileId::new("file-1"),
                source_layer: None,
                label: "piece".to_string(),
                real_bounds: Rect {
                    x: 0.0,
                    y: 0.0,
                    width: side_mm,
                    height: side_mm * 2.0,
                },
                geometry: DxfGeometrySummary {
                    entity_type: DxfGeometryEntityType::PresetShape,
                    closed: true,
                    segments: vec![],
                },
                warnings: vec![],
            },
            allow_mirror: true,
            collision_geometry: CollisionGeometry {
                source_piece_id: PieceId::new(id),
                source_bounds: IrregularBounds::new(0.0, 0.0, side_mm, side_mm * 2.0),
                sampled_points: vec![],
                convex_hull: polygon.clone(),
                collision_polygon: polygon,
                placement_reference: IrregularPoint::new(0.0, 0.0),
                diagnostics: vec![],
            },
            transforms: vec![],
            priority_order_key: None,
        }
    }

    #[test]
    fn measure_collision_polygon_measures_rectangle() {
        let polygon = square(10.0);
        let measurements =
            measure_collision_polygon(&polygon.points).expect("valid rectangle measures");
        assert_eq!(measurements.area_mm2, 200.0);
        assert_eq!(measurements.maximum_side_mm, 20.0);
        assert_eq!(measurements.aspect_ratio, 2.0);
    }

    #[test]
    fn measure_collision_polygon_rejects_degenerate_input() {
        assert!(measure_collision_polygon(&[]).is_none());
        assert!(measure_collision_polygon(&[
            IrregularPoint::new(0.0, 0.0),
            IrregularPoint::new(1.0, 0.0)
        ])
        .is_none());
        // Zero-height degenerate rectangle: `shorter <= 0`.
        assert!(measure_collision_polygon(&[
            IrregularPoint::new(0.0, 0.0),
            IrregularPoint::new(1.0, 0.0),
            IrregularPoint::new(1.0, 0.0),
            IrregularPoint::new(0.0, 0.0),
        ])
        .is_none());
    }

    #[test]
    fn canonical_cyclic_polygon_key_is_rotation_and_direction_invariant() {
        let square = square(10.0);
        let rotated = IrregularPolygon::new(
            square.points[1..]
                .iter()
                .chain(square.points[..1].iter())
                .copied()
                .collect(),
        );
        let reversed = IrregularPolygon::new(square.points.iter().rev().copied().collect());
        let key = canonical_cyclic_polygon_key(&square.points);
        assert_eq!(key, canonical_cyclic_polygon_key(&rotated.points));
        assert_eq!(key, canonical_cyclic_polygon_key(&reversed.points));
    }

    #[test]
    fn canonical_cyclic_polygon_key_of_empty_points_is_empty_string() {
        assert_eq!(canonical_cyclic_polygon_key(&[]), "");
    }

    #[test]
    fn intrinsic_collision_family_key_falls_back_to_source_id() {
        let piece = prepared_piece("piece-1", None, 10.0);
        let key = intrinsic_collision_family_key(&piece);
        assert!(key.starts_with("[\"piece-1\","));
    }

    #[test]
    fn intrinsic_collision_family_key_prefers_interchangeability_key() {
        let piece = prepared_piece("piece-1", Some("family-a"), 10.0);
        let key = intrinsic_collision_family_key(&piece);
        assert!(key.starts_with("[\"family-a\","));
    }

    #[test]
    fn group_preserves_first_occurrence_insertion_order_and_pushes_into_existing_group() {
        let pieces = vec![
            prepared_piece("a", Some("family-a"), 10.0),
            prepared_piece("b", Some("family-b"), 20.0),
            prepared_piece("c", Some("family-a"), 10.0),
        ];
        let families = group_intrinsic_collision_families(&pieces);
        assert_eq!(families.len(), 2, "two distinct families");
        assert_eq!(families[0].key, intrinsic_collision_family_key(&pieces[0]));
        assert_eq!(families[0].members.len(), 2, "a and c share family-a");
        assert_eq!(families[0].first_baseline_index, 0.0);
        assert_eq!(families[1].key, intrinsic_collision_family_key(&pieces[1]));
        assert_eq!(families[1].members.len(), 1);
        assert_eq!(families[1].first_baseline_index, 1.0);
    }

    #[test]
    fn group_measurements_come_from_first_member_only() {
        // Two members nominally in the same (interchangeability-key-based)
        // family but with intentionally different geometry: the returned
        // measurements must come from the first member alone.
        let mut pieces = vec![prepared_piece("a", Some("family-a"), 10.0)];
        let mut second = prepared_piece("b", Some("family-a"), 999.0);
        // Force an identical family key despite different geometry by
        // overwriting the second piece's collision polygon with the first's
        // shape post-construction (keeping `interchangeabilityKey` shared is
        // what the real key groups on; this directly tests the "first
        // member wins" rule without relying on key collision nuances).
        second.collision_geometry.collision_polygon =
            pieces[0].collision_geometry.collision_polygon.clone();
        pieces.push(second);
        let families = group_intrinsic_collision_families(&pieces);
        assert_eq!(families.len(), 1);
        assert_eq!(families[0].collision_area_mm2, 200.0);
    }

    #[test]
    fn empty_pieces_yields_no_families() {
        assert!(group_intrinsic_collision_families(&[]).is_empty());
    }
}
