//! Nominal string-identity newtypes.
//!
//! TS source: `src/shared/domain/ids.ts`. `PieceId`/`SourceFileId`/`JobId`
//! are Effect `Schema.brand` wrappers over `Schema.String` (`ids.ts:11-13`
//! declares the brand *symbols*; `ids.ts:49-51` declares the three schema
//! values this crate needs). Per
//! `docs/planning/rust-irregular-backend/semantic-mapping.md`'s `core::domain`
//! newtypes row: "no runtime representation beyond `string`; Rust newtype
//! wrapping a `String` is sufficient." `FreeRectId` (`ids.ts:14,52`) belongs
//! only to the excluded rectangular algorithm and is intentionally not
//! ported here.
//!
//! The `Math.random()`-based zero-argument UUID fallback (`ids.ts:26-32`,
//! reached only when `globalThis.crypto.randomUUID` is unavailable) is
//! confirmed not reachable from the nesting hot path (`semantic-mapping.md`'s
//! `ids.ts` row) and is not ported: every id this crate ever sees crosses the
//! N-API boundary already generated by TypeScript.
//!
//! Every id type additionally derives `Eq`/`Hash`/`Ord` beyond this module's
//! baseline `Clone`/`Debug`/`PartialEq` requirement: ids are plain immutable
//! strings (no `f64` fields to make those derives unsound), and later stages
//! of this port need them as `HashMap`/`BTreeMap` keys and sort keys (e.g.
//! placed-piece indices, cache stores) exactly as the TS `string` brand they
//! mirror already supports via `===`/`Map`/`.sort()`.

use serde::{Deserialize, Serialize};
use std::fmt;

/// TS: `ids.ts:49` `export const PieceId = withGeneratedId(PieceBrand(Schema.String))`.
/// Identifies one imported/prepared/placed piece.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct PieceId(pub String);

/// TS: `ids.ts:50` `export const SourceFileId = withGeneratedId(SourceFileBrand(Schema.String))`.
/// Identifies one imported DXF source document.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct SourceFileId(pub String);

/// TS: `ids.ts:51` `export const JobId = withGeneratedId(JobBrand(Schema.String))`.
/// Identifies one nesting job.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct JobId(pub String);

macro_rules! impl_id_conversions {
    ($name:ident) => {
        impl $name {
            /// Wraps an already-generated id string. Mirrors the TS
            /// `PieceId.make(input)` decode path (`ids.ts:38-40`); this crate
            /// never re-validates the string (validation stays TS-side, see
            /// the module doc), it only carries an already-trusted value.
            pub fn new(value: impl Into<String>) -> Self {
                Self(value.into())
            }

            pub fn as_str(&self) -> &str {
                &self.0
            }
        }

        impl fmt::Display for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                fmt::Display::fmt(&self.0, f)
            }
        }

        impl From<String> for $name {
            fn from(value: String) -> Self {
                Self(value)
            }
        }

        impl From<&str> for $name {
            fn from(value: &str) -> Self {
                Self(value.to_string())
            }
        }
    };
}

impl_id_conversions!(PieceId);
impl_id_conversions!(SourceFileId);
impl_id_conversions!(JobId);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ids_construct_display_and_compare_as_plain_strings() {
        let a = PieceId::new("piece-1");
        let b: PieceId = "piece-1".into();
        let c: PieceId = String::from("piece-2").into();
        assert_eq!(a, b);
        assert_ne!(a, c);
        assert_eq!(a.as_str(), "piece-1");
        assert_eq!(format!("{a}"), "piece-1");
    }

    #[test]
    fn ids_serde_round_trip_as_a_bare_json_string() {
        let id = JobId::new("job-42");
        let json = serde_json::to_string(&id).expect("JobId serializes");
        assert_eq!(json, "\"job-42\"");
        let decoded: JobId = serde_json::from_str(&json).expect("JobId deserializes");
        assert_eq!(decoded, id);
    }
}
