//! Differential-vector test for `crates/irregular-nesting-native/src/search/beam_state.rs`.
//!
//! Loads `tests/vectors/beam-state.json`, generated by
//! `scripts/rust-parity/dump-beam-state.ts` from the REAL production TS
//! `IrregularBeamState` class (`src/workers/algorithm/irregular/irregularBeamState.ts`),
//! and asserts this crate's port reproduces every recorded canonical key,
//! ring-key invariance sweep, incremental-state-chain snapshot, `-0`
//! coordinate case, and insertion-order dedup-identity proof.
//!
//! # `localeCompare`-dependent fields: content-equivalence, not byte-equality
//!
//! Two fields in the recorded snapshots
//! (`contactSignatureContinuationIdentity`, and the
//! `nearCompleteStructuralContactSignatureCounts` sub-string embedded inside
//! `continuationMetadataIdentity`) are sorted by TS's locale-sensitive
//! `String.prototype.localeCompare` before serialization. Per
//! `search::beam_state::IrregularBeamState::contact_signature_continuation_identity`'s
//! own doc comment (which documents an empirically-verified, genuine
//! divergence from plain UTF-16 code-unit order for this content class, and
//! this crate's inability to add an ICU-backed dependency), this Rust port
//! deliberately uses a different-but-equally-deterministic order. This test
//! therefore verifies **content equivalence** (decode both sides' JSON
//! payload, sort by a shared Rust-only order, compare) for those two
//! sub-fields rather than raw string equality -- exactly the same principle
//! `validation::spatial_index::PlacedCollisionSpatialIndex::continuation_identity`
//! already established for its own `localeCompare` field. Every other
//! recorded field (every canonical key, every bound, every contact metric,
//! `canonicalEntryContinuationIdentity`, and the `canonicalEntryKeys`
//! sub-string embedded inside `continuationMetadataIdentity`) is asserted
//! byte-exact.

use std::fs;
use std::sync::Arc;

use serde_json::Value;

use irregular_nesting_native::domain::{
    IrregularPlacedPiece, IrregularPlacement, IrregularPoint, IrregularPolygon, IrregularTransform,
    IrregularTransformCandidate, IrregularTransformReason, PieceId, TransformedCollisionGeometry,
};
use irregular_nesting_native::search::beam_state::{
    canonical_collision_polygon_key, IrregularBeamState, IrregularBeamStateInput,
    IrregularCollisionBounds, IrregularQuarterTurnDegrees, WithPlacementInput,
    WithUnplacedPieceInput,
};

fn load_vectors() -> Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/vectors/beam-state.json");
    let raw = fs::read_to_string(path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&raw).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

// ---------------------------------------------------------------------------
// f64 bit-pattern decode (matches every other `*_vectors.rs`'s convention).
// ---------------------------------------------------------------------------
fn parse_f64_bits(hex: &str) -> f64 {
    let stripped = hex
        .strip_prefix("0x")
        .unwrap_or_else(|| panic!("bit-pattern hex must start with 0x, got {hex}"));
    let bits = u64::from_str_radix(stripped, 16)
        .unwrap_or_else(|err| panic!("invalid bit-pattern hex {hex}: {err}"));
    f64::from_bits(bits)
}

fn bits_field(value: &Value, field: &str) -> f64 {
    parse_f64_bits(
        value[field]
            .as_str()
            .unwrap_or_else(|| panic!("{field} present as a bit-pattern hex string")),
    )
}

fn assert_bits_eq(actual: f64, value: &Value, field: &str, label: &str) {
    let expected = bits_field(value, field);
    assert_eq!(
        actual.to_bits(),
        expected.to_bits(),
        "{label}: {field} mismatch (actual={actual:?}, expected={expected:?})"
    );
}

fn assert_optional_bits_eq(actual: Option<f64>, value: &Value, field: &str, label: &str) {
    let raw = &value[field];
    if raw.is_null() {
        assert_eq!(
            actual, None,
            "{label}: {field} expected None, got {actual:?}"
        );
        return;
    }
    let expected = parse_f64_bits(
        raw.as_str()
            .unwrap_or_else(|| panic!("{label}: {field} present as a bit-pattern hex string")),
    );
    match actual {
        None => panic!("{label}: {field} expected Some({expected:?}), got None"),
        Some(actual) => assert_eq!(
            actual.to_bits(),
            expected.to_bits(),
            "{label}: {field} mismatch (actual={actual:?}, expected={expected:?})"
        ),
    }
}

fn decode_point(value: &Value) -> IrregularPoint {
    IrregularPoint::new(bits_field(value, "x"), bits_field(value, "y"))
}

fn decode_points(value: &Value) -> Vec<IrregularPoint> {
    value
        .as_array()
        .expect("points array present")
        .iter()
        .map(decode_point)
        .collect()
}

fn decode_transform_reason(raw: &str) -> IrregularTransformReason {
    match raw {
        "orthogonal" => IrregularTransformReason::Orthogonal,
        "edge_alignment" => IrregularTransformReason::EdgeAlignment,
        "configured" => IrregularTransformReason::Configured,
        other => panic!("unrecognized IrregularTransformReason: {other}"),
    }
}

fn decode_collision_bounds(value: &Value) -> Option<IrregularCollisionBounds> {
    if value.is_null() {
        return None;
    }
    Some(IrregularCollisionBounds {
        min_x: bits_field(value, "minX"),
        min_y: bits_field(value, "minY"),
        max_x: bits_field(value, "maxX"),
        max_y: bits_field(value, "maxY"),
        width: bits_field(value, "width"),
        height: bits_field(value, "height"),
    })
}

fn assert_optional_bounds_eq(actual: Option<IrregularCollisionBounds>, value: &Value, label: &str) {
    let expected = decode_collision_bounds(value);
    match (actual, expected) {
        (None, None) => {}
        (Some(actual), Some(expected)) => {
            assert_eq!(
                actual.min_x.to_bits(),
                expected.min_x.to_bits(),
                "{label}: bounds.minX mismatch"
            );
            assert_eq!(
                actual.min_y.to_bits(),
                expected.min_y.to_bits(),
                "{label}: bounds.minY mismatch"
            );
            assert_eq!(
                actual.max_x.to_bits(),
                expected.max_x.to_bits(),
                "{label}: bounds.maxX mismatch"
            );
            assert_eq!(
                actual.max_y.to_bits(),
                expected.max_y.to_bits(),
                "{label}: bounds.maxY mismatch"
            );
            assert_eq!(
                actual.width.to_bits(),
                expected.width.to_bits(),
                "{label}: bounds.width mismatch"
            );
            assert_eq!(
                actual.height.to_bits(),
                expected.height.to_bits(),
                "{label}: bounds.height mismatch"
            );
        }
        (actual, expected) => {
            panic!("{label}: bounds presence mismatch (actual={actual:?}, expected={expected:?})")
        }
    }
}

fn decode_optional_string(value: &Value) -> Option<String> {
    let present = value["present"]
        .as_bool()
        .expect("optional-string wrapper has a boolean `present` field");
    if !present {
        return None;
    }
    Some(
        value["value"]
            .as_str()
            .expect("optional-string wrapper's value present when `present` is true")
            .to_string(),
    )
}

fn decode_piece_id_list(value: &Value) -> Vec<PieceId> {
    value
        .as_array()
        .expect("piece id array present")
        .iter()
        .map(|entry| PieceId::new(entry.as_str().expect("piece id is a string")))
        .collect()
}

/// Decodes one `EncodedPlacedPiece` (`{pieceId, points, placement:
/// {translateX, translateY, rotationDeg, mirrored}, collisionTransform:
/// {index, rotationDeg, mirrored, reason}}`) into a fresh
/// `Arc<IrregularPlacedPiece>`.
fn decode_placed_piece(value: &Value) -> Arc<IrregularPlacedPiece> {
    let piece_id = PieceId::new(
        value["pieceId"]
            .as_str()
            .expect("placed piece has a pieceId"),
    );
    let points = decode_points(&value["points"]);
    let placement = &value["placement"];
    let collision_transform = &value["collisionTransform"];
    Arc::new(IrregularPlacedPiece {
        placement: IrregularPlacement {
            piece_id: None,
            source_piece_id: piece_id.clone(),
            placement_reference: None,
            transform: IrregularTransform {
                translate_x: bits_field(placement, "translateX"),
                translate_y: bits_field(placement, "translateY"),
                rotation_deg: bits_field(placement, "rotationDeg"),
                mirrored: placement["mirrored"]
                    .as_bool()
                    .expect("placement.mirrored present"),
            },
        },
        collision_geometry: TransformedCollisionGeometry {
            source_piece_id: piece_id,
            transform: IrregularTransformCandidate {
                index: bits_field(collision_transform, "index"),
                rotation_deg: bits_field(collision_transform, "rotationDeg"),
                mirrored: collision_transform["mirrored"]
                    .as_bool()
                    .expect("collisionTransform.mirrored present"),
                reason: decode_transform_reason(
                    collision_transform["reason"]
                        .as_str()
                        .expect("collisionTransform.reason present"),
                ),
            },
            polygon: IrregularPolygon::new(points),
            bounds: {
                // `TransformedCollisionGeometry.bounds` is not separately
                // recorded per placed piece (it is not read by any
                // `IrregularBeamState` canonical-key/bounds/contact
                // derivation this test exercises -- only
                // `polygon.points`/`placement.transform` are); a placeholder
                // finite value keeps the trusted carrier well-formed without
                // asserting on a field this cluster never reads.
                irregular_nesting_native::domain::IrregularBounds::new(0.0, 0.0, 0.0, 0.0)
            },
        },
    })
}

/// Decodes a `contactSignatureContinuationIdentity`-shaped JSON string
/// (`[[signature, count], ...]`) into a canonically-sorted `(String, f64)`
/// vector, for order-independent content comparison (see this file's top
/// doc, "`localeCompare`-dependent fields").
fn decode_signature_pairs_sorted(json_str: &str) -> Vec<(String, u64)> {
    let value: Value = serde_json::from_str(json_str)
        .unwrap_or_else(|err| panic!("invalid signature-pairs JSON: {err}"));
    let mut pairs: Vec<(String, u64)> = value
        .as_array()
        .expect("signature pairs is a JSON array")
        .iter()
        .map(|entry| {
            let tuple = entry.as_array().expect("signature pair is a 2-tuple");
            let signature = tuple[0]
                .as_str()
                .expect("signature is a string")
                .to_string();
            // Counts are always non-negative safe integers by construction
            // (`is_safe_integer` guarded throughout `beam_state.rs`); bit
            // pattern is irrelevant here, only the exact integer value.
            let count = tuple[1].as_f64().expect("count is a number") as u64;
            (signature, count)
        })
        .collect();
    pairs.sort();
    pairs
}

fn assert_contact_signature_identity_content_matches(
    actual: Option<String>,
    expected_value: &Value,
    label: &str,
) {
    let expected = decode_optional_string(expected_value);
    match (actual, expected) {
        (None, None) => {}
        (Some(actual_str), Some(expected_str)) => {
            assert_eq!(
                decode_signature_pairs_sorted(&actual_str),
                decode_signature_pairs_sorted(&expected_str),
                "{label}: contact signature continuation identity CONTENT (order-independent) mismatch"
            );
        }
        (actual, expected) => panic!(
            "{label}: contact signature continuation identity presence mismatch \
             (actual={actual:?}, expected present={})",
            expected.is_some()
        ),
    }
}

/// Structurally validates `continuation_metadata_identity()` against the
/// recorded TS string: decodes both as JSON objects, asserts the
/// `canonicalEntryKeys` field is byte-identical (no locale dependency), the
/// `nearCompleteStructuralContactSignatureCounts` key's *presence* matches
/// (content already independently verified via
/// [`assert_contact_signature_identity_content_matches`] on the un-nested
/// value), and the `placedCollisionIndex` field is present as a non-empty
/// string (its exact bytes are deliberately not compared -- see
/// `validation::spatial_index::PlacedCollisionSpatialIndex::continuation_identity`'s
/// own doc for why that field's `localeCompare`-derived bytes are not
/// ported byte-exact either).
fn assert_continuation_metadata_identity_matches(
    actual: &str,
    expected_str: &str,
    expected_contact_signature_present: bool,
    label: &str,
) {
    let actual_value: Value = serde_json::from_str(actual).unwrap_or_else(|err| {
        panic!("{label}: actual continuationMetadataIdentity not valid JSON: {err}")
    });
    let expected_value: Value = serde_json::from_str(expected_str).unwrap_or_else(|err| {
        panic!("{label}: expected continuationMetadataIdentity not valid JSON: {err}")
    });

    assert_eq!(
        actual_value["canonicalEntryKeys"], expected_value["canonicalEntryKeys"],
        "{label}: continuationMetadataIdentity.canonicalEntryKeys mismatch"
    );
    assert_eq!(
        actual_value
            .get("nearCompleteStructuralContactSignatureCounts")
            .is_some(),
        expected_contact_signature_present,
        "{label}: continuationMetadataIdentity nearCompleteStructuralContactSignatureCounts presence mismatch"
    );
    assert!(
        actual_value["placedCollisionIndex"]
            .as_str()
            .is_some_and(|s| !s.is_empty()),
        "{label}: continuationMetadataIdentity.placedCollisionIndex must be a non-empty string"
    );
}

// ---------------------------------------------------------------------------
// Section A: ring-key byte-exact values.
// ---------------------------------------------------------------------------
#[test]
fn ring_key_values_match_ts_production_oracle() {
    let file = load_vectors();
    let cases = file["ringKeyValues"]["cases"]
        .as_array()
        .expect("ringKeyValues.cases present");
    assert_eq!(
        cases.len() as u64,
        file["ringKeyValues"]["caseCount"]
            .as_u64()
            .expect("caseCount present")
    );
    assert!(cases.len() >= 300, "expected a broad ring-key value sweep");

    for case in cases {
        let label = case["category"].as_str().expect("category present");
        let points = decode_points(&case["points"]);
        let tx = bits_field(case, "translateX");
        let ty = bits_field(case, "translateY");
        let expected_key = case["key"].as_str().expect("key present");
        let actual_key = canonical_collision_polygon_key(&points, tx, ty);
        assert_eq!(
            actual_key, expected_key,
            "{label}: canonical ring key mismatch"
        );
    }
}

// ---------------------------------------------------------------------------
// Section B: ring-key invariance sweeps.
// ---------------------------------------------------------------------------
fn rotated_start(points: &[IrregularPoint], offset: usize) -> Vec<IrregularPoint> {
    let n = points.len();
    (0..n).map(|index| points[(index + offset) % n]).collect()
}

fn reversed_ring(points: &[IrregularPoint]) -> Vec<IrregularPoint> {
    let mut reversed = points.to_vec();
    reversed.reverse();
    reversed
}

/// Reconstructs one invariance variant's point array from the recorded base
/// ring, per this variant's `label` (see `dump-beam-state.ts`'s
/// `recordInvariance`, whose four label shapes this mirrors exactly:
/// `rotated-start-{n}`, `reversed-winding`, `reversed-winding-rotated-start-{n}`).
fn variant_points(base: &[IrregularPoint], label: &str) -> Vec<IrregularPoint> {
    if label == "reversed-winding" {
        return reversed_ring(base);
    }
    if let Some(offset_str) = label.strip_prefix("reversed-winding-rotated-start-") {
        let offset: usize = offset_str.parse().expect("offset parses as usize");
        return rotated_start(&reversed_ring(base), offset);
    }
    if let Some(offset_str) = label.strip_prefix("rotated-start-") {
        let offset: usize = offset_str.parse().expect("offset parses as usize");
        return rotated_start(base, offset);
    }
    panic!("unrecognized ring-key invariance variant label: {label}");
}

#[test]
fn ring_key_invariance_sweeps_hold_and_match_ts_production_oracle() {
    let file = load_vectors();
    let cases = file["ringKeyInvariance"]["cases"]
        .as_array()
        .expect("ringKeyInvariance.cases present");
    assert_eq!(
        cases.len() as u64,
        file["ringKeyInvariance"]["caseCount"]
            .as_u64()
            .expect("caseCount present")
    );
    assert!(!cases.is_empty());

    for case in cases {
        let label = case["category"].as_str().expect("category present");
        let base_points = decode_points(&case["points"]);
        let tx = bits_field(case, "translateX");
        let ty = bits_field(case, "translateY");
        let expected_base_key = case["baseKey"].as_str().expect("baseKey present");

        let actual_base_key = canonical_collision_polygon_key(&base_points, tx, ty);
        assert_eq!(
            actual_base_key, expected_base_key,
            "{label}: base ring key mismatch"
        );

        let variants = case["variants"].as_array().expect("variants present");
        for variant in variants {
            let variant_label = variant["label"].as_str().expect("variant.label present");
            let expected_variant_key = variant["key"].as_str().expect("variant.key present");
            let variant_ring = variant_points(&base_points, variant_label);
            let actual_variant_key = canonical_collision_polygon_key(&variant_ring, tx, ty);
            assert_eq!(
                actual_variant_key, expected_variant_key,
                "{label}/{variant_label}: variant ring key mismatch vs. TS oracle"
            );
            // The defining invariance property itself: every start-vertex
            // rotation and every winding direction must key identically to
            // the base ring.
            assert_eq!(
                actual_variant_key, actual_base_key,
                "{label}/{variant_label}: variant key not invariant with base key"
            );
        }
    }
}

// ---------------------------------------------------------------------------
// Section C: incremental state chains.
// ---------------------------------------------------------------------------
fn assert_snapshot_matches(state: &Arc<IrregularBeamState>, expected: &Value, label: &str) {
    assert_eq!(
        state.canonical_occupied_geometry_key,
        expected["canonicalOccupiedGeometryKey"]
            .as_str()
            .expect("canonicalOccupiedGeometryKey present"),
        "{label}: canonicalOccupiedGeometryKey mismatch"
    );
    assert_optional_bounds_eq(
        state.translated_collision_bounds,
        &expected["translatedCollisionBounds"],
        &format!("{label}: translatedCollisionBounds"),
    );
    assert_optional_bits_eq(
        state.shared_collision_boundary_length_mm,
        expected,
        "sharedCollisionBoundaryLengthMm",
        label,
    );
    assert_optional_bits_eq(
        state.shared_collision_boundary_contact_units,
        expected,
        "sharedCollisionBoundaryContactUnits",
        label,
    );
    assert_optional_bits_eq(
        state.near_complete_structural_contact_count,
        expected,
        "nearCompleteStructuralContactCount",
        label,
    );
    assert_optional_bits_eq(
        state.dominant_near_complete_structural_contact_count,
        expected,
        "dominantNearCompleteStructuralContactCount",
        label,
    );
    assert_eq!(
        state.unplaced_piece_ids,
        decode_piece_id_list(&expected["unplacedPieceIds"]),
        "{label}: unplacedPieceIds mismatch"
    );
    assert_eq!(
        state.unplaced_source_piece_ids,
        decode_piece_id_list(&expected["unplacedSourcePieceIds"]),
        "{label}: unplacedSourcePieceIds mismatch"
    );
    assert_eq!(
        state.placement_order,
        decode_piece_id_list(&expected["placementOrder"]),
        "{label}: placementOrder mismatch"
    );
    assert_eq!(
        state.canonical_entry_continuation_identity(),
        expected["canonicalEntryContinuationIdentity"]
            .as_str()
            .expect("canonicalEntryContinuationIdentity present"),
        "{label}: canonicalEntryContinuationIdentity mismatch"
    );
    assert_contact_signature_identity_content_matches(
        state.contact_signature_continuation_identity(),
        &expected["contactSignatureContinuationIdentity"],
        label,
    );
    assert_continuation_metadata_identity_matches(
        &state.continuation_metadata_identity(),
        expected["continuationMetadataIdentity"]
            .as_str()
            .expect("continuationMetadataIdentity present"),
        decode_optional_string(&expected["contactSignatureContinuationIdentity"]).is_some(),
        label,
    );

    assert_quarter_turn_result(
        Arc::clone(state).with_bottom_left_anchored(),
        &expected["bottomLeftAnchored"],
        &format!("{label}: bottomLeftAnchored"),
    );
    let expected_projection_key = expected["bottomLeftAnchoredProjectionKey"].as_str();
    assert_eq!(
        state
            .bottom_left_anchored_canonical_occupied_geometry_key()
            .as_deref(),
        expected_projection_key,
        "{label}: bottomLeftAnchoredProjectionKey mismatch"
    );
    assert_quarter_turn_result(
        Arc::clone(state).with_quarter_turn_bottom_left(IrregularQuarterTurnDegrees::Ninety),
        &expected["quarterTurn90"],
        &format!("{label}: quarterTurn90"),
    );
    assert_quarter_turn_result(
        Arc::clone(state).with_quarter_turn_bottom_left(IrregularQuarterTurnDegrees::OneEighty),
        &expected["quarterTurn180"],
        &format!("{label}: quarterTurn180"),
    );
    assert_quarter_turn_result(
        Arc::clone(state).with_quarter_turn_bottom_left(IrregularQuarterTurnDegrees::TwoSeventy),
        &expected["quarterTurn270"],
        &format!("{label}: quarterTurn270"),
    );
}

fn assert_quarter_turn_result(
    actual: Option<Arc<IrregularBeamState>>,
    expected: &Value,
    label: &str,
) {
    let expected_present = expected["present"].as_bool().expect("present flag present");
    match (actual, expected_present) {
        (None, false) => {}
        (Some(state), true) => {
            assert_eq!(
                state.canonical_occupied_geometry_key,
                expected["canonicalOccupiedGeometryKey"]
                    .as_str()
                    .expect("canonicalOccupiedGeometryKey present"),
                "{label}: canonicalOccupiedGeometryKey mismatch"
            );
            assert_optional_bounds_eq(
                state.translated_collision_bounds,
                &expected["translatedCollisionBounds"],
                &format!("{label}: translatedCollisionBounds"),
            );
            let expected_pieces = expected["placedPieces"]
                .as_array()
                .expect("placedPieces present");
            assert_eq!(
                state.placed_collision_geometries.len(),
                expected_pieces.len(),
                "{label}: placedPieces length mismatch"
            );
            for (actual_piece, expected_piece) in state
                .placed_collision_geometries
                .iter()
                .zip(expected_pieces.iter())
            {
                assert_bits_eq(
                    actual_piece.placement.transform.translate_x,
                    &expected_piece["placement"],
                    "translateX",
                    &format!("{label}: placed piece translateX"),
                );
                assert_bits_eq(
                    actual_piece.placement.transform.translate_y,
                    &expected_piece["placement"],
                    "translateY",
                    &format!("{label}: placed piece translateY"),
                );
                assert_bits_eq(
                    actual_piece.placement.transform.rotation_deg,
                    &expected_piece["placement"],
                    "rotationDeg",
                    &format!("{label}: placed piece placement rotationDeg"),
                );
                assert_eq!(
                    actual_piece.placement.transform.mirrored,
                    expected_piece["placement"]["mirrored"]
                        .as_bool()
                        .expect("placement.mirrored present"),
                    "{label}: placed piece placement mirrored mismatch"
                );
                assert_bits_eq(
                    actual_piece.collision_geometry.transform.rotation_deg,
                    &expected_piece["collisionTransform"],
                    "rotationDeg",
                    &format!("{label}: placed piece collisionTransform rotationDeg"),
                );
                let expected_points = decode_points(&expected_piece["points"]);
                assert_eq!(
                    actual_piece.collision_geometry.polygon.points.len(),
                    expected_points.len(),
                    "{label}: placed piece point count mismatch"
                );
                for (actual_point, expected_point) in actual_piece
                    .collision_geometry
                    .polygon
                    .points
                    .iter()
                    .zip(expected_points.iter())
                {
                    assert_eq!(
                        actual_point.x.to_bits(),
                        expected_point.x.to_bits(),
                        "{label}: placed piece point.x mismatch"
                    );
                    assert_eq!(
                        actual_point.y.to_bits(),
                        expected_point.y.to_bits(),
                        "{label}: placed piece point.y mismatch"
                    );
                }
            }
        }
        (actual, expected_present) => panic!(
            "{label}: presence mismatch (actual_present={}, expected_present={expected_present})",
            actual.is_some()
        ),
    }
}

#[test]
fn state_chains_replay_incrementally_and_match_every_recorded_snapshot() {
    let file = load_vectors();
    let chains = file["chains"]["cases"]
        .as_array()
        .expect("chains.cases present");
    assert!(chains.len() >= 20, "expected many replayed chains");

    let mut total_steps = 0usize;
    for chain in chains {
        let category = chain["category"].as_str().expect("category present");
        let mut state = IrregularBeamState::empty(Vec::new());
        assert_snapshot_matches(
            &state,
            &chain["initialSnapshot"],
            &format!("{category}: initial"),
        );

        let steps = chain["steps"].as_array().expect("steps present");
        for (step_index, step) in steps.iter().enumerate() {
            total_steps += 1;
            let kind = step["kind"].as_str().expect("step.kind present");
            let step_label = format!("{category}: step {step_index} ({kind})");
            state = match kind {
                "place" => {
                    let piece = decode_placed_piece(&step["placedPiece"]);
                    let placement_order_piece_id = PieceId::new(
                        step["placementOrderPieceId"]
                            .as_str()
                            .expect("placementOrderPieceId present"),
                    );
                    state.with_placement(WithPlacementInput {
                        remaining_prepared_pieces: Vec::new(),
                        placed_collision_geometry: piece,
                        placement_order_piece_id,
                        on_phase_timings: None,
                        timing_now: None,
                    })
                }
                "unplace" => {
                    let unplaced_piece_id = PieceId::new(
                        step["unplacedPieceId"]
                            .as_str()
                            .expect("unplacedPieceId present"),
                    );
                    state.with_unplaced_piece(WithUnplacedPieceInput {
                        remaining_prepared_pieces: Vec::new(),
                        unplaced_piece_id,
                    })
                }
                other => panic!("unrecognized step kind: {other}"),
            };
            assert_snapshot_matches(&state, &step["snapshotAfter"], &step_label);
        }
    }
    assert!(total_steps >= 100, "expected many replayed chain steps");
}

// ---------------------------------------------------------------------------
// Section D: `-0`-producing coordinates/translations.
// ---------------------------------------------------------------------------
#[test]
fn negative_zero_cases_match_ts_production_oracle_and_fold_to_the_comparison_key() {
    let file = load_vectors();
    let cases = file["negativeZero"]["cases"]
        .as_array()
        .expect("negativeZero.cases present");
    assert!(!cases.is_empty());

    for case in cases {
        let label = case["category"].as_str().expect("category present");
        let points = decode_points(&case["points"]);
        let tx = bits_field(case, "translateX");
        let ty = bits_field(case, "translateY");
        let expected_key = case["key"].as_str().expect("key present");
        let actual_key = canonical_collision_polygon_key(&points, tx, ty);
        assert_eq!(actual_key, expected_key, "{label}: key mismatch");

        let comparison_points = decode_points(&case["comparisonPoints"]);
        let comparison_tx = bits_field(case, "comparisonTranslateX");
        let comparison_ty = bits_field(case, "comparisonTranslateY");
        let expected_comparison_key = case["comparisonKey"]
            .as_str()
            .expect("comparisonKey present");
        let actual_comparison_key =
            canonical_collision_polygon_key(&comparison_points, comparison_tx, comparison_ty);
        assert_eq!(
            actual_comparison_key, expected_comparison_key,
            "{label}: comparisonKey mismatch"
        );

        // The defining `-0` property: the `-0`-producing case must key
        // identically to its plain-zero comparison case.
        assert_eq!(
            actual_key, actual_comparison_key,
            "{label}: -0-producing key not folded to match the plain-zero comparison key"
        );
    }
}

// ---------------------------------------------------------------------------
// Section E: dedup identity across insertion order.
// ---------------------------------------------------------------------------
fn replay_order_key(pieces: &[Value]) -> String {
    let mut state = IrregularBeamState::empty(Vec::new());
    for piece_value in pieces {
        let piece = decode_placed_piece(piece_value);
        let placement_order_piece_id = piece.placement.source_piece_id.clone();
        state = state.with_placement(WithPlacementInput {
            remaining_prepared_pieces: Vec::new(),
            placed_collision_geometry: piece,
            placement_order_piece_id,
            on_phase_timings: None,
            timing_now: None,
        });
    }
    state.canonical_occupied_geometry_key.clone()
}

#[test]
fn dedup_identity_is_independent_of_placement_insertion_order() {
    let file = load_vectors();
    let cases = file["dedup"]["cases"]
        .as_array()
        .expect("dedup.cases present");
    assert!(!cases.is_empty());

    for case in cases {
        let label = case["category"].as_str().expect("category present");
        let order_a = case["orderA"].as_array().expect("orderA present");
        let order_b = case["orderB"].as_array().expect("orderB present");
        let expected_key_a = case["keyA"].as_str().expect("keyA present");
        let expected_key_b = case["keyB"].as_str().expect("keyB present");

        let actual_key_a = replay_order_key(order_a);
        let actual_key_b = replay_order_key(order_b);
        assert_eq!(actual_key_a, expected_key_a, "{label}: keyA mismatch");
        assert_eq!(actual_key_b, expected_key_b, "{label}: keyB mismatch");
        assert_eq!(
            actual_key_a, actual_key_b,
            "{label}: dedup identity differs across insertion order"
        );
    }
}

// ---------------------------------------------------------------------------
// Header sanity.
// ---------------------------------------------------------------------------
#[test]
fn vector_file_reports_at_least_500_total_cases() {
    let file = load_vectors();
    let total = file["totalCaseCount"]
        .as_u64()
        .expect("totalCaseCount present");
    assert!(
        total >= 500,
        "expected >=500 total beam-state vectors, got {total}"
    );
}

/// Guards against a stale `IrregularBeamStateInput`/`IrregularQuarterTurnDegrees`
/// import going unused if a future edit trims which fields this file reads
/// directly (both types are exercised transitively above via the public
/// `IrregularBeamState` API, but keeping a direct, explicit construction
/// here proves `IrregularBeamStateInput`'s raw-construction entry point --
/// mirroring TS's `new IrregularBeamState({...})` -- independently of the
/// `empty`/`with_placement` convenience paths every other test in this file
/// exercises).
#[test]
fn from_input_raw_construction_matches_incremental_construction_for_the_same_geometry() {
    let file = load_vectors();
    let chain = file["chains"]["cases"][0].clone();
    let steps = chain["steps"].as_array().expect("steps present");
    let mut incremental = IrregularBeamState::empty(Vec::new());
    let mut placed_pieces = Vec::new();
    for step in steps {
        if step["kind"].as_str() == Some("place") {
            let piece = decode_placed_piece(&step["placedPiece"]);
            let placement_order_piece_id = piece.placement.source_piece_id.clone();
            incremental = incremental.with_placement(WithPlacementInput {
                remaining_prepared_pieces: Vec::new(),
                placed_collision_geometry: Arc::clone(&piece),
                placement_order_piece_id,
                on_phase_timings: None,
                timing_now: None,
            });
            placed_pieces.push(piece);
        }
    }

    let raw = IrregularBeamState::from_input(IrregularBeamStateInput {
        remaining_prepared_pieces: Vec::new(),
        placed_collision_geometries: placed_pieces,
        unplaced_piece_ids: None,
        unplaced_source_piece_ids: None,
        placement_order: Vec::new(),
        parent: None,
        placed_collision_index: None,
    });

    assert_eq!(
        raw.canonical_occupied_geometry_key, incremental.canonical_occupied_geometry_key,
        "from-scratch construction must match incrementally-built construction \
         for the same placed-piece set (search-scoring.md §7.4's equivalence)"
    );
    assert_eq!(
        raw.shared_collision_boundary_length_mm.map(f64::to_bits),
        incremental
            .shared_collision_boundary_length_mm
            .map(f64::to_bits)
    );
}
