//! Differential vector test for
//! `crates/irregular-nesting-native/src/checkpoints/canonical_json.rs`.
//!
//! Loads `tests/vectors/canonical-json.json` (generated by
//! `scripts/rust-parity/dump-canonical-json.ts`, per
//! `docs/planning/rust-irregular-backend/stage0-rulings.md` R14) and asserts
//! the Rust port reproduces every recorded output exactly: byte-exact
//! strings for every `"value"`-outcome vector, an observed `panic` for every
//! `"throws"`-outcome vector (Encoder C given a `bigint`), and a `None`
//! return for every `"undefined"`-outcome vector (a bare top-level
//! `JsValue::Undefined` input).

use std::fs;
use std::panic::{self, AssertUnwindSafe};

use irregular_nesting_native::checkpoints::canonical_json::{
    canonical_entry_list_key, canonical_number, canonical_record, canonical_token,
    intrinsic_capacity_canonical_json, intrinsic_periodic_canonical_json,
    intrinsic_strict_canonical_json, locale_compare_keys, JsValue,
};
use num_bigint::BigInt;
use serde_json::Value;

fn load_vectors() -> Value {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/vectors/canonical-json.json"
    );
    let raw = fs::read_to_string(path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&raw).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

// ---------------------------------------------------------------------------
// Tagged-JSON decoder mirroring `scripts/rust-parity/dump-canonical-json.ts`'s
// `toVectorJson` encoder exactly: `$undefined`/`$bigint`/`$number`/`$arr`/
// `$obj`/`$map` single-key tagged objects disambiguate values with no native
// JSON representation (or, for `$arr`/`$obj`, values whose insertion order
// must survive the JSON round-trip exactly, independent of any JSON map
// implementation's own ordering guarantees).
// ---------------------------------------------------------------------------

fn decode_number_tag(tag: &str) -> f64 {
    match tag {
        "NaN" => f64::NAN,
        "Infinity" => f64::INFINITY,
        "-Infinity" => f64::NEG_INFINITY,
        "-0" => -0.0,
        other => other
            .parse::<f64>()
            .unwrap_or_else(|_| panic!("unrecognized $number tag: {other}")),
    }
}

fn decode_vector_json(value: &Value) -> JsValue {
    match value {
        Value::Null => JsValue::Null,
        Value::Bool(b) => JsValue::Bool(*b),
        Value::Number(n) => JsValue::Num(
            n.as_f64()
                .unwrap_or_else(|| panic!("JSON number {n} is not representable as f64")),
        ),
        Value::String(s) => JsValue::Str(s.clone()),
        Value::Array(_) => {
            panic!("bare JSON arrays are not used by the vector schema; expected an $arr tag")
        }
        Value::Object(map) => {
            if map.len() == 1 {
                if let Some(Value::Bool(true)) = map.get("$undefined") {
                    return JsValue::Undefined;
                }
                if let Some(Value::String(s)) = map.get("$bigint") {
                    return JsValue::BigInt(
                        s.parse::<BigInt>()
                            .unwrap_or_else(|_| panic!("invalid $bigint decimal string: {s}")),
                    );
                }
                if let Some(Value::String(s)) = map.get("$number") {
                    return JsValue::Num(decode_number_tag(s));
                }
                if let Some(Value::Array(items)) = map.get("$arr") {
                    return JsValue::Arr(items.iter().map(decode_vector_json).collect());
                }
                if let Some(Value::Array(items)) = map.get("$obj") {
                    return JsValue::Obj(
                        items
                            .iter()
                            .map(|pair| {
                                let pair = pair
                                    .as_array()
                                    .unwrap_or_else(|| panic!("$obj entry must be [key, value]"));
                                let key = pair
                                    .first()
                                    .and_then(Value::as_str)
                                    .unwrap_or_else(|| panic!("$obj entry key must be a string"))
                                    .to_string();
                                let field_value = pair
                                    .get(1)
                                    .unwrap_or_else(|| panic!("$obj entry missing value"));
                                (key, decode_vector_json(field_value))
                            })
                            .collect(),
                    );
                }
                if let Some(Value::Array(items)) = map.get("$map") {
                    return JsValue::Map(
                        items
                            .iter()
                            .map(|pair| {
                                let pair = pair
                                    .as_array()
                                    .unwrap_or_else(|| panic!("$map entry must be [key, value]"));
                                let key = pair
                                    .first()
                                    .unwrap_or_else(|| panic!("$map entry missing key"));
                                let entry_value = pair
                                    .get(1)
                                    .unwrap_or_else(|| panic!("$map entry missing value"));
                                (decode_vector_json(key), decode_vector_json(entry_value))
                            })
                            .collect(),
                    );
                }
            }
            panic!("unrecognized tagged vector JSON object: {value:?}");
        }
    }
}

// ---------------------------------------------------------------------------
// Encoder A/B/C vector shape and assertion helper.
// ---------------------------------------------------------------------------

fn assert_encoder_vectors(label: &str, vectors: &[Value], encoder: fn(&JsValue) -> Option<String>) {
    assert!(!vectors.is_empty(), "{label}: expected at least one vector");
    for vector in vectors {
        let id = vector["id"].as_str().expect("vector id is a string");
        let input = decode_vector_json(&vector["input"]);
        let outcome = vector["outcome"].as_str().expect("outcome is a string");
        match outcome {
            "value" => {
                let expected = vector["expected"]
                    .as_str()
                    .unwrap_or_else(|| panic!("{label}[{id}]: expected string missing"));
                let actual = encoder(&input);
                assert_eq!(
                    actual.as_deref(),
                    Some(expected),
                    "{label}[{id}]: encoder output mismatch"
                );
            }
            "undefined" => {
                let actual = encoder(&input);
                assert_eq!(
                    actual, None,
                    "{label}[{id}]: expected the encoder to return None (raw JS `undefined`)"
                );
            }
            "throws" => {
                let result = panic::catch_unwind(AssertUnwindSafe(|| encoder(&input)));
                assert!(
                    result.is_err(),
                    "{label}[{id}]: expected the encoder to panic (real TS throws here)"
                );
            }
            other => panic!("{label}[{id}]: unrecognized outcome tag: {other}"),
        }
    }
}

#[test]
fn capacity_encoder_matches_oracle() {
    let document = load_vectors();
    let vectors = document["capacityVectors"]
        .as_array()
        .expect("capacityVectors array");
    assert!(
        vectors.len() >= 100,
        "expected a broad capacity-encoder vector matrix, got {}",
        vectors.len()
    );
    assert_encoder_vectors(
        "capacityVectors",
        vectors,
        intrinsic_capacity_canonical_json,
    );
}

#[test]
fn strict_encoder_matches_oracle() {
    let document = load_vectors();
    let vectors = document["strictVectors"]
        .as_array()
        .expect("strictVectors array");
    assert!(
        vectors.len() >= 100,
        "expected a broad strict-encoder vector matrix, got {}",
        vectors.len()
    );
    assert_encoder_vectors("strictVectors", vectors, intrinsic_strict_canonical_json);
}

#[test]
fn periodic_encoder_matches_oracle() {
    let document = load_vectors();
    let vectors = document["periodicVectors"]
        .as_array()
        .expect("periodicVectors array");
    assert!(
        vectors.len() >= 100,
        "expected a broad periodic-encoder vector matrix, got {}",
        vectors.len()
    );
    assert_encoder_vectors(
        "periodicVectors",
        vectors,
        intrinsic_periodic_canonical_json,
    );
    // At least one real "throws" vector must exist and actually panic, or
    // this test suite could pass vacuously without ever proving the
    // no-bigint-branch behavior.
    let has_throws_case = vectors
        .iter()
        .any(|vector| vector["outcome"] == Value::String("throws".to_string()));
    assert!(
        has_throws_case,
        "expected at least one 'throws' vector for the periodic encoder's missing bigint branch"
    );
}

#[test]
fn strict_map_vectors_match_oracle() {
    let document = load_vectors();
    let vectors = document["strictMapVectors"]
        .as_array()
        .expect("strictMapVectors array");
    assert!(
        !vectors.is_empty(),
        "expected at least one Map vector for the strict (Encoder B) Map-handling branch"
    );
    assert_encoder_vectors("strictMapVectors", vectors, intrinsic_strict_canonical_json);
    // Every vector here must actually be Map-shaped input, or this suite
    // would not be exercising Encoder B's `instanceof Map` branch at all.
    for vector in vectors {
        let input = decode_vector_json(&vector["input"]);
        assert!(
            matches!(input, JsValue::Map(_)),
            "strictMapVectors[{}]: expected Map-shaped input",
            vector["id"]
        );
    }
}

// ---------------------------------------------------------------------------
// Encoder D vectors: `canonicalToken`/`canonicalNumber`/`canonicalRecord`/
// `canonicalEntryListKey`.
// ---------------------------------------------------------------------------

#[test]
fn canonical_token_matches_oracle() {
    let document = load_vectors();
    let vectors = document["tokenVectors"]
        .as_array()
        .expect("tokenVectors array");
    assert!(!vectors.is_empty(), "expected token vectors");
    for vector in vectors {
        let id = vector["id"].as_str().expect("id is a string");
        let value = vector["value"].as_str().expect("value is a string");
        let expected = vector["expected"].as_str().expect("expected is a string");
        assert_eq!(
            canonical_token(value),
            expected,
            "tokenVectors[{id}] mismatch for value={value:?}"
        );
    }
}

#[test]
fn canonical_number_matches_oracle() {
    let document = load_vectors();
    let vectors = document["canonicalNumberVectors"]
        .as_array()
        .expect("canonicalNumberVectors array");
    assert!(!vectors.is_empty(), "expected canonicalNumber vectors");
    for vector in vectors {
        let id = vector["id"].as_str().expect("id is a string");
        let value = match decode_vector_json(&vector["value"]) {
            JsValue::Num(n) => n,
            other => panic!("canonicalNumberVectors[{id}]: expected a Num value, got {other:?}"),
        };
        let expected = vector["expected"].as_str().expect("expected is a string");
        let actual = canonical_number(value);
        assert_eq!(
            actual,
            expected,
            "canonicalNumberVectors[{id}] mismatch for value={value:?} (bits={:016x})",
            value.to_bits()
        );
    }
}

#[test]
fn canonical_record_matches_oracle() {
    let document = load_vectors();
    let vectors = document["recordVectors"]
        .as_array()
        .expect("recordVectors array");
    assert!(!vectors.is_empty(), "expected canonicalRecord vectors");
    for vector in vectors {
        let id = vector["id"].as_str().expect("id is a string");
        let fields: Vec<Vec<String>> = vector["fields"]
            .as_array()
            .expect("fields is an array")
            .iter()
            .map(|row| {
                row.as_array()
                    .expect("field row is an array")
                    .iter()
                    .map(|entry| {
                        entry
                            .as_str()
                            .expect("field row entry is a string")
                            .to_string()
                    })
                    .collect()
            })
            .collect();
        let expected = vector["expected"].as_str().expect("expected is a string");
        assert_eq!(
            canonical_record(&fields),
            expected,
            "recordVectors[{id}] mismatch for fields={fields:?}"
        );
    }
}

#[test]
fn canonical_entry_list_key_matches_oracle() {
    let document = load_vectors();
    let vectors = document["entryListKeyVectors"]
        .as_array()
        .expect("entryListKeyVectors array");
    assert!(
        !vectors.is_empty(),
        "expected canonicalEntryListKey vectors"
    );
    for vector in vectors {
        let id = vector["id"].as_str().expect("id is a string");
        let entry_keys: Vec<String> = vector["entryKeys"]
            .as_array()
            .expect("entryKeys is an array")
            .iter()
            .map(|entry| entry.as_str().expect("entryKey is a string").to_string())
            .collect();
        let expected = vector["expected"].as_str().expect("expected is a string");
        assert_eq!(
            canonical_entry_list_key(&entry_keys),
            expected,
            "entryListKeyVectors[{id}] mismatch for entryKeys={entry_keys:?}"
        );
    }
}

/// Direct oracle test for `locale_compare_keys` — the hand-derived,
/// empirically-validated `localeCompare`-equivalent comparator shared by
/// Encoders B/C. Closes a coverage gap: prior to this test, no vector in
/// this suite compared `locale_compare_keys` against real
/// `String.prototype.localeCompare` output directly; every other vector only
/// exercised it indirectly through object-key sort order on a handful of
/// curated key alphabets. `localeCompareVectors` (from
/// `dump-canonical-json.ts`) is an exhaustive single-character matrix over
/// the full printable-ASCII range plus randomized multi-character strings
/// from that same alphabet — this is the actual "committed, pinned proof"
/// [`locale_compare_keys`]'s own doc comment cites.
#[test]
fn locale_compare_keys_matches_oracle_over_full_printable_ascii_range() {
    let document = load_vectors();
    let vectors = document["localeCompareVectors"]
        .as_array()
        .expect("localeCompareVectors array");
    assert!(
        vectors.len() >= 9000,
        "expected the exhaustive printable-ASCII single-character matrix (95*95=9025) plus \
         random-string vectors, got {}",
        vectors.len()
    );
    for vector in vectors {
        let id = vector["id"].as_str().expect("id is a string");
        let first = vector["first"].as_str().expect("first is a string");
        let second = vector["second"].as_str().expect("second is a string");
        let expected_sign = vector["expectedSign"]
            .as_i64()
            .unwrap_or_else(|| panic!("localeCompareVectors[{id}]: expectedSign missing"));
        let expected = match expected_sign {
            -1 => std::cmp::Ordering::Less,
            0 => std::cmp::Ordering::Equal,
            1 => std::cmp::Ordering::Greater,
            other => panic!("localeCompareVectors[{id}]: unrecognized expectedSign {other}"),
        };
        assert_eq!(
            locale_compare_keys(first, second),
            expected,
            "localeCompareVectors[{id}] mismatch for first={first:?} second={second:?}"
        );
    }
}

#[test]
fn header_records_generating_commit_and_meaningful_coverage() {
    let document = load_vectors();
    let header = &document["header"];
    assert!(
        header["generatingCommit"]
            .as_str()
            .is_some_and(|commit| commit.len() == 40),
        "vector file header must record a 40-character generating commit hash"
    );
    let total = header["totalVectorCount"]
        .as_u64()
        .expect("totalVectorCount is present");
    assert!(
        total >= 300,
        "expected at least 300 total vectors per the differential-vector coverage bar, got {total}"
    );
}
