//! Differential-vector test for
//! `crates/irregular-nesting-native/src/capacity/{preflight,material,endpoint}.rs`.
//!
//! Loads `tests/vectors/capacity-core.json`, generated by
//! `scripts/rust-parity/dump-capacity-core.ts` from the REAL production
//! `preflightIntrinsicCompleteCapacity`/`intrinsicCapacityMaterialAreas`/
//! `materializeIntrinsicCapacityEndpoint`/`compareIntrinsicCapacityObjectives`
//! (`src/workers/algorithm/irregular/intrinsicCapacity{Preflight,Material,
//! Endpoint}.ts`), and asserts this crate's Rust port reproduces every
//! recorded outcome exactly:
//! - every preflight verdict (`proven_impossible` with its exact `reason`/
//!   `pieceId` vs `inconclusive`) and its full bigint/f64 measurements,
//! - every material-areas result (`complete` map vs first-invalid-piece
//!   `invalid`), bigint-exact,
//! - every endpoint construction (`materialize_intrinsic_capacity_endpoint`),
//!   including canonical identity/hash, oriented placed/unplaced partition,
//!   and every metric field, f64-bit-exact / bigint-string-exact,
//! - every `compare_intrinsic_capacity_objectives` outcome sign, across both
//!   the synthetic per-key sweep and the real-endpoint-derived objective
//!   pairs.

use std::collections::HashMap;
use std::fs;
use std::sync::Arc;

use irregular_nesting_native::caches::GeometryCacheStore;
use irregular_nesting_native::capacity::endpoint::{
    compare_intrinsic_capacity_objectives, materialize_intrinsic_capacity_endpoint,
    IntrinsicCapacityCavityCache, IntrinsicCapacityEndpoint, IntrinsicCapacityEndpointOrigin,
    IntrinsicCapacityObjective, MaterializeIntrinsicCapacityEndpointInput,
};
use irregular_nesting_native::capacity::material::intrinsic_capacity_material_areas;
use irregular_nesting_native::capacity::material::IntrinsicCapacityMaterialAreas;
use irregular_nesting_native::capacity::preflight::{
    preflight_intrinsic_complete_capacity, IntrinsicCapacityPreflightMeasurements,
    IntrinsicCapacityPreflightOutcome, IntrinsicCapacityProvenImpossibleReason,
};
use irregular_nesting_native::domain::{
    CollisionGeometry, DxfGeometryEntityType, DxfGeometrySummary, ImportedPiece, IrregularBounds,
    IrregularGeometrySettings, IrregularPlacedPiece, IrregularPlacement, IrregularPoint,
    IrregularPolygon, IrregularPreparedPiece, IrregularTransform, IrregularTransformCandidate,
    IrregularTransformReason, PieceId, Rect, SheetSpec, SourceFileId, TransformedCollisionGeometry,
};
use irregular_nesting_native::search::beam_state::{IrregularBeamState, IrregularBeamStateInput};
use num_bigint::BigInt;
use serde_json::Value;

// ---------------------------------------------------------------------------
// Loading + generic decode helpers.
// ---------------------------------------------------------------------------

fn load_vectors() -> Value {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/vectors/capacity-core.json"
    );
    let raw = fs::read_to_string(path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&raw).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

fn parse_f64_bits(hex: &str) -> f64 {
    let stripped = hex
        .strip_prefix("0x")
        .unwrap_or_else(|| panic!("bit-pattern hex must start with 0x, got {hex}"));
    let bits = u64::from_str_radix(stripped, 16)
        .unwrap_or_else(|err| panic!("invalid bit-pattern hex {hex}: {err}"));
    f64::from_bits(bits)
}

fn decode_f64_bits(value: &Value, field: &str) -> f64 {
    parse_f64_bits(
        value[field]
            .as_str()
            .unwrap_or_else(|| panic!("{field} present")),
    )
}

fn decode_optional_f64_bits(value: &Value) -> Option<f64> {
    match value {
        Value::Null => None,
        Value::String(hex) => Some(parse_f64_bits(hex)),
        other => panic!("expected null or bit-pattern hex string, got {other:?}"),
    }
}

fn decode_bigint(value: &Value, field: &str) -> BigInt {
    let text = value[field]
        .as_str()
        .unwrap_or_else(|| panic!("{field} present"));
    text.parse::<BigInt>()
        .unwrap_or_else(|err| panic!("invalid bigint decimal string {text:?} for {field}: {err}"))
}

fn decode_piece_id(value: &Value, field: &str) -> PieceId {
    PieceId::new(
        value[field]
            .as_str()
            .unwrap_or_else(|| panic!("{field} present")),
    )
}

fn decode_string_or_null(value: &Value, field: &str) -> Option<String> {
    match &value[field] {
        Value::Null => None,
        Value::String(s) => Some(s.clone()),
        other => panic!("expected null or string for {field}, got {other:?}"),
    }
}

fn assert_f64_bits_eq(actual: f64, expected: f64, label: &str) {
    assert_eq!(
        actual.to_bits(),
        expected.to_bits(),
        "{label}: f64 bit mismatch (rust={actual} ts={expected})"
    );
}

fn assert_optional_f64_bits_eq(actual: Option<f64>, expected: Option<f64>, label: &str) {
    match (actual, expected) {
        (None, None) => {}
        (Some(a), Some(e)) => assert_f64_bits_eq(a, e, label),
        (a, e) => panic!("{label}: presence mismatch (rust={a:?} ts={e:?})"),
    }
}

// ---------------------------------------------------------------------------
// Rectangle piece builders (mirror the dump script's own fixture builders).
// ---------------------------------------------------------------------------

fn rectangle_points(width: f64, height: f64) -> Vec<IrregularPoint> {
    vec![
        IrregularPoint::new(0.0, 0.0),
        IrregularPoint::new(width, 0.0),
        IrregularPoint::new(width, height),
        IrregularPoint::new(0.0, height),
    ]
}

fn imported_piece(id: &str) -> ImportedPiece {
    ImportedPiece {
        id: PieceId::new(id),
        source_file_id: SourceFileId::new(format!("source-{id}")),
        source_layer: None,
        label: id.to_string(),
        real_bounds: Rect {
            x: 0.0,
            y: 0.0,
            width: 1.0,
            height: 1.0,
        },
        geometry: DxfGeometrySummary {
            entity_type: DxfGeometryEntityType::PresetShape,
            closed: true,
            segments: vec![],
        },
        warnings: vec![],
    }
}

fn decode_transform(value: &Value) -> IrregularTransformCandidate {
    IrregularTransformCandidate {
        index: decode_f64_bits(value, "index"),
        rotation_deg: decode_f64_bits(value, "rotationDeg"),
        mirrored: value["mirrored"].as_bool().expect("mirrored present"),
        reason: IrregularTransformReason::Configured,
    }
}

/// Reconstructs a rectangular `IrregularPreparedPiece` from one
/// `preflightVectors[].pieces[]` entry: `width`/`height` describe the
/// collision polygon (this file's TS counterpart's `preparedRectangle`
/// always uses the same rectangle for the convex hull too, but preflight
/// never reads the hull, so it is left identical here for fidelity).
fn decode_preflight_piece(value: &Value) -> IrregularPreparedPiece {
    let id = value["id"].as_str().expect("id present").to_string();
    let width = decode_f64_bits(value, "width");
    let height = decode_f64_bits(value, "height");
    let shape = IrregularPolygon::new(rectangle_points(width, height));
    let transforms = value["transforms"]
        .as_array()
        .expect("transforms array present")
        .iter()
        .map(decode_transform)
        .collect();
    IrregularPreparedPiece {
        piece_id: Some(PieceId::new(&id)),
        interchangeability_key: None,
        source: imported_piece(&id),
        allow_mirror: false,
        collision_geometry: CollisionGeometry {
            source_piece_id: PieceId::new(&id),
            source_bounds: IrregularBounds::new(0.0, 0.0, width, height),
            sampled_points: shape.points.clone(),
            convex_hull: shape.clone(),
            collision_polygon: shape,
            placement_reference: IrregularPoint::new(0.0, 0.0),
            diagnostics: vec![],
        },
        transforms,
        priority_order_key: None,
    }
}

/// Reconstructs a prepared piece for one `materialVectors[].pieces[]` entry,
/// whose only load-bearing field is `materialPoints` (the convex hull --
/// material accounting never reads `collisionPolygon`/`transforms`).
fn decode_material_piece(value: &Value) -> IrregularPreparedPiece {
    let id = value["id"].as_str().expect("id present").to_string();
    let points: Vec<IrregularPoint> = value["materialPoints"]
        .as_array()
        .expect("materialPoints array present")
        .iter()
        .map(|point| IrregularPoint::new(decode_f64_bits(point, "x"), decode_f64_bits(point, "y")))
        .collect();
    let hull = IrregularPolygon::new(points);
    IrregularPreparedPiece {
        piece_id: Some(PieceId::new(&id)),
        interchangeability_key: None,
        source: imported_piece(&id),
        allow_mirror: false,
        collision_geometry: CollisionGeometry {
            source_piece_id: PieceId::new(&id),
            source_bounds: IrregularBounds::new(0.0, 0.0, 1.0, 1.0),
            sampled_points: hull.points.clone(),
            convex_hull: hull.clone(),
            collision_polygon: hull,
            placement_reference: IrregularPoint::new(0.0, 0.0),
            diagnostics: vec![],
        },
        transforms: vec![],
        priority_order_key: None,
    }
}

fn decode_sheet(value: &Value) -> SheetSpec {
    SheetSpec {
        width: decode_f64_bits(value, "width"),
        height: decode_f64_bits(value, "height"),
        label: value["label"].as_str().expect("label present").to_string(),
    }
}

fn geometry_settings() -> IrregularGeometrySettings {
    IrregularGeometrySettings {
        flattening_sag_tolerance_mm: 0.25,
        clearance_safety_margin_mm: 0.25,
        geometry_backend_id: "irregular-convex-v2-default".to_string(),
        geometry_backend_version: "0".to_string(),
    }
}

// ---------------------------------------------------------------------------
// Preflight vectors.
// ---------------------------------------------------------------------------

fn assert_measurements_match(
    actual: &IntrinsicCapacityPreflightMeasurements,
    expected: &Value,
    label: &str,
) {
    assert_f64_bits_eq(
        actual.piece_count,
        decode_f64_bits(expected, "pieceCount"),
        &format!("{label} pieceCount"),
    );
    assert_f64_bits_eq(
        actual.sheet_width_grid,
        decode_f64_bits(expected, "sheetWidthGrid"),
        &format!("{label} sheetWidthGrid"),
    );
    assert_f64_bits_eq(
        actual.sheet_height_grid,
        decode_f64_bits(expected, "sheetHeightGrid"),
        &format!("{label} sheetHeightGrid"),
    );
    assert_eq!(
        actual.sheet_doubled_area_grid2,
        decode_bigint(expected, "sheetDoubledAreaGrid2"),
        "{label} sheetDoubledAreaGrid2"
    );
    assert_eq!(
        actual.minimum_doubled_collision_area_sum_grid2,
        decode_bigint(expected, "minimumDoubledCollisionAreaSumGrid2"),
        "{label} minimumDoubledCollisionAreaSumGrid2"
    );
    assert_eq!(
        actual.minimum_collision_area_pressure_ppm,
        decode_bigint(expected, "minimumCollisionAreaPressurePpm"),
        "{label} minimumCollisionAreaPressurePpm"
    );
    assert_eq!(
        actual.maximum_singleton_span_pressure_ppm,
        decode_bigint(expected, "maximumSingletonSpanPressurePpm"),
        "{label} maximumSingletonSpanPressurePpm"
    );
    let expected_ids: Vec<PieceId> = expected["singletonInfeasiblePieceIds"]
        .as_array()
        .expect("singletonInfeasiblePieceIds array present")
        .iter()
        .map(|id| PieceId::new(id.as_str().expect("piece id string")))
        .collect();
    assert_eq!(
        actual.singleton_infeasible_piece_ids, expected_ids,
        "{label} singletonInfeasiblePieceIds"
    );
}

#[test]
fn preflight_vectors_match() {
    let vectors = load_vectors();
    let cases = vectors["preflightVectors"]
        .as_array()
        .expect("preflightVectors array");
    assert!(!cases.is_empty(), "expected at least one preflight vector");

    for case in cases {
        let description = case["description"].as_str().unwrap_or("<no description>");
        let sheet = decode_sheet(&case["sheet"]);
        let pieces: Vec<IrregularPreparedPiece> = case["pieces"]
            .as_array()
            .expect("pieces array present")
            .iter()
            .map(decode_preflight_piece)
            .collect();
        let settings = geometry_settings();
        let mut cache = GeometryCacheStore::new();
        let outcome =
            preflight_intrinsic_complete_capacity(&sheet, &pieces, &settings, &mut cache, None)
                .unwrap_or_else(|err| panic!("{description}: preflight failed: {err:?}"));

        let expected = &case["outcome"];
        let expected_kind = expected["kind"].as_str().expect("outcome.kind present");
        match (&outcome, expected_kind) {
            (
                IntrinsicCapacityPreflightOutcome::ProvenImpossible {
                    reason,
                    measurements,
                },
                "proven_impossible",
            ) => {
                let expected_reason = expected["reason"].as_str().expect("outcome.reason present");
                match (reason, expected_reason) {
                    (
                        IntrinsicCapacityProvenImpossibleReason::SingletonTransformSetDoesNotFit {
                            piece_id,
                        },
                        "singleton-transform-set-does-not-fit",
                    ) => {
                        let expected_piece_id = decode_piece_id(expected, "pieceId");
                        assert_eq!(
                            *piece_id, expected_piece_id,
                            "{description}: proven_impossible pieceId"
                        );
                    }
                    (
                        IntrinsicCapacityProvenImpossibleReason::MinimumCollisionAreaExceedsSheetArea,
                        "minimum-collision-area-exceeds-sheet-area",
                    ) => {}
                    (actual_reason, expected_reason) => panic!(
                        "{description}: proven_impossible reason mismatch (rust={actual_reason:?} ts={expected_reason})"
                    ),
                }
                assert_measurements_match(measurements, &expected["measurements"], description);
            }
            (IntrinsicCapacityPreflightOutcome::Inconclusive { measurements }, "inconclusive") => {
                assert_measurements_match(measurements, &expected["measurements"], description);
            }
            (actual, expected_kind) => {
                panic!("{description}: outcome kind mismatch (rust={actual:?} ts={expected_kind})")
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Material vectors.
// ---------------------------------------------------------------------------

#[test]
fn material_vectors_match() {
    let vectors = load_vectors();
    let cases = vectors["materialVectors"]
        .as_array()
        .expect("materialVectors array");
    assert!(!cases.is_empty(), "expected at least one material vector");

    for case in cases {
        let description = case["description"].as_str().unwrap_or("<no description>");
        let pieces: Vec<IrregularPreparedPiece> = case["pieces"]
            .as_array()
            .expect("pieces array present")
            .iter()
            .map(decode_material_piece)
            .collect();
        let result = intrinsic_capacity_material_areas(&pieces);

        let expected = &case["result"];
        let expected_kind = expected["kind"].as_str().expect("result.kind present");
        match (&result, expected_kind) {
            (IntrinsicCapacityMaterialAreas::Complete { areas_by_piece_id }, "complete") => {
                let expected_entries = expected["areas"].as_array().expect("areas array present");
                assert_eq!(
                    areas_by_piece_id.len(),
                    expected_entries.len(),
                    "{description}: areas map size mismatch"
                );
                for entry in expected_entries {
                    let pair = entry.as_array().expect("[id, area] pair");
                    let id = PieceId::new(pair[0].as_str().expect("piece id string"));
                    let expected_area = pair[1]
                        .as_str()
                        .expect("area decimal string")
                        .parse::<BigInt>()
                        .expect("valid bigint");
                    let actual_area = areas_by_piece_id
                        .get(&id)
                        .unwrap_or_else(|| panic!("{description}: missing area for {id:?}"));
                    assert_eq!(
                        *actual_area, expected_area,
                        "{description}: area for {id:?}"
                    );
                }
            }
            (IntrinsicCapacityMaterialAreas::Invalid { piece_id }, "invalid") => {
                let expected_piece_id = decode_piece_id(expected, "pieceId");
                assert_eq!(
                    *piece_id, expected_piece_id,
                    "{description}: invalid pieceId"
                );
            }
            (actual, expected_kind) => {
                panic!("{description}: result kind mismatch (rust={actual:?} ts={expected_kind})")
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Endpoint construction vectors.
// ---------------------------------------------------------------------------

fn decode_origin(text: &str) -> IntrinsicCapacityEndpointOrigin {
    match text {
        "cold-search" => IntrinsicCapacityEndpointOrigin::ColdSearch,
        "prefix-incumbent" => IntrinsicCapacityEndpointOrigin::PrefixIncumbent,
        "warm-prefix-continuation" => IntrinsicCapacityEndpointOrigin::WarmPrefixContinuation,
        other => panic!("unknown origin {other:?}"),
    }
}

fn decode_placed_piece(value: &Value) -> Arc<IrregularPlacedPiece> {
    let id = PieceId::new(value["id"].as_str().expect("placed.id present"));
    let x = decode_f64_bits(value, "x");
    let y = decode_f64_bits(value, "y");
    let width = decode_f64_bits(value, "width");
    let height = decode_f64_bits(value, "height");
    let polygon = IrregularPolygon::new(rectangle_points(width, height));
    Arc::new(IrregularPlacedPiece {
        placement: IrregularPlacement {
            piece_id: Some(id.clone()),
            source_piece_id: id.clone(),
            placement_reference: None,
            transform: IrregularTransform {
                translate_x: x,
                translate_y: y,
                rotation_deg: 0.0,
                mirrored: false,
            },
        },
        collision_geometry: TransformedCollisionGeometry {
            source_piece_id: id,
            transform: IrregularTransformCandidate {
                index: 0.0,
                rotation_deg: 0.0,
                mirrored: false,
                reason: IrregularTransformReason::Configured,
            },
            polygon: polygon.clone(),
            bounds: IrregularBounds::new(0.0, 0.0, width, height),
        },
    })
}

fn assert_endpoint_matches(
    actual: Option<&IntrinsicCapacityEndpoint>,
    expected: &Value,
    label: &str,
) {
    let expected_kind = expected["kind"].as_str().expect("result.kind present");
    match (actual, expected_kind) {
        (None, "undefined") => {}
        (Some(_), "undefined") => panic!("{label}: expected undefined, rust endpoint materialized"),
        (None, "endpoint") => panic!("{label}: expected an endpoint, rust returned undefined"),
        (Some(endpoint), "endpoint") => {
            let expected_origin = expected["origin"].as_str().expect("origin present");
            assert_eq!(
                format!("{:?}", endpoint.origin),
                format!("{:?}", decode_origin(expected_origin)),
                "{label}: origin"
            );
            assert_eq!(
                endpoint.source_role,
                decode_string_or_null(expected, "sourceRole"),
                "{label}: sourceRole"
            );
            assert_optional_f64_bits_eq(
                endpoint.prefix_depth,
                decode_optional_f64_bits(&expected["prefixDepth"]),
                &format!("{label}: prefixDepth"),
            );
            let expected_placed: Vec<PieceId> = expected["placedPreparedIds"]
                .as_array()
                .expect("placedPreparedIds array")
                .iter()
                .map(|id| PieceId::new(id.as_str().expect("piece id string")))
                .collect();
            assert_eq!(
                endpoint.placed_prepared_ids, expected_placed,
                "{label}: placedPreparedIds"
            );
            let expected_unplaced: Vec<PieceId> = expected["unplacedPreparedIds"]
                .as_array()
                .expect("unplacedPreparedIds array")
                .iter()
                .map(|id| PieceId::new(id.as_str().expect("piece id string")))
                .collect();
            assert_eq!(
                endpoint.unplaced_prepared_ids, expected_unplaced,
                "{label}: unplacedPreparedIds"
            );
            assert_f64_bits_eq(
                endpoint.selected_rotation_deg,
                decode_f64_bits(expected, "selectedRotationDeg"),
                &format!("{label}: selectedRotationDeg"),
            );
            assert_eq!(
                endpoint.canonical_geometry_identity,
                expected["canonicalGeometryIdentity"]
                    .as_str()
                    .expect("canonicalGeometryIdentity present"),
                "{label}: canonicalGeometryIdentity"
            );
            assert_eq!(
                endpoint.canonical_geometry_hash,
                expected["canonicalGeometryHash"]
                    .as_str()
                    .expect("canonicalGeometryHash present"),
                "{label}: canonicalGeometryHash"
            );

            let metrics = &expected["metrics"];
            assert_f64_bits_eq(
                endpoint.metrics.placed_count,
                decode_f64_bits(metrics, "placedCount"),
                &format!("{label}: metrics.placedCount"),
            );
            assert_eq!(
                endpoint.metrics.placed_doubled_material_area_grid2,
                decode_bigint(metrics, "placedDoubledMaterialAreaGrid2"),
                "{label}: metrics.placedDoubledMaterialAreaGrid2"
            );
            assert_f64_bits_eq(
                endpoint.metrics.placed_material_area_mm2,
                decode_f64_bits(metrics, "placedMaterialAreaMm2"),
                &format!("{label}: metrics.placedMaterialAreaMm2"),
            );
            assert_f64_bits_eq(
                endpoint.metrics.enclosed_cavity_count,
                decode_f64_bits(metrics, "enclosedCavityCount"),
                &format!("{label}: metrics.enclosedCavityCount"),
            );
            assert_f64_bits_eq(
                endpoint.metrics.total_enclosed_cavity_area_mm2,
                decode_f64_bits(metrics, "totalEnclosedCavityAreaMm2"),
                &format!("{label}: metrics.totalEnclosedCavityAreaMm2"),
            );
            assert_eq!(
                endpoint.metrics.total_enclosed_cavity_doubled_area_grid2,
                metrics["totalEnclosedCavityDoubledAreaGrid2"]
                    .as_str()
                    .expect("totalEnclosedCavityDoubledAreaGrid2 present"),
                "{label}: metrics.totalEnclosedCavityDoubledAreaGrid2"
            );
            assert_f64_bits_eq(
                endpoint.metrics.envelope_maximum_side_mm,
                decode_f64_bits(metrics, "envelopeMaximumSideMm"),
                &format!("{label}: metrics.envelopeMaximumSideMm"),
            );
            assert_f64_bits_eq(
                endpoint.metrics.envelope_area_mm2,
                decode_f64_bits(metrics, "envelopeAreaMm2"),
                &format!("{label}: metrics.envelopeAreaMm2"),
            );
            assert_f64_bits_eq(
                endpoint.metrics.envelope_span_mm,
                decode_f64_bits(metrics, "envelopeSpanMm"),
                &format!("{label}: metrics.envelopeSpanMm"),
            );
            assert_f64_bits_eq(
                endpoint.metrics.envelope_maximum_side_grid,
                decode_f64_bits(metrics, "envelopeMaximumSideGrid"),
                &format!("{label}: metrics.envelopeMaximumSideGrid"),
            );
            assert_eq!(
                endpoint.metrics.envelope_area_grid2,
                metrics["envelopeAreaGrid2"]
                    .as_str()
                    .expect("envelopeAreaGrid2 present"),
                "{label}: metrics.envelopeAreaGrid2"
            );
            assert_f64_bits_eq(
                endpoint.metrics.envelope_span_grid,
                decode_f64_bits(metrics, "envelopeSpanGrid"),
                &format!("{label}: metrics.envelopeSpanGrid"),
            );
        }
        (actual, expected_kind) => panic!(
            "{label}: unexpected combination (rust_some={} ts_kind={expected_kind})",
            actual.is_some()
        ),
    }
}

#[test]
fn endpoint_vectors_match() {
    let vectors = load_vectors();
    let cases = vectors["endpointVectors"]
        .as_array()
        .expect("endpointVectors array");
    assert!(!cases.is_empty(), "expected at least one endpoint vector");

    for case in cases {
        let description = case["description"].as_str().unwrap_or("<no description>");
        let sheet = decode_sheet(&case["sheet"]);
        let placed: Vec<Arc<IrregularPlacedPiece>> = case["placed"]
            .as_array()
            .expect("placed array present")
            .iter()
            .map(decode_placed_piece)
            .collect();
        let placement_order: Vec<PieceId> = placed
            .iter()
            .map(|piece| piece.placement.source_piece_id.clone())
            .collect();
        let unplaced_prepared_ids: Vec<PieceId> = case["unplacedPreparedIds"]
            .as_array()
            .expect("unplacedPreparedIds array present")
            .iter()
            .map(|id| PieceId::new(id.as_str().expect("piece id string")))
            .collect();
        let origin = decode_origin(case["origin"].as_str().expect("origin present"));
        let source_role = decode_string_or_null(case, "sourceRole");
        let prefix_depth = decode_optional_f64_bits(&case["prefixDepth"]);
        let mut materials: HashMap<PieceId, BigInt> = HashMap::new();
        for entry in case["materials"]
            .as_array()
            .expect("materials array present")
        {
            let pair = entry.as_array().expect("[id, area] pair");
            let id = PieceId::new(pair[0].as_str().expect("material id string"));
            let area = pair[1]
                .as_str()
                .expect("material area decimal string")
                .parse::<BigInt>()
                .expect("valid bigint");
            materials.insert(id, area);
        }

        let state = IrregularBeamState::from_input(IrregularBeamStateInput {
            remaining_prepared_pieces: vec![],
            placed_collision_geometries: placed,
            unplaced_piece_ids: None,
            unplaced_source_piece_ids: None,
            placement_order,
            parent: None,
            placed_collision_index: None,
        });
        let mut cavity_cache: IntrinsicCapacityCavityCache = IntrinsicCapacityCavityCache::new();
        let endpoint =
            materialize_intrinsic_capacity_endpoint(MaterializeIntrinsicCapacityEndpointInput {
                sheet: &sheet,
                state,
                unplaced_prepared_ids,
                origin,
                source_role,
                prefix_depth,
                material_areas_by_piece_id: &materials,
                cavity_cache: &mut cavity_cache,
            });

        assert_endpoint_matches(endpoint.as_ref(), &case["result"], description);
    }
}

// ---------------------------------------------------------------------------
// Comparator vectors (synthetic-objective sweep and real-endpoint-derived
// objective pairs share the exact same encoded shape, so one decoder/runner
// covers both `comparatorVectors` and `endpointComparatorVectors`).
// ---------------------------------------------------------------------------

fn decode_objective(value: &Value) -> IntrinsicCapacityObjective {
    IntrinsicCapacityObjective {
        placed_count: decode_f64_bits(value, "placedCount"),
        placed_doubled_material_area_grid2: decode_bigint(value, "placedDoubledMaterialAreaGrid2"),
        enclosed_cavity_count: decode_f64_bits(value, "enclosedCavityCount"),
        total_enclosed_cavity_area_mm2: decode_f64_bits(value, "totalEnclosedCavityAreaMm2"),
        total_enclosed_cavity_doubled_area_grid2: value["totalEnclosedCavityDoubledAreaGrid2"]
            .as_str()
            .expect("totalEnclosedCavityDoubledAreaGrid2 present")
            .to_string(),
        envelope_maximum_side_mm: decode_f64_bits(value, "envelopeMaximumSideMm"),
        envelope_area_mm2: decode_f64_bits(value, "envelopeAreaMm2"),
        envelope_span_mm: decode_f64_bits(value, "envelopeSpanMm"),
        envelope_maximum_side_grid: decode_f64_bits(value, "envelopeMaximumSideGrid"),
        envelope_area_grid2: value["envelopeAreaGrid2"]
            .as_str()
            .expect("envelopeAreaGrid2 present")
            .to_string(),
        envelope_span_grid: decode_f64_bits(value, "envelopeSpanGrid"),
        canonical_geometry_hash: value["canonicalGeometryHash"]
            .as_str()
            .expect("canonicalGeometryHash present")
            .to_string(),
        origin: decode_origin(value["origin"].as_str().expect("origin present")),
        prefix_depth: decode_optional_f64_bits(&value["prefixDepth"]),
        source_role: decode_string_or_null(value, "sourceRole"),
    }
}

fn run_comparator_section(section: &str) {
    let vectors = load_vectors();
    let cases = vectors[section]
        .as_array()
        .unwrap_or_else(|| panic!("{section} array present"));
    assert!(!cases.is_empty(), "expected at least one {section} vector");

    for case in cases {
        let description = case["description"].as_str().unwrap_or("<no description>");
        let first = decode_objective(&case["first"]);
        let second = decode_objective(&case["second"]);
        let ordering = compare_intrinsic_capacity_objectives(&first, &second);
        let sign: i64 = match ordering {
            std::cmp::Ordering::Less => -1,
            std::cmp::Ordering::Equal => 0,
            std::cmp::Ordering::Greater => 1,
        };
        let expected_sign = case["sign"].as_i64().expect("sign present");
        assert_eq!(
            sign, expected_sign,
            "{section}: {description}: comparator sign mismatch"
        );
    }
}

#[test]
fn comparator_vectors_match() {
    run_comparator_section("comparatorVectors");
}

#[test]
fn endpoint_comparator_vectors_match() {
    run_comparator_section("endpointComparatorVectors");
}
