//! Differential-vector test for `geometry::convex`.
//!
//! Loads `tests/vectors/convex.json`, generated by
//! `scripts/rust-parity/dump-convex.ts` from the REAL production TypeScript
//! functions (`ConvexHull.compute`, `boundsForPoints`,
//! `translatePolygonWithBounds`, `areDisjoint`,
//! `ConvexPolygonValidation.validateStrictBoundary`), and asserts this
//! crate's `geometry::convex` module reproduces every recorded output
//! exactly: bit-exact `f64` (compared via `to_bits()`, so `-0.0`/`+0.0` and
//! any two differently payloaded `NaN`s are distinguished exactly as the
//! oracle recorded them), exact strings, and exact `-1`/`1` winding/booleans.

use std::fs;

use irregular_nesting_native::domain::{IrregularBounds, IrregularPoint, IrregularPolygon};
use irregular_nesting_native::geometry::convex::{
    are_disjoint, bounds_for_points, compute_convex_hull, translate_polygon_with_bounds,
    validate_strict_boundary, StrictConvexBoundaryValidation,
};
use serde::Deserialize;

fn load_vectors() -> VectorFile {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/vectors/convex.json");
    let raw = fs::read_to_string(path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&raw).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

// ---------------------------------------------------------------------------
// Vector file shape, mirroring `scripts/rust-parity/dump-convex.ts`'s output
// exactly.
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
struct VectorFile {
    #[serde(rename = "generatingCommit")]
    generating_commit: String,
    #[serde(rename = "totalCaseCount")]
    total_case_count: usize,
    hull: Section<HullCase>,
    bounds: Section<BoundsCase>,
    translate: Section<TranslateCase>,
    disjoint: Section<DisjointCase>,
    validation: Section<ValidationCase>,
}

#[derive(Deserialize)]
struct Section<T> {
    #[serde(rename = "caseCount")]
    case_count: usize,
    cases: Vec<T>,
}

#[derive(Deserialize)]
struct EncodedPoint {
    x: String,
    y: String,
}

#[derive(Deserialize)]
struct EncodedBounds {
    #[serde(rename = "minX")]
    min_x: String,
    #[serde(rename = "minY")]
    min_y: String,
    #[serde(rename = "maxX")]
    max_x: String,
    #[serde(rename = "maxY")]
    max_y: String,
}

#[derive(Deserialize)]
struct HullCase {
    category: String,
    input: Vec<EncodedPoint>,
    hull: Vec<EncodedPoint>,
}

#[derive(Deserialize)]
struct BoundsCase {
    category: String,
    input: Vec<EncodedPoint>,
    bounds: Option<EncodedBounds>,
}

#[derive(Deserialize)]
struct TranslateResult {
    polygon: Vec<EncodedPoint>,
    bounds: EncodedBounds,
}

#[derive(Deserialize)]
struct TranslateCase {
    category: String,
    polygon: Vec<EncodedPoint>,
    translation: EncodedPoint,
    result: Option<TranslateResult>,
}

#[derive(Deserialize)]
struct DisjointCase {
    category: String,
    first: EncodedBounds,
    second: EncodedBounds,
    disjoint: bool,
}

#[derive(Deserialize)]
#[serde(untagged)]
enum EncodedValidationResult {
    Valid { winding: i32 },
    Invalid { message: String },
}

#[derive(Deserialize)]
struct ValidationCase {
    category: String,
    points: Vec<EncodedPoint>,
    result: EncodedValidationResult,
}

// ---------------------------------------------------------------------------
// Decoders mirroring `scripts/rust-parity/dump-convex.ts`'s encoders. f64
// values are big-endian IEEE-754 bit-pattern hex strings (e.g.
// `"0x4066c00000000000"`), matching `dump-predicates.ts`'s `f64Bits`
// convention.
// ---------------------------------------------------------------------------

fn parse_f64_bits(hex: &str) -> f64 {
    let stripped = hex
        .strip_prefix("0x")
        .unwrap_or_else(|| panic!("bit-pattern hex must start with 0x, got {hex}"));
    let bits = u64::from_str_radix(stripped, 16)
        .unwrap_or_else(|err| panic!("invalid bit-pattern hex {hex}: {err}"));
    f64::from_bits(bits)
}

fn decode_point(point: &EncodedPoint) -> IrregularPoint {
    IrregularPoint::new(parse_f64_bits(&point.x), parse_f64_bits(&point.y))
}

fn decode_points(points: &[EncodedPoint]) -> Vec<IrregularPoint> {
    points.iter().map(decode_point).collect()
}

fn decode_bounds(bounds: &EncodedBounds) -> IrregularBounds {
    IrregularBounds::new(
        parse_f64_bits(&bounds.min_x),
        parse_f64_bits(&bounds.min_y),
        parse_f64_bits(&bounds.max_x),
        parse_f64_bits(&bounds.max_y),
    )
}

// ---------------------------------------------------------------------------
// Bit-exact comparison helpers.
// ---------------------------------------------------------------------------

fn assert_f64_bits_eq(actual: f64, expected: f64, context: &str) {
    assert_eq!(
        actual.to_bits(),
        expected.to_bits(),
        "{context}: expected {expected:?} (bits {:x}), got {actual:?} (bits {:x})",
        expected.to_bits(),
        actual.to_bits()
    );
}

fn assert_points_eq(actual: &[IrregularPoint], expected: &[IrregularPoint], context: &str) {
    assert_eq!(
        actual.len(),
        expected.len(),
        "{context}: point count mismatch (expected {}, got {})",
        expected.len(),
        actual.len()
    );
    for (index, (actual_point, expected_point)) in actual.iter().zip(expected.iter()).enumerate() {
        assert_f64_bits_eq(
            actual_point.x,
            expected_point.x,
            &format!("{context}[{index}].x"),
        );
        assert_f64_bits_eq(
            actual_point.y,
            expected_point.y,
            &format!("{context}[{index}].y"),
        );
    }
}

fn assert_bounds_eq(actual: &IrregularBounds, expected: &IrregularBounds, context: &str) {
    assert_f64_bits_eq(actual.min_x, expected.min_x, &format!("{context}.minX"));
    assert_f64_bits_eq(actual.min_y, expected.min_y, &format!("{context}.minY"));
    assert_f64_bits_eq(actual.max_x, expected.max_x, &format!("{context}.maxX"));
    assert_f64_bits_eq(actual.max_y, expected.max_y, &format!("{context}.maxY"));
}

// ---------------------------------------------------------------------------
// Header sanity.
// ---------------------------------------------------------------------------

#[test]
fn vector_file_header_records_generating_commit_and_meaningful_coverage() {
    let vectors = load_vectors();
    assert_eq!(
        vectors.generating_commit.len(),
        40,
        "expected a full git SHA-1 hex commit hash"
    );
    assert!(
        vectors
            .generating_commit
            .chars()
            .all(|c| c.is_ascii_hexdigit()),
        "generating commit must be hex"
    );
    assert!(
        vectors.total_case_count >= 500,
        "expected at least 500 total convex vectors, got {}",
        vectors.total_case_count
    );
    assert_eq!(
        vectors.total_case_count,
        vectors.hull.case_count
            + vectors.bounds.case_count
            + vectors.translate.case_count
            + vectors.disjoint.case_count
            + vectors.validation.case_count,
        "totalCaseCount must equal the sum of every section's caseCount"
    );
    assert_eq!(vectors.hull.case_count, vectors.hull.cases.len());
    assert_eq!(vectors.bounds.case_count, vectors.bounds.cases.len());
    assert_eq!(vectors.translate.case_count, vectors.translate.cases.len());
    assert_eq!(vectors.disjoint.case_count, vectors.disjoint.cases.len());
    assert_eq!(
        vectors.validation.case_count,
        vectors.validation.cases.len()
    );

    // A representative fixture-derived category must actually be present, so
    // this file's "all 61 fixture rings" requirement is verifiably met, not
    // merely asserted in prose.
    let fixture_hull_cases = vectors
        .hull
        .cases
        .iter()
        .filter(|case| case.category.starts_with("fixture-piece:"))
        .count();
    assert_eq!(
        fixture_hull_cases, 61,
        "expected exactly 61 fixture-piece hull vectors (one per mixed61 source piece)"
    );
}

// ---------------------------------------------------------------------------
// compute_convex_hull
// ---------------------------------------------------------------------------

#[test]
fn compute_convex_hull_matches_oracle_for_every_vector() {
    let vectors = load_vectors();
    assert!(!vectors.hull.cases.is_empty());
    for case in &vectors.hull.cases {
        let input = decode_points(&case.input);
        let expected_hull = decode_points(&case.hull);
        let actual_hull = compute_convex_hull(&input);
        assert_points_eq(
            &actual_hull.points,
            &expected_hull,
            &format!("hull[{}]", case.category),
        );
    }
}

// ---------------------------------------------------------------------------
// bounds_for_points
// ---------------------------------------------------------------------------

#[test]
fn bounds_for_points_matches_oracle_for_every_vector() {
    let vectors = load_vectors();
    assert!(!vectors.bounds.cases.is_empty());
    for case in &vectors.bounds.cases {
        let input = decode_points(&case.input);
        let expected = case.bounds.as_ref().map(decode_bounds);
        let actual = bounds_for_points(&input);
        match (actual, expected) {
            (None, None) => {}
            (Some(actual_bounds), Some(expected_bounds)) => {
                assert_bounds_eq(
                    &actual_bounds,
                    &expected_bounds,
                    &format!("bounds[{}]", case.category),
                );
            }
            (actual, expected) => panic!(
                "bounds[{}]: presence mismatch (expected {:?}, got {:?})",
                case.category,
                expected.is_some(),
                actual.is_some()
            ),
        }
    }
}

// ---------------------------------------------------------------------------
// translate_polygon_with_bounds
// ---------------------------------------------------------------------------

#[test]
fn translate_polygon_with_bounds_matches_oracle_for_every_vector() {
    let vectors = load_vectors();
    assert!(!vectors.translate.cases.is_empty());
    for case in &vectors.translate.cases {
        let polygon = IrregularPolygon::new(decode_points(&case.polygon));
        let translation = decode_point(&case.translation);
        let actual = translate_polygon_with_bounds(&polygon, translation);
        match (actual, &case.result) {
            (None, None) => {}
            (Some(actual_result), Some(expected_result)) => {
                let expected_points = decode_points(&expected_result.polygon);
                assert_points_eq(
                    &actual_result.polygon.points,
                    &expected_points,
                    &format!("translate[{}].polygon", case.category),
                );
                assert_bounds_eq(
                    &actual_result.bounds,
                    &decode_bounds(&expected_result.bounds),
                    &format!("translate[{}].bounds", case.category),
                );
            }
            (actual, expected) => panic!(
                "translate[{}]: presence mismatch (expected {:?}, got {:?})",
                case.category,
                expected.is_some(),
                actual.is_some()
            ),
        }
    }
}

// ---------------------------------------------------------------------------
// are_disjoint
// ---------------------------------------------------------------------------

#[test]
fn are_disjoint_matches_oracle_for_every_vector() {
    let vectors = load_vectors();
    assert!(!vectors.disjoint.cases.is_empty());
    for case in &vectors.disjoint.cases {
        let first = decode_bounds(&case.first);
        let second = decode_bounds(&case.second);
        let actual = are_disjoint(&first, &second);
        assert_eq!(
            actual, case.disjoint,
            "disjoint[{}]: expected {}, got {}",
            case.category, case.disjoint, actual
        );
    }
}

// ---------------------------------------------------------------------------
// validate_strict_boundary
// ---------------------------------------------------------------------------

#[test]
fn validate_strict_boundary_matches_oracle_for_every_vector() {
    let vectors = load_vectors();
    assert!(!vectors.validation.cases.is_empty());
    for case in &vectors.validation.cases {
        let points = decode_points(&case.points);
        let actual = validate_strict_boundary(&points);
        match (&actual, &case.result) {
            (
                StrictConvexBoundaryValidation::Valid { winding },
                EncodedValidationResult::Valid {
                    winding: expected_winding,
                },
            ) => {
                assert_eq!(
                    winding, expected_winding,
                    "validation[{}]: winding mismatch",
                    case.category
                );
            }
            (
                StrictConvexBoundaryValidation::Invalid { message },
                EncodedValidationResult::Invalid {
                    message: expected_message,
                },
            ) => {
                assert_eq!(
                    message, expected_message,
                    "validation[{}]: message mismatch",
                    case.category
                );
            }
            (actual, expected) => panic!(
                "validation[{}]: discriminant mismatch (expected {}, got {})",
                case.category,
                match expected {
                    EncodedValidationResult::Valid { .. } => "Valid",
                    EncodedValidationResult::Invalid { .. } => "Invalid",
                },
                match actual {
                    StrictConvexBoundaryValidation::Valid { .. } => "Valid",
                    StrictConvexBoundaryValidation::Invalid { .. } => "Invalid",
                }
            ),
        }
    }
}
