//! Coordinator integration coverage for
//! `crates/irregular-nesting-native/src/result/{mod,coordinator,materialize,progress}.rs`
//! (the port of `src/workers/algorithm/irregular/computeIrregularNesting.ts`)
//! plus the `capacity::mode` orchestration it now wires directly
//! (`run_intrinsic_capacity_mode`/`run_intrinsic_capacity_scheduler_cold_quantum`,
//! ported from `intrinsicCapacityMode.ts`).
//!
//! The first four tests below (`archive_ineligible_settings_return_a_typed_routing_error`
//! through `history_mode_off_suppresses_state_snapshots_but_not_progress`) are
//! the original hand-built structural/behavioral integration tests written
//! before the full differential suite existed; they exercise coordinator
//! wiring the vector suite below does not specifically target (progress
//! event emission order, snapshot suppression under `historyMode: 'off'`)
//! and are kept unchanged.
//!
//! `full_job_vectors_match_ts_oracle` is the real cross-language
//! differential suite the task brief asks for: it loads
//! `tests/vectors/coordinator.json` (generated by
//! `scripts/rust-parity/dump-coordinator.ts` from the REAL, Effect-layered
//! production `computeIrregularNesting` -- see that script's own top doc for
//! the exact layer stack, matching `nesting.worker.ts`'s
//! `computeIrregularWorkerResult` precisely), reconstructs each case's
//! `NestingRequest`/`IrregularNestingSettings` in Rust, calls
//! `result::coordinator::compute_irregular_nesting`, and asserts the real
//! Rust result's own semantic projection (placements bit-exact, score,
//! placed/unplaced partitions, canonical hashes, snapshot sequences,
//! portfolio/capacity/scheduler traces, statuses) exactly reproduces the
//! recorded TS oracle output. Every `performance.now()`-derived field
//! (`*RuntimeMs`, `*Ms`, `elapsedMs`) is excluded from both sides as
//! documented non-semantic timing data -- there is no `timingNow` seam in
//! `computeIrregularNesting.ts` itself (confirmed by direct source grep).

use std::fs;
use std::sync::Mutex;

use irregular_nesting_native::caches::GeometryCacheStore;
use irregular_nesting_native::domain::{
    default_irregular_placement_policy_ids, DxfGeometryEntityType, DxfGeometrySegment,
    DxfGeometrySummary, DxfLineSegment, ImportedPiece, IntrinsicObjectiveProfileId,
    IrregularGeometrySettings, IrregularNestingSettings, IrregularOptimizerSettings,
    IrregularPlacementPolicyId, PieceId, Rect, SheetSpec, SourceFileId,
};
use irregular_nesting_native::nfp_ifp::NfpIfpAbortReason;
use irregular_nesting_native::result::coordinator::{
    compute_irregular_nesting, ComputeIrregularNestingOptions,
};
use irregular_nesting_native::result::progress::IrregularComputeEventSink;
use irregular_nesting_native::result::{
    HistoryMode, IrregularComputeErrorType, IrregularComputeResult, IrregularPortfolioPhase,
    IrregularPortfolioProgress, IrregularSearchSource, IrregularStateSnapshot, NestingOptions,
    NestingRequest,
};
use irregular_nesting_native::search::layout_scorer::FreeMaterialCache;
use irregular_nesting_native::search::sort_pieces::{CutRowRef, PreparedPiece, RectWith};
use serde_json::Value;

// ===========================================================================
// Original hand-built structural/behavioral coverage (unchanged).
// ===========================================================================

fn line(x1: f64, y1: f64, x2: f64, y2: f64) -> DxfGeometrySegment {
    DxfGeometrySegment::Line(DxfLineSegment {
        x1,
        y1,
        x2,
        y2,
        bulge: None,
        source_curve: None,
    })
}

/// A closed axis-aligned square source piece, matching the established
/// fixture pattern `geometry::collision_builder`'s own tests use
/// (`rectangle_piece`).
fn square_source_piece(id: &str, x: f64, y: f64, side: f64) -> ImportedPiece {
    ImportedPiece {
        id: PieceId::new(id),
        source_file_id: SourceFileId::new("test-source"),
        source_layer: None,
        label: format!("square {id}"),
        real_bounds: Rect {
            x,
            y,
            width: side,
            height: side,
        },
        geometry: DxfGeometrySummary {
            entity_type: DxfGeometryEntityType::Lwpolyline,
            closed: true,
            segments: vec![
                line(x, y, x + side, y),
                line(x + side, y, x + side, y + side),
                line(x + side, y + side, x, y + side),
                line(x, y + side, x, y),
            ],
        },
        warnings: Vec::new(),
    }
}

fn square_prepared_piece(id: &str, side: f64) -> PreparedPiece {
    let rect = Rect {
        x: 0.0,
        y: 0.0,
        width: side,
        height: side,
    };
    PreparedPiece {
        id: PieceId::new(id),
        source_piece_id: PieceId::new(id),
        interchangeability_key: None,
        real_bounds: rect,
        padded_bounds: RectWith {
            rect,
            longest_edge: side,
            area: side * side,
            imbalance: 0.0,
        },
        padding: 0.0,
        allow_rotation: true,
        allow_mirror: true,
        cut_row_ref: None,
    }
}

/// A closed axis-aligned rectangle source piece (width `w`, height `h`),
/// used by the cancellation-during-nested-resume scenario below (a square
/// combo does not reliably force the nested resume to fire; a mixed
/// rectangle combo, calibrated against the real TS oracle, does).
fn rect_source_piece(id: &str, w: f64, h: f64) -> ImportedPiece {
    ImportedPiece {
        id: PieceId::new(id),
        source_file_id: SourceFileId::new("test-source"),
        source_layer: None,
        label: format!("rect {id}"),
        real_bounds: Rect {
            x: 0.0,
            y: 0.0,
            width: w,
            height: h,
        },
        geometry: DxfGeometrySummary {
            entity_type: DxfGeometryEntityType::Lwpolyline,
            closed: true,
            segments: vec![
                line(0.0, 0.0, w, 0.0),
                line(w, 0.0, w, h),
                line(w, h, 0.0, h),
                line(0.0, h, 0.0, 0.0),
            ],
        },
        warnings: Vec::new(),
    }
}

fn rect_prepared_piece(id: &str, w: f64, h: f64) -> PreparedPiece {
    let rect = Rect {
        x: 0.0,
        y: 0.0,
        width: w,
        height: h,
    };
    PreparedPiece {
        id: PieceId::new(id),
        source_piece_id: PieceId::new(id),
        interchangeability_key: None,
        real_bounds: rect,
        padded_bounds: RectWith {
            rect,
            longest_edge: w.max(h),
            area: w * h,
            imbalance: (w - h).abs(),
        },
        padding: 0.0,
        allow_rotation: true,
        allow_mirror: true,
        cut_row_ref: None,
    }
}

fn default_geometry_settings() -> IrregularGeometrySettings {
    IrregularGeometrySettings {
        flattening_sag_tolerance_mm: 0.25,
        clearance_safety_margin_mm: 0.25,
        geometry_backend_id: "test".to_string(),
        geometry_backend_version: "0".to_string(),
    }
}

/// A Compact-preset-shaped optimizer settings block: `intrinsicSharedArchiveEnabled:
/// true`, GA fully disabled via `baselineOnly: true` -- matching
/// `makeCompactQualityIrregularOptimizerSettings`'s production defaults
/// closely enough to exercise the archive-eligible path (see
/// `result::intrinsic_shared_archive_eligibility`).
fn compact_optimizer_settings() -> IrregularOptimizerSettings {
    IrregularOptimizerSettings {
        order_window: 8.0,
        beam_width: 8.0,
        local_candidate_fanout: 4.0,
        local_repair_budget: 0.0,
        intrinsic_shared_archive_enabled: true,
        intrinsic_objective_profile_id: IntrinsicObjectiveProfileId::Compact,
        transform_cap: 24.0,
        transform_minimum_edge_length_mm: 1.0,
        transform_angle_deduplication_tolerance_deg: 0.01,
        configured_rotation_enabled: true,
        edge_alignment_enabled: true,
        configured_rotation_deg: Vec::new(),
        ga_enabled: false,
        baseline_only: true,
        ga_population: 16.0,
        ga_generation_budget: 2.0,
        ga_evaluation_budget: 24.0,
        ga_time_budget_ms: 0.0,
        ga_seed: "seed".to_string(),
        priority_order_mutation_enabled: true,
        transform_preference_mutation_enabled: true,
        placement_policy_mutation_enabled: true,
        placement_policy_id: IrregularPlacementPolicyId::BalancedCompactness,
        placement_policy_ids: default_irregular_placement_policy_ids(),
    }
}

fn compact_settings() -> IrregularNestingSettings {
    IrregularNestingSettings {
        geometry: default_geometry_settings(),
        optimizer: compact_optimizer_settings(),
    }
}

fn roomy_sheet() -> SheetSpec {
    SheetSpec {
        width: 2000.0,
        height: 2000.0,
        label: "test-sheet".to_string(),
    }
}

fn default_options() -> NestingOptions {
    NestingOptions {
        allow_global_rotation: true,
        allow_global_mirror: Some(true),
        history_mode: HistoryMode::Stream,
        irregular_settings: None,
    }
}

/// Records every emitted event, in emission order, for assertion.
#[derive(Default)]
struct RecordingSink {
    phases: Mutex<Vec<IrregularPortfolioPhase>>,
    snapshot_count: Mutex<usize>,
}

impl IrregularComputeEventSink for RecordingSink {
    fn emit_state_snapshot(&mut self, _snapshot: &IrregularStateSnapshot, _beam_width: f64) {
        *self.snapshot_count.lock().unwrap() += 1;
    }

    fn emit_portfolio_progress(&mut self, progress: &IrregularPortfolioProgress) {
        self.phases.lock().unwrap().push(progress.phase);
    }
}

#[test]
fn archive_ineligible_settings_return_a_typed_routing_error() {
    let mut settings = compact_settings();
    settings.optimizer.intrinsic_shared_archive_enabled = false;

    let request = NestingRequest {
        sheet: roomy_sheet(),
        padding: 0.0,
        pieces: vec![square_prepared_piece("piece-1", 100.0)],
        source_pieces: vec![square_source_piece("piece-1", 0.0, 0.0, 100.0)],
        options: default_options(),
    };

    let mut options = ComputeIrregularNestingOptions::default();
    let mut geometry_cache = GeometryCacheStore::new();
    let mut free_material_cache = FreeMaterialCache::new();

    let result = compute_irregular_nesting(
        &request,
        &settings,
        &mut options,
        &mut geometry_cache,
        &mut free_material_cache,
    );

    match result {
        Err(IrregularComputeErrorType::Portfolio(error)) => {
            assert_eq!(error.operation, "computeIrregularNesting");
        }
        other => panic!("expected a Portfolio routing error, got {other:?}"),
    }
}

#[test]
fn missing_source_geometry_returns_the_typed_compute_error() {
    let settings = compact_settings();
    let request = NestingRequest {
        sheet: roomy_sheet(),
        padding: 0.0,
        pieces: vec![square_prepared_piece("piece-missing", 100.0)],
        // No matching source piece: `findSourcePiece` must fail closed.
        source_pieces: Vec::new(),
        options: default_options(),
    };

    let mut options = ComputeIrregularNestingOptions::default();
    let mut geometry_cache = GeometryCacheStore::new();
    let mut free_material_cache = FreeMaterialCache::new();

    let result = compute_irregular_nesting(
        &request,
        &settings,
        &mut options,
        &mut geometry_cache,
        &mut free_material_cache,
    );

    match result {
        Err(IrregularComputeErrorType::Compute(error)) => {
            assert_eq!(error.prepared_piece_id, PieceId::new("piece-missing"));
            assert_eq!(error.source_piece_id, PieceId::new("piece-missing"));
        }
        other => panic!("expected an IrregularComputeError, got {other:?}"),
    }
}

#[test]
fn two_small_squares_on_a_roomy_sheet_settle_through_the_shared_archive_winner_path() {
    let settings = compact_settings();
    let request = NestingRequest {
        sheet: roomy_sheet(),
        padding: 0.0,
        pieces: vec![
            square_prepared_piece("square-a", 50.0),
            square_prepared_piece("square-b", 40.0),
        ],
        source_pieces: vec![
            square_source_piece("square-a", 0.0, 0.0, 50.0),
            square_source_piece("square-b", 0.0, 0.0, 40.0),
        ],
        options: default_options(),
    };

    let mut sink = RecordingSink::default();
    let mut options = ComputeIrregularNestingOptions {
        event_sink: Some(&mut sink),
        cancellation_reason: None,
        focused_complete_reconstruction_enabled: true,
    };
    let mut geometry_cache = GeometryCacheStore::new();
    let mut free_material_cache = FreeMaterialCache::new();

    let result = compute_irregular_nesting(
        &request,
        &settings,
        &mut options,
        &mut geometry_cache,
        &mut free_material_cache,
    )
    .expect("two small squares on a 2000x2000 sheet must settle without needing capacity mode");

    // Both pieces are placed; the shared archive is the terminal source for
    // every Compact-eligible request that finds a fitting winner.
    assert_eq!(result.placed_collision_geometries.len(), 2);
    assert!(result.unplaced_piece_ids.is_empty());
    assert_eq!(
        result.portfolio.source,
        IrregularSearchSource::SharedArchive
    );
    assert!(result.capacity_trace.is_none());

    // TS: `emitSharedArchiveProgress(input, 'shared_archive', ...)` is
    // always the first progress event on the archive-eligible path
    // (`computeIrregularNesting.ts:506-511`), and `'completed'` is the
    // last event on the winner-found branch (`:1057-1062`) since Compact
    // (not Compact Short Side) never enters the Short Side profile block.
    let phases = sink.phases.into_inner().unwrap();
    assert_eq!(
        phases.first(),
        Some(&IrregularPortfolioPhase::SharedArchive)
    );
    assert_eq!(phases.last(), Some(&IrregularPortfolioPhase::Completed));

    // `historyMode: 'stream'` means state snapshots are emitted (TS:
    // `selectedLayoutRevealSnapshots`, one snapshot per placement-count
    // prefix, so `placed_collision_geometries.len() + 1` snapshots).
    assert_eq!(*sink.snapshot_count.lock().unwrap(), 3);
}

#[test]
fn history_mode_off_suppresses_state_snapshots_but_not_progress() {
    let settings = compact_settings();
    let mut request_options = default_options();
    request_options.history_mode = HistoryMode::Off;
    let request = NestingRequest {
        sheet: roomy_sheet(),
        padding: 0.0,
        pieces: vec![square_prepared_piece("only-square", 50.0)],
        source_pieces: vec![square_source_piece("only-square", 0.0, 0.0, 50.0)],
        options: request_options,
    };

    let mut sink = RecordingSink::default();
    let mut options = ComputeIrregularNestingOptions {
        event_sink: Some(&mut sink),
        cancellation_reason: None,
        focused_complete_reconstruction_enabled: true,
    };
    let mut geometry_cache = GeometryCacheStore::new();
    let mut free_material_cache = FreeMaterialCache::new();

    let result = compute_irregular_nesting(
        &request,
        &settings,
        &mut options,
        &mut geometry_cache,
        &mut free_material_cache,
    )
    .expect("a single small square on a roomy sheet must settle");

    assert!(result.state_snapshots.is_empty());
    assert_eq!(*sink.snapshot_count.lock().unwrap(), 0);
    assert!(!sink.phases.into_inner().unwrap().is_empty());
}

/// TS: `computeIrregularNesting.ts:1194-1201` -- when the Short Side profile
/// is requested but nothing ever settles into `selected.placedCollisionGeometries`
/// (here: preflight proves a single piece bigger than the sheet itself can
/// never fit, so capacity mode settles with zero placed pieces), the
/// directional-reference `production*` terms
/// (`intrinsicShortSideObserver.ts`'s `directionalReference`, ported as
/// `short_side::observer::directional_reference`) are all `None` for an
/// empty `placedCollisionGeometries` slice -- so the pair-fold construction
/// never runs at all and the coordinator must fail closed with the typed
/// `IrregularNoValidResultError { operation: "intrinsicShortSide" }`, never
/// silently falling back to an incomplete/degraded "success". This exact
/// no-production-geometry branch of the Short Side handoff is not otherwise
/// exercised by `full_job_vectors_match_ts_oracle` (every generated Short
/// Side case there settles with a nonempty, `'accepted'` pair fold).
#[test]
fn short_side_profile_with_zero_placed_pieces_fails_closed_with_no_valid_result() {
    let mut settings = compact_settings();
    settings.optimizer.intrinsic_objective_profile_id = IntrinsicObjectiveProfileId::ShortSide;

    let tiny_sheet = SheetSpec {
        width: 40.0,
        height: 40.0,
        label: "tiny-sheet".to_string(),
    };
    let request = NestingRequest {
        sheet: tiny_sheet,
        padding: 0.0,
        // A single piece far larger than the sheet in every dimension: no
        // prepared transform can ever fit it, so the preflight itself proves
        // impossibility (`singleton-transform-set-does-not-fit`) and capacity
        // mode settles with the piece unplaced -- zero placed pieces.
        pieces: vec![square_prepared_piece("too-big", 500.0)],
        source_pieces: vec![square_source_piece("too-big", 0.0, 0.0, 500.0)],
        options: default_options(),
    };

    let mut options = ComputeIrregularNestingOptions::default();
    let mut geometry_cache = GeometryCacheStore::new();
    let mut free_material_cache = FreeMaterialCache::new();

    let result = compute_irregular_nesting(
        &request,
        &settings,
        &mut options,
        &mut geometry_cache,
        &mut free_material_cache,
    );

    match result {
        Err(IrregularComputeErrorType::NoValidResult(error)) => {
            assert_eq!(error.operation, "intrinsicShortSide");
        }
        other => panic!("expected a typed NoValidResult error, got {other:?}"),
    }
}

// ===========================================================================
// Full-job TS-oracle differential suite.
// ===========================================================================

fn load_vectors() -> Value {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/vectors/coordinator.json"
    );
    let raw = fs::read_to_string(path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&raw).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

fn f64_bits(value: f64) -> Value {
    Value::String(format!("0x{:016x}", value.to_bits()))
}

fn opt_f64_bits(value: Option<f64>) -> Value {
    match value {
        Some(value) => f64_bits(value),
        None => Value::Null,
    }
}

fn encode_json_numbers_as_bits(value: Value) -> Value {
    match value {
        Value::Array(values) => Value::Array(
            values
                .into_iter()
                .map(encode_json_numbers_as_bits)
                .collect(),
        ),
        Value::Object(values) => Value::Object(
            values
                .into_iter()
                .map(|(key, value)| (key, encode_json_numbers_as_bits(value)))
                .collect(),
        ),
        Value::Number(value) => f64_bits(value.as_f64().expect("prepared-piece number is f64")),
        value => value,
    }
}

// ---------------------------------------------------------------------------
// Request decoding: reconstructs a real Rust `NestingRequest` +
// `IrregularNestingSettings` from one vector case's `request` object.
// ---------------------------------------------------------------------------
fn decode_imported_piece(value: &Value) -> ImportedPiece {
    serde_json::from_value(value.clone())
        .unwrap_or_else(|err| panic!("failed to decode ImportedPiece: {err}; value={value}"))
}

fn decode_prepared_piece(value: &Value) -> PreparedPiece {
    let padded = &value["paddedBounds"];
    let real = &value["realBounds"];
    PreparedPiece {
        id: PieceId::new(value["id"].as_str().expect("id")),
        source_piece_id: PieceId::new(value["sourcePieceId"].as_str().expect("sourcePieceId")),
        interchangeability_key: value["interchangeabilityKey"]
            .as_str()
            .map(|s| s.to_string()),
        real_bounds: Rect {
            x: real["x"].as_f64().expect("x"),
            y: real["y"].as_f64().expect("y"),
            width: real["width"].as_f64().expect("width"),
            height: real["height"].as_f64().expect("height"),
        },
        padded_bounds: RectWith {
            rect: Rect {
                x: padded["x"].as_f64().expect("x"),
                y: padded["y"].as_f64().expect("y"),
                width: padded["width"].as_f64().expect("width"),
                height: padded["height"].as_f64().expect("height"),
            },
            longest_edge: padded["longestEdge"].as_f64().expect("longestEdge"),
            area: padded["area"].as_f64().expect("area"),
            imbalance: padded["imbalance"].as_f64().expect("imbalance"),
        },
        padding: value["padding"].as_f64().expect("padding"),
        allow_rotation: value["allowRotation"].as_bool().expect("allowRotation"),
        allow_mirror: value["allowMirror"].as_bool().expect("allowMirror"),
        cut_row_ref: None::<CutRowRef>,
    }
}

fn decode_sheet(value: &Value) -> SheetSpec {
    serde_json::from_value(value.clone())
        .unwrap_or_else(|err| panic!("failed to decode SheetSpec: {err}; value={value}"))
}

fn decode_settings(value: &Value) -> IrregularNestingSettings {
    serde_json::from_value(value.clone()).unwrap_or_else(|err| {
        panic!("failed to decode IrregularNestingSettings: {err}; value={value}")
    })
}

fn decode_request(case: &Value) -> (NestingRequest, IrregularNestingSettings) {
    let request_value = &case["request"];
    let settings = decode_settings(&request_value["settings"]);
    let sheet = decode_sheet(&request_value["sheet"]);
    let pieces: Vec<PreparedPiece> = request_value["pieces"]
        .as_array()
        .expect("pieces array")
        .iter()
        .map(decode_prepared_piece)
        .collect();
    let source_pieces: Vec<ImportedPiece> = request_value["sourcePieces"]
        .as_array()
        .expect("sourcePieces array")
        .iter()
        .map(decode_imported_piece)
        .collect();
    let history_mode = match request_value["historyMode"].as_str().expect("historyMode") {
        "stream" => HistoryMode::Stream,
        "final" => HistoryMode::Final,
        "off" => HistoryMode::Off,
        other => panic!("unknown historyMode {other}"),
    };
    let request = NestingRequest {
        sheet,
        padding: request_value["padding"].as_f64().expect("padding"),
        pieces,
        source_pieces,
        options: NestingOptions {
            allow_global_rotation: request_value["allowGlobalRotation"]
                .as_bool()
                .expect("allowGlobalRotation"),
            allow_global_mirror: request_value["allowGlobalMirror"].as_bool(),
            history_mode,
            irregular_settings: None,
        },
    };
    (request, settings)
}

// ---------------------------------------------------------------------------
// Result encoding: mirrors `dump-coordinator.ts`'s own encoders field for
// field, so the two sides can be compared as plain `serde_json::Value`s.
// ---------------------------------------------------------------------------
fn encode_transform(transform: &irregular_nesting_native::domain::IrregularTransform) -> Value {
    serde_json::json!({
        "translateX": f64_bits(transform.translate_x),
        "translateY": f64_bits(transform.translate_y),
        "rotationDeg": f64_bits(transform.rotation_deg),
        "mirrored": transform.mirrored,
    })
}

fn encode_placement(placement: &irregular_nesting_native::domain::IrregularPlacement) -> Value {
    serde_json::json!({
        "pieceId": placement.piece_id.as_ref().map(|id| id.as_str().to_string()),
        "sourcePieceId": placement.source_piece_id.as_str(),
        "transform": encode_transform(&placement.transform),
    })
}

fn encode_score(score: &irregular_nesting_native::domain::IrregularLayoutScoreSummary) -> Value {
    serde_json::json!({
        "unplacedCount": f64_bits(score.unplaced_count),
        "sharedCollisionBoundaryLengthMm": opt_f64_bits(score.shared_collision_boundary_length_mm),
        "sharedCollisionBoundaryContactUnits": opt_f64_bits(score.shared_collision_boundary_contact_units),
        "sharedCollisionBoundaryContactBand": opt_f64_bits(score.shared_collision_boundary_contact_band),
        "nearCompleteStructuralContactCount": opt_f64_bits(score.near_complete_structural_contact_count),
        "dominantNearCompleteStructuralContactCount": opt_f64_bits(score.dominant_near_complete_structural_contact_count),
        "largestNetFreeMaterialRegionAreaMm2": f64_bits(score.largest_net_free_material_region_area_mm2),
        "freeMaterialRegionCount": f64_bits(score.free_material_region_count),
        "freeMaterialHoleCount": f64_bits(score.free_material_hole_count),
        "canonicalEnclosedCavityCount": opt_f64_bits(score.canonical_enclosed_cavity_count),
        "freeMaterialSliverMetric": f64_bits(score.free_material_sliver_metric),
        "collisionBoundsWorstNormalizedSheetConsumption": f64_bits(score.collision_bounds_worst_normalized_sheet_consumption),
        "collisionBoundsNormalizedSpanSum": f64_bits(score.collision_bounds_normalized_span_sum),
        "collisionBoundsAreaMm2": f64_bits(score.collision_bounds_area_mm2),
        "collisionBoundsSpanMm": f64_bits(score.collision_bounds_span_mm),
    })
}

/// `IrregularComputeResult.score` is TS's full internal `IrregularLayoutScore`
/// (`irregularLayoutScorer.ts:58-99`), not the `IrregularLayoutScoreSummary`
/// projection `portfolio.score` carries -- every field required, and it has
/// no `canonicalEnclosedCavityCount` field at all (`dump-coordinator.ts`'s
/// `encodeScore` reads that key from a plain object, gets `undefined` for
/// this type, and encodes `null`; mirrored here as a hardcoded `Value::Null`).
fn encode_layout_score(
    score: &irregular_nesting_native::search::layout_scorer::IrregularLayoutScore,
) -> Value {
    serde_json::json!({
        "unplacedCount": f64_bits(score.unplaced_count),
        "sharedCollisionBoundaryLengthMm": f64_bits(score.shared_collision_boundary_length_mm),
        "sharedCollisionBoundaryContactUnits": f64_bits(score.shared_collision_boundary_contact_units),
        "sharedCollisionBoundaryContactBand": f64_bits(score.shared_collision_boundary_contact_band),
        "nearCompleteStructuralContactCount": f64_bits(score.near_complete_structural_contact_count),
        "dominantNearCompleteStructuralContactCount": f64_bits(score.dominant_near_complete_structural_contact_count),
        "largestNetFreeMaterialRegionAreaMm2": f64_bits(score.largest_net_free_material_region_area_mm2),
        "freeMaterialRegionCount": f64_bits(score.free_material_region_count),
        "freeMaterialHoleCount": f64_bits(score.free_material_hole_count),
        "canonicalEnclosedCavityCount": Value::Null,
        "freeMaterialSliverMetric": f64_bits(score.free_material_sliver_metric),
        "collisionBoundsWorstNormalizedSheetConsumption": f64_bits(score.collision_bounds_worst_normalized_sheet_consumption),
        "collisionBoundsNormalizedSpanSum": f64_bits(score.collision_bounds_normalized_span_sum),
        "collisionBoundsAreaMm2": f64_bits(score.collision_bounds_area_mm2),
        "collisionBoundsSpanMm": f64_bits(score.collision_bounds_span_mm),
    })
}

fn portfolio_status_str(
    status: irregular_nesting_native::result::IrregularPortfolioStatus,
) -> &'static str {
    use irregular_nesting_native::result::IrregularPortfolioStatus as S;
    match status {
        S::Completed => "completed",
        S::Partial => "budget-expired",
        S::Failed => "no-valid-result",
    }
}

fn portfolio_termination_reason_str(
    reason: irregular_nesting_native::result::IrregularPortfolioTerminationReason,
) -> &'static str {
    use irregular_nesting_native::result::IrregularPortfolioTerminationReason as R;
    match reason {
        R::CapacitySubsetSettled => "capacity_subset_settled",
        R::SharedArchiveCompleted => "shared_archive_completed",
    }
}

fn search_source_str(
    source: irregular_nesting_native::result::IrregularSearchSource,
) -> &'static str {
    use irregular_nesting_native::result::IrregularSearchSource as Src;
    match source {
        Src::SharedArchive => "shared-archive",
    }
}

fn encode_portfolio(
    portfolio: &irregular_nesting_native::result::IrregularPortfolioResult,
) -> Value {
    serde_json::json!({
        "status": portfolio_status_str(portfolio.status),
        "terminationReason": portfolio_termination_reason_str(portfolio.termination_reason),
        "source": search_source_str(portfolio.source),
        "placements": portfolio.placements.iter().map(encode_placement).collect::<Vec<_>>(),
        "unplacedPieceIds": portfolio.unplaced_piece_ids.iter().map(|id| id.as_str().to_string()).collect::<Vec<_>>(),
        "score": encode_score(&portfolio.score),
    })
}

fn encode_snapshot(snapshot: &IrregularStateSnapshot) -> Value {
    use irregular_nesting_native::result::IrregularStateSnapshotSource as Src;
    serde_json::json!({
        "stepIndex": f64_bits(snapshot.step_index),
        "beamRank": f64_bits(snapshot.beam_rank),
        "candidateCount": f64_bits(snapshot.candidate_count),
        "source": snapshot.source.map(|source| match source {
            Src::Beam => "beam",
            Src::SharedArchive => "shared-archive",
        }),
        "placedPieceCount": f64_bits(snapshot.state.placed_collision_geometries.len() as f64),
        "remainingPreparedPieces": snapshot.state.remaining_prepared_pieces.iter().map(|piece| {
            encode_json_numbers_as_bits(
                serde_json::to_value(&**piece).expect("prepared piece serializes"),
            )
        }).collect::<Vec<_>>(),
    })
}

fn capacity_endpoint_origin_str(
    origin: irregular_nesting_native::capacity::endpoint::IntrinsicCapacityEndpointOrigin,
) -> &'static str {
    use irregular_nesting_native::capacity::endpoint::IntrinsicCapacityEndpointOrigin as O;
    match origin {
        O::ColdSearch => "cold-search",
        O::PrefixIncumbent => "prefix-incumbent",
        O::WarmPrefixContinuation => "warm-prefix-continuation",
    }
}

fn encode_capacity_objective(
    objective: &irregular_nesting_native::capacity::endpoint::IntrinsicCapacityObjective,
) -> Value {
    serde_json::json!({
        "placedCount": f64_bits(objective.placed_count),
        "placedDoubledMaterialAreaGrid2": objective.placed_doubled_material_area_grid2.to_string(),
        "enclosedCavityCount": f64_bits(objective.enclosed_cavity_count),
        "totalEnclosedCavityAreaMm2": f64_bits(objective.total_enclosed_cavity_area_mm2),
        "totalEnclosedCavityDoubledAreaGrid2": objective.total_enclosed_cavity_doubled_area_grid2,
        "envelopeMaximumSideMm": f64_bits(objective.envelope_maximum_side_mm),
        "envelopeAreaMm2": f64_bits(objective.envelope_area_mm2),
        "envelopeSpanMm": f64_bits(objective.envelope_span_mm),
        "envelopeMaximumSideGrid": f64_bits(objective.envelope_maximum_side_grid),
        "envelopeAreaGrid2": objective.envelope_area_grid2,
        "envelopeSpanGrid": f64_bits(objective.envelope_span_grid),
        "canonicalGeometryHash": objective.canonical_geometry_hash,
        "origin": capacity_endpoint_origin_str(objective.origin),
        "prefixDepth": opt_f64_bits(objective.prefix_depth),
        "sourceRole": objective.source_role,
    })
}

fn warm_prefix_lane_status_str(
    status: irregular_nesting_native::capacity::mode::WarmPrefixLaneStatus,
) -> &'static str {
    use irregular_nesting_native::capacity::mode::WarmPrefixLaneStatus as S;
    match status {
        S::Settled => "settled",
        S::CheckpointedCensored => "checkpointed-censored",
    }
}

fn encode_warm_prefix_lane(
    lane: &irregular_nesting_native::capacity::mode::IntrinsicCapacityWarmPrefixLaneTrace,
) -> Value {
    serde_json::json!({
        "sourceRole": lane.source_role,
        "prefixDepth": f64_bits(lane.prefix_depth),
        "reusedPlacedCount": f64_bits(lane.reused_placed_count),
        "status": warm_prefix_lane_status_str(lane.status),
        "selectedForContinuation": lane.selected_for_continuation,
        "checkpointRetained": lane.checkpoint_retained,
        "consumedPlacementEvaluations": f64_bits(lane.consumed_placement_evaluations),
        "completedDepths": f64_bits(lane.completed_depths),
        "endpoint": lane.endpoint.as_ref().map(encode_capacity_objective),
    })
}

fn quality_warm_prefix_status_str(
    status: irregular_nesting_native::capacity::mode::QualityWarmPrefixStatus,
) -> &'static str {
    use irregular_nesting_native::capacity::mode::QualityWarmPrefixStatus as S;
    match status {
        S::SkippedBelowMinimumPieceCount => "skipped-below-minimum-piece-count",
        S::SkippedNoFittingCanonicalPrefix => "skipped-no-fitting-canonical-prefix",
        S::Settled => "settled",
        S::EvaluationCap => "evaluation-cap",
        S::CheckpointedCensored => "checkpointed-censored",
    }
}

fn quality_output_influence_str(
    influence: irregular_nesting_native::capacity::mode::QualityWarmPrefixOutputInfluence,
) -> &'static str {
    use irregular_nesting_native::capacity::mode::QualityWarmPrefixOutputInfluence as I;
    match influence {
        I::None => "none",
        I::StrictCountImprovement => "strict-count-improvement",
    }
}

fn encode_quality_warm_prefix(
    trace: &irregular_nesting_native::capacity::mode::IntrinsicCapacityQualityWarmPrefixTrace,
) -> Value {
    serde_json::json!({
        "status": quality_warm_prefix_status_str(trace.status),
        "outputInfluence": quality_output_influence_str(trace.output_influence),
        "sourceRole": trace.source_role,
        "prefixDepth": opt_f64_bits(trace.prefix_depth),
        "reusedPlacedCount": f64_bits(trace.reused_placed_count),
        "requestPieceCount": f64_bits(trace.request_piece_count),
        "minimumPieceCount": f64_bits(trace.minimum_piece_count),
        "placementEvaluationCap": f64_bits(trace.placement_evaluation_cap),
        "consumedPlacementEvaluations": f64_bits(trace.consumed_placement_evaluations),
        "completedDepths": f64_bits(trace.completed_depths),
        "checkpointRetained": trace.checkpoint_retained,
        "endpoint": trace.endpoint.as_ref().map(encode_capacity_objective),
    })
}

fn lane_producer_role_str(
    role: irregular_nesting_native::capacity::mode::LaneCoordinatorQuantumProducerRole,
) -> &'static str {
    use irregular_nesting_native::capacity::mode::LaneCoordinatorQuantumProducerRole as R;
    match role {
        R::CapacityCold => "capacity-cold",
        R::CapacityQualityWarmPrefix => "capacity-quality-warm-prefix",
        R::CapacityWarmPrefix => "capacity-warm-prefix",
    }
}

fn lane_phase_str(
    phase: irregular_nesting_native::capacity::mode::LaneCoordinatorQuantumPhase,
) -> &'static str {
    use irregular_nesting_native::capacity::mode::LaneCoordinatorQuantumPhase as P;
    match phase {
        P::Initial => "initial",
        P::Resume => "resume",
        P::Censor => "censor",
    }
}

fn lane_outcome_str(
    outcome: irregular_nesting_native::capacity::mode::LaneCoordinatorQuantumOutcome,
) -> &'static str {
    use irregular_nesting_native::capacity::mode::LaneCoordinatorQuantumOutcome as O;
    match outcome {
        O::Checkpointed => "checkpointed",
        O::Settled => "settled",
        O::Censored => "censored",
    }
}

fn encode_lane_coordinator_quantum(
    quantum: &irregular_nesting_native::capacity::mode::IntrinsicCapacityLaneCoordinatorQuantum,
) -> Value {
    serde_json::json!({
        "ordinal": f64_bits(quantum.ordinal),
        "producerRole": lane_producer_role_str(quantum.producer_role),
        "sourceRole": quantum.source_role,
        "prefixDepth": opt_f64_bits(quantum.prefix_depth),
        "phase": lane_phase_str(quantum.phase),
        "fromDepth": f64_bits(quantum.from_depth),
        "toDepth": f64_bits(quantum.to_depth),
        "placementEvaluationDelta": f64_bits(quantum.placement_evaluation_delta),
        "outcome": lane_outcome_str(quantum.outcome),
    })
}

fn encode_lane_coordinator(
    trace: &irregular_nesting_native::capacity::mode::IntrinsicCapacityLaneCoordinatorTrace,
) -> Value {
    serde_json::json!({
        "aggregatePlacementEvaluationCap": f64_bits(trace.aggregate_placement_evaluation_cap),
        "aggregateConsumedPlacementEvaluations": f64_bits(trace.aggregate_consumed_placement_evaluations),
        "warmPilotDepthBoundaries": f64_bits(trace.warm_pilot_depth_boundaries),
        "retainedCheckpointCount": f64_bits(trace.retained_checkpoint_count),
        "censoredLaneCount": f64_bits(trace.censored_lane_count),
        "quanta": trace.quanta.iter().map(encode_lane_coordinator_quantum).collect::<Vec<_>>(),
    })
}

fn capacity_routing_str(
    routing: irregular_nesting_native::capacity::mode::IntrinsicCapacityRouting,
) -> &'static str {
    use irregular_nesting_native::capacity::mode::IntrinsicCapacityRouting as R;
    match routing {
        R::PreflightProvenImpossible => "preflight-proven-impossible",
        R::BoundedCompleteArchiveMiss => "bounded-complete-archive-miss",
    }
}

fn capacity_settlement_str(
    settlement: irregular_nesting_native::capacity::search::IntrinsicCapacitySettlement,
) -> &'static str {
    use irregular_nesting_native::capacity::search::IntrinsicCapacitySettlement as S;
    match settlement {
        S::Exhausted => "exhausted",
        S::EvaluationCap => "evaluation-cap",
        S::Paused => "paused",
    }
}

fn encode_capacity_trace(
    trace: &irregular_nesting_native::capacity::mode::IntrinsicCapacityTrace,
) -> Value {
    use irregular_nesting_native::capacity::preflight::IntrinsicCapacityPreflightOutcome as Preflight;
    use irregular_nesting_native::capacity::preflight::IntrinsicCapacityProvenImpossibleReason as Reason;
    let (preflight_kind, preflight_reason): (&str, Option<&str>) = match &trace.preflight {
        Preflight::ProvenImpossible { reason, .. } => (
            "proven_impossible",
            Some(match reason {
                Reason::SingletonTransformSetDoesNotFit { .. } => {
                    "singleton-transform-set-does-not-fit"
                }
                Reason::MinimumCollisionAreaExceedsSheetArea => {
                    "minimum-collision-area-exceeds-sheet-area"
                }
            }),
        ),
        Preflight::Inconclusive { .. } => ("inconclusive", None),
    };
    serde_json::json!({
        "routing": capacity_routing_str(trace.routing),
        "preflightKind": preflight_kind,
        "preflightReason": preflight_reason,
        "prefixes": {
            "capturedCount": f64_bits(trace.prefixes.captured_count),
            "fittingCount": f64_bits(trace.prefixes.fitting_count),
            "rejectedCount": f64_bits(trace.prefixes.rejected_count),
            "terminalizedCount": f64_bits(trace.prefixes.terminalized_count),
        },
        "prefixIncumbent": trace.prefix_incumbent.as_ref().map(|incumbent| serde_json::json!({
            "sourceRole": incumbent.source_role,
            "prefixDepth": opt_f64_bits(incumbent.prefix_depth),
            "placedCount": f64_bits(incumbent.placed_count),
            "placedMaterialAreaMm2": f64_bits(incumbent.placed_material_area_mm2),
            "selectedRotationDeg": f64_bits(incumbent.selected_rotation_deg),
            "canonicalGeometryHash": incumbent.canonical_geometry_hash,
        })),
        "coldSearch": {
            "settlement": capacity_settlement_str(trace.cold_search.settlement),
            "consumedPlacementEvaluations": f64_bits(trace.cold_search.consumed_placement_evaluations),
            "placementEvaluationCap": f64_bits(trace.cold_search.placement_evaluation_cap),
            "prunedByAttainableCount": f64_bits(trace.cold_search.pruned_by_attainable_count),
            "prunedByAttainableMaterial": f64_bits(trace.cold_search.pruned_by_attainable_material),
            "completedDepths": f64_bits(trace.cold_search.completed_depths),
            "pieceCount": f64_bits(trace.cold_search.piece_count),
        },
        "warmPrefixLanes": trace.warm_prefix_lanes.as_ref().map(|lanes| {
            lanes.iter().map(encode_warm_prefix_lane).collect::<Vec<_>>()
        }),
        "warmPrefixEndpointsAdmitted": trace.warm_prefix_endpoints_admitted,
        "cohesionShadow": trace.cohesion_shadow.as_ref().map(|_| "present"),
        "qualityWarmPrefix": trace.quality_warm_prefix.as_ref().map(encode_quality_warm_prefix),
        "laneCoordinator": trace.lane_coordinator.as_ref().map(encode_lane_coordinator),
        "selected": {
            "objective": encode_capacity_objective(&trace.selected.objective),
            "unplacedCount": f64_bits(trace.selected.unplaced_count),
            "placedMaterialAreaMm2": f64_bits(trace.selected.placed_material_area_mm2),
            "selectedRotationDeg": f64_bits(trace.selected.selected_rotation_deg),
        },
    })
}

fn scheduler_cold_start_status_str(
    status: irregular_nesting_native::result::IntrinsicAnytimeSchedulerColdStartStatus,
) -> &'static str {
    use irregular_nesting_native::result::IntrinsicAnytimeSchedulerColdStartStatus as S;
    match status {
        S::Paused => "paused",
        S::Settled => "settled",
    }
}

fn scheduler_cancellation_reason_str(
    reason: irregular_nesting_native::result::IntrinsicAnytimeSchedulerCancellationReason,
) -> &'static str {
    use irregular_nesting_native::result::IntrinsicAnytimeSchedulerCancellationReason as R;
    match reason {
        R::CompleteEndpointFitted => "complete-endpoint-fitted",
        R::CompleteCohortMiss => "complete-cohort-miss",
    }
}

fn scheduler_cohort_str(
    cohort: irregular_nesting_native::result::IntrinsicAnytimeSchedulerCohort,
) -> &'static str {
    use irregular_nesting_native::result::IntrinsicAnytimeSchedulerCohort as C;
    match cohort {
        C::Partial => "partial",
        C::Complete => "complete",
        C::ExperimentalComplete => "experimental-complete",
    }
}

fn scheduler_producer_role_str(
    role: irregular_nesting_native::result::IntrinsicAnytimeSchedulerProducerRole,
) -> &'static str {
    use irregular_nesting_native::result::IntrinsicAnytimeSchedulerProducerRole as R;
    match role {
        R::CapacityCold => "capacity-cold",
        R::CapacityQualityWarmPrefix => "capacity-quality-warm-prefix",
        R::LegacyComplete => "legacy-complete",
        R::CapacityWarmPrefix => "capacity-warm-prefix",
        R::ExperimentalPlaceDeferComplete => "experimental-place-defer-complete",
    }
}

fn scheduler_outcome_str(
    outcome: irregular_nesting_native::result::IntrinsicAnytimeSchedulerOutcome,
) -> &'static str {
    use irregular_nesting_native::result::IntrinsicAnytimeSchedulerOutcome as O;
    match outcome {
        O::Checkpointed => "checkpointed",
        O::Settled => "settled",
        O::Cancelled => "cancelled",
        O::Censored => "censored",
    }
}

fn encode_scheduler_trace(
    trace: &irregular_nesting_native::result::IntrinsicAnytimeSchedulerTrace,
) -> Value {
    serde_json::json!({
        "coldQuantumDepths": f64_bits(trace.cold_quantum_depths),
        "coldStartStatus": scheduler_cold_start_status_str(trace.cold_start_status),
        "coldStartCompletedDepths": f64_bits(trace.cold_start_completed_depths),
        "coldStartConsumedPlacementEvaluations": f64_bits(trace.cold_start_consumed_placement_evaluations),
        "coldCheckpointReused": trace.cold_checkpoint_reused,
        "warmPrefixEndpointsAdmitted": trace.warm_prefix_endpoints_admitted,
        "cancellationReason": trace.cancellation_reason.map(scheduler_cancellation_reason_str),
        "quanta": trace.quanta.iter().map(|quantum| serde_json::json!({
            "ordinal": f64_bits(quantum.ordinal as f64),
            "cohort": scheduler_cohort_str(quantum.cohort),
            "producerRole": scheduler_producer_role_str(quantum.producer_role),
            "outcome": scheduler_outcome_str(quantum.outcome),
        })).collect::<Vec<_>>(),
    })
}

fn focused_reconstruction_status_str(
    status: irregular_nesting_native::result::IntrinsicFocusedCompleteReconstructionStatus,
) -> &'static str {
    use irregular_nesting_native::result::IntrinsicFocusedCompleteReconstructionStatus as S;
    match status {
        S::Completed => "completed",
        S::DuplicateOrder => "duplicate-order",
        S::EvaluationCap => "evaluation-cap",
        S::Deadline => "deadline",
        S::Incomplete => "incomplete",
        S::FailedProtectedFallback => "failed-protected-fallback",
        S::SkippedPreflightProvenImpossible => "skipped-preflight-proven-impossible",
        S::SkippedNoFittingProtectedEndpoint => "skipped-no-fitting-protected-endpoint",
    }
}

fn focused_reconstruction_output_influence_str(
    influence: irregular_nesting_native::result::IntrinsicFocusedCompleteReconstructionOutputInfluence,
) -> &'static str {
    use irregular_nesting_native::result::IntrinsicFocusedCompleteReconstructionOutputInfluence as I;
    match influence {
        I::Selected => "selected",
        I::ProtectedFallback => "protected-fallback",
        I::None => "none",
    }
}

fn encode_focused_reconstruction(
    trace: &irregular_nesting_native::result::IntrinsicFocusedCompleteReconstructionTrace,
) -> Value {
    serde_json::json!({
        "status": focused_reconstruction_status_str(trace.status),
        "sourceCanonicalGeometryHash": trace.source_canonical_geometry_hash,
        "candidateCanonicalGeometryHash": trace.candidate_canonical_geometry_hash,
        "selectedCanonicalGeometryHash": trace.selected_canonical_geometry_hash,
        "consumedCandidateEvaluations": f64_bits(trace.consumed_candidate_evaluations),
        "candidateEvaluationAccountingComplete": trace.candidate_evaluation_accounting_complete,
        "outputInfluence": focused_reconstruction_output_influence_str(trace.output_influence),
        "failureReason": trace.failure_reason,
    })
}

fn encode_short_side_observer(
    trace: &irregular_nesting_native::short_side::observer::IntrinsicShortSideObserverTrace,
) -> Value {
    serde_json::json!({
        "status": trace.status.as_str(),
        "outputInfluence": trace.output_influence.as_str(),
        "settledEndpointCount": f64_bits(trace.settled_endpoint_count),
        "evaluatedOrientationCount": f64_bits(trace.evaluated_orientation_count),
        "observerWinnerCanonicalGeometryHash": Value::Null,
    })
}

fn encode_short_side_pair_fold(
    trace: &irregular_nesting_native::short_side::pair_fold::IntrinsicShortSidePairFoldTrace,
) -> Value {
    serde_json::json!({
        "status": trace.status.as_str(),
        "constructionKind": trace.construction_kind.map(|kind| kind.as_str()),
        "canonicalGeometryHash": trace.canonical_geometry_hash,
        "outputInfluence": trace.output_influence.as_str(),
    })
}

fn encode_result(result: &IrregularComputeResult) -> Value {
    serde_json::json!({
        "placedCollisionGeometryCount": f64_bits(result.placed_collision_geometries.len() as f64),
        "placements": result.placed_collision_geometries.iter().map(|placed| encode_placement(&placed.placement)).collect::<Vec<_>>(),
        "unplacedPieceIds": result.unplaced_piece_ids.iter().map(|id| id.as_str().to_string()).collect::<Vec<_>>(),
        "sortedPieceIds": result.sorted_piece_ids.iter().map(|id| id.as_str().to_string()).collect::<Vec<_>>(),
        "beamWidth": f64_bits(result.beam_width),
        "score": encode_layout_score(&result.score),
        "portfolio": encode_portfolio(&result.portfolio),
        "snapshotCount": f64_bits(result.state_snapshots.len() as f64),
        "snapshots": result.state_snapshots.iter().map(encode_snapshot).collect::<Vec<_>>(),
        "capacityTrace": result.capacity_trace.as_ref().map(encode_capacity_trace),
        "intrinsicAnytimeSchedulerTrace": result.intrinsic_anytime_scheduler_trace.as_ref().map(encode_scheduler_trace),
        "focusedCompleteReconstructionTrace": result.focused_complete_reconstruction_trace.as_ref().map(encode_focused_reconstruction),
        "intrinsicShortSideObserverTrace": result.intrinsic_short_side_observer_trace.as_ref().map(encode_short_side_observer),
        "intrinsicShortSidePairFoldTrace": result.intrinsic_short_side_pair_fold_trace.as_ref().map(encode_short_side_pair_fold),
    })
}

/// Collects every structural/value mismatch between `actual` and `expected`
/// (recursing through objects/arrays) into `mismatches` as `"{path}:
/// actual={a} expected={b}"` strings, rather than panicking on the first
/// one -- lets the differential suite report the *complete* scope of any
/// divergence across all cases in one run instead of stopping at the first
/// case/field.
fn collect_json_diffs(actual: &Value, expected: &Value, path: &str, mismatches: &mut Vec<String>) {
    match (actual, expected) {
        (Value::Object(actual_map), Value::Object(expected_map)) => {
            let mut keys: Vec<&String> = actual_map.keys().chain(expected_map.keys()).collect();
            keys.sort();
            keys.dedup();
            for key in keys {
                let child_path = format!("{path}.{key}");
                let actual_child = actual_map.get(key).unwrap_or(&Value::Null);
                let expected_child = expected_map.get(key).unwrap_or(&Value::Null);
                collect_json_diffs(actual_child, expected_child, &child_path, mismatches);
            }
        }
        (Value::Array(actual_arr), Value::Array(expected_arr)) => {
            if actual_arr.len() != expected_arr.len() {
                mismatches.push(format!(
                    "{path}: array length mismatch actual={} expected={}",
                    actual_arr.len(),
                    expected_arr.len()
                ));
                return;
            }
            for (index, (actual_item, expected_item)) in
                actual_arr.iter().zip(expected_arr.iter()).enumerate()
            {
                collect_json_diffs(
                    actual_item,
                    expected_item,
                    &format!("{path}[{index}]"),
                    mismatches,
                );
            }
        }
        (actual_leaf, expected_leaf) => {
            if actual_leaf != expected_leaf {
                mismatches.push(format!(
                    "{path}: actual={actual_leaf} expected={expected_leaf}"
                ));
            }
        }
    }
}

#[test]
fn full_job_vectors_match_ts_oracle() {
    let vectors = load_vectors();
    let cases = vectors["cases"].as_array().expect("cases array");
    let case_count = vectors["caseCount"].as_u64().expect("caseCount") as usize;
    assert_eq!(cases.len(), case_count);
    assert!(
        case_count >= 80,
        "expected >= 80 coordinator vectors, got {case_count}"
    );

    let mut settled = 0usize;
    let mut preflight_proven_impossible = 0usize;
    let mut bounded_complete_archive_miss = 0usize;
    let mut all_mismatches: Vec<String> = Vec::new();

    for case in cases {
        let case_id = case["caseId"].as_str().expect("caseId");
        let (request, settings) = decode_request(case);

        let mut options = ComputeIrregularNestingOptions::default();
        let mut geometry_cache = GeometryCacheStore::new();
        let mut free_material_cache = FreeMaterialCache::new();

        let result = compute_irregular_nesting(
            &request,
            &settings,
            &mut options,
            &mut geometry_cache,
            &mut free_material_cache,
        )
        .unwrap_or_else(|error| panic!("case {case_id} failed in Rust: {error:?}"));

        match &result.capacity_trace {
            None => settled += 1,
            Some(trace) => match trace.routing {
                irregular_nesting_native::capacity::mode::IntrinsicCapacityRouting::PreflightProvenImpossible => {
                    preflight_proven_impossible += 1
                }
                irregular_nesting_native::capacity::mode::IntrinsicCapacityRouting::BoundedCompleteArchiveMiss => {
                    bounded_complete_archive_miss += 1
                }
            },
        }

        let actual = encode_result(&result);
        let expected = &case["result"];
        let before = all_mismatches.len();
        collect_json_diffs(&actual, expected, "result", &mut all_mismatches);
        if all_mismatches.len() > before {
            for mismatch in &all_mismatches[before..] {
                eprintln!("case {case_id}: {mismatch}");
            }
        }
    }

    assert!(
        all_mismatches.is_empty(),
        "{} field mismatch(es) across {} cases (see stderr for the full per-case list)",
        all_mismatches.len(),
        cases.len()
    );

    let expected_routing = &vectors["routingCounts"];
    assert_eq!(
        settled as u64,
        expected_routing["none"].as_u64().unwrap(),
        "settled (no capacity trace) count mismatch"
    );
    assert_eq!(
        preflight_proven_impossible as u64,
        expected_routing["preflight-proven-impossible"]
            .as_u64()
            .unwrap(),
        "preflight-proven-impossible count mismatch"
    );
    assert_eq!(
        bounded_complete_archive_miss as u64,
        expected_routing["bounded-complete-archive-miss"]
            .as_u64()
            .unwrap(),
        "bounded-complete-archive-miss count mismatch"
    );
    assert!(preflight_proven_impossible > 0);
    assert!(bounded_complete_archive_miss > 0);
}

// ===========================================================================
// Control-threading regression: `on_canonical_grid_checkpointed`'s nested
// `run_intrinsic_capacity_scheduler_cold_quantum` resume must thread the
// real cooperative-cancellation control, exactly as TS
// `computeIrregularNesting.ts:673-684` does. Loads
// `tests/vectors/coordinator-cancellation.json` (generated by
// `scripts/rust-parity/dump-coordinator-cancellation.ts` from the real TS
// oracle, using a deterministic call-counting `isCancelled` injected at the
// same, independently-calibrated call ordinal on both sides -- see that
// script's own top doc for the full calibration methodology and evidence
// that Rust and TS make checkpoint calls in the same order/count for this
// scenario) and reproduces every recorded outcome in Rust.
// ===========================================================================

fn load_cancellation_vectors() -> Value {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/vectors/coordinator-cancellation.json"
    );
    let raw = fs::read_to_string(path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&raw).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

fn cancellation_scenario_request(vectors: &Value) -> (NestingRequest, IrregularNestingSettings) {
    let scenario = &vectors["scenario"];
    let sheet_json = &scenario["sheet"];
    let sheet = SheetSpec {
        width: sheet_json["width"].as_f64().expect("sheet.width"),
        height: sheet_json["height"].as_f64().expect("sheet.height"),
        label: sheet_json["label"]
            .as_str()
            .expect("sheet.label")
            .to_string(),
    };
    let pieces_json = scenario["pieces"]
        .as_array()
        .expect("scenario.pieces array");
    let mut pieces = Vec::with_capacity(pieces_json.len());
    let mut source_pieces = Vec::with_capacity(pieces_json.len());
    for piece in pieces_json {
        let id = piece["id"].as_str().expect("piece.id");
        let w = piece["width"].as_f64().expect("piece.width");
        let h = piece["height"].as_f64().expect("piece.height");
        pieces.push(rect_prepared_piece(id, w, h));
        source_pieces.push(rect_source_piece(id, w, h));
    }
    let request = NestingRequest {
        sheet,
        padding: 0.0,
        pieces,
        source_pieces,
        options: NestingOptions {
            allow_global_rotation: true,
            allow_global_mirror: Some(true),
            history_mode: HistoryMode::Off,
            irregular_settings: None,
        },
    };
    (request, compact_settings())
}

/// Runs the scenario with a deterministic call-counting `is_cancelled`:
/// returns `true` on exactly the `cancel_at_ordinal`th invocation (1-indexed,
/// `None` disables cancellation entirely -- matches the TS oracle script's
/// own `runWithCancelAt` semantics exactly). Also returns the total number
/// of `is_cancelled` invocations observed, so callers can pin the exact
/// call count against the TS oracle's own recorded count -- this is the
/// decisive signal that distinguishes the fixed control-threading from the
/// original defect: with `control` not threaded into the nested resume, its
/// own internal checkpoint calls never poll `is_cancelled` at all, so the
/// observed count for an uncancelled run drops by exactly however many
/// calls the nested resume's own cold search would otherwise have made
/// (confirmed empirically while authoring this test: 6966 instead of
/// 10098, a shortfall of exactly `nestedResumeLastCallOrdinal -
/// nestedResumeFirstCallOrdinal + 1 = 3132`). A "does cancelling at ordinal
/// N abort the job at all" check alone is *not* decisive: since
/// `is_cancelled` is a single shared counter across the whole job, a
/// defective build that skips polling it during the nested resume's window
/// still eventually reaches the Nth call at some *later*, unrelated
/// checkpoint elsewhere in the job and aborts there instead -- externally
/// indistinguishable from aborting inside the nested resume. The exact
/// total-call-count pin closes that gap.
fn run_cancellation_scenario(
    request: &NestingRequest,
    settings: &IrregularNestingSettings,
    cancel_at_ordinal: Option<u64>,
) -> (
    Result<IrregularComputeResult, IrregularComputeErrorType>,
    u64,
) {
    let mut call_count: u64 = 0;
    let mut cancellation_reason = || {
        call_count += 1;
        (Some(call_count) == cancel_at_ordinal).then_some(NfpIfpAbortReason::Cancelled)
    };
    let mut options = ComputeIrregularNestingOptions {
        event_sink: None,
        cancellation_reason: Some(&mut cancellation_reason),
        focused_complete_reconstruction_enabled: true,
    };
    let mut geometry_cache = GeometryCacheStore::new();
    let mut free_material_cache = FreeMaterialCache::new();
    let result = compute_irregular_nesting(
        request,
        settings,
        &mut options,
        &mut geometry_cache,
        &mut free_material_cache,
    );
    (result, call_count)
}

fn assert_cancelled(
    result: &Result<IrregularComputeResult, IrregularComputeErrorType>,
    label: &str,
) {
    match result {
        Err(IrregularComputeErrorType::NfpIfpControlAbort(abort)) => {
            assert_eq!(
                abort.reason,
                NfpIfpAbortReason::Cancelled,
                "{label}: expected abort reason Cancelled"
            );
        }
        other => panic!("{label}: expected a cancelled NfpIfpControlAbort, got {other:?}"),
    }
}

#[test]
fn baseline_uncancelled_run_matches_ts_oracle_and_fires_the_nested_resume() {
    let vectors = load_cancellation_vectors();
    let (request, settings) = cancellation_scenario_request(&vectors);

    let (result, total_calls) = run_cancellation_scenario(&request, &settings, None);
    let result =
        result.unwrap_or_else(|err| panic!("baseline (uncancelled) run must succeed: {err:?}"));

    let expected_baseline = &vectors["baseline"];
    assert_eq!(expected_baseline["outcome"], "ok");
    // The decisive regression pin (see `run_cancellation_scenario`'s own doc
    // comment): this exact count is only reached when the nested resume's
    // own internal checkpoint calls are actually being polled, i.e. only
    // when `control` is threaded into it. A reintroduced defect (`None`
    // hardcoded again) reproducibly drops this to 6966 for this scenario --
    // confirmed by temporarily reintroducing the defect while authoring this
    // test -- while every other assertion in this test still passes
    // (the algorithm's *output* is unaffected by whether checkpoint calls
    // happen when nothing ever cancels).
    assert_eq!(
        total_calls,
        expected_baseline["totalCalls"].as_u64().unwrap(),
        "total is_cancelled() call count must match the TS oracle exactly -- a mismatch here \
         means control is not being polled somewhere it should be (e.g. the nested resume again \
         defaulting to `None`)"
    );
    let trace = result
        .intrinsic_anytime_scheduler_trace
        .as_ref()
        .expect("baseline run must produce an intrinsicAnytimeSchedulerTrace");

    // TS: `quanta[1]` is the interleaved scheduler's own `legacy-complete`/
    // `checkpointed` quantum (the canonical-grid checkpoint firing); `quanta[2]`
    // is the nested resume's own `capacity-cold`/`partial` quantum -- this
    // pair existing at all is direct, oracle-matched proof the nested resume
    // fired for this scenario.
    let expected_quanta = expected_baseline["quanta"]
        .as_array()
        .expect("baseline.quanta array");
    assert_eq!(
        trace.quanta.len(),
        expected_quanta.len(),
        "baseline quanta length mismatch"
    );
    for (actual, expected) in trace.quanta.iter().zip(expected_quanta.iter()) {
        assert_eq!(actual.cohort.as_str(), expected["cohort"], "quantum cohort");
        assert_eq!(
            actual.producer_role.as_str(),
            expected["producerRole"],
            "quantum producerRole"
        );
        assert_eq!(
            actual.outcome.as_str(),
            expected["outcome"],
            "quantum outcome"
        );
    }
    assert_eq!(trace.quanta[1].producer_role.as_str(), "legacy-complete");
    assert_eq!(trace.quanta[1].outcome.as_str(), "checkpointed");
    assert_eq!(trace.quanta[2].producer_role.as_str(), "capacity-cold");
    assert_eq!(trace.quanta[2].cohort.as_str(), "partial");
}

#[test]
fn cancellation_injected_during_the_nested_scheduler_resume_aborts_the_whole_job() {
    let vectors = load_cancellation_vectors();
    let (request, settings) = cancellation_scenario_request(&vectors);

    let first_ordinal = vectors["nestedResumeFirstCallOrdinal"]
        .as_u64()
        .expect("nestedResumeFirstCallOrdinal");
    let last_ordinal = vectors["nestedResumeLastCallOrdinal"]
        .as_u64()
        .expect("nestedResumeLastCallOrdinal");
    assert_eq!(
        vectors["cancelledAtNestedResumeFirstCall"]["cancelAtOrdinal"]
            .as_u64()
            .unwrap(),
        first_ordinal
    );
    assert_eq!(
        vectors["cancelledAtNestedResumeLastCall"]["cancelAtOrdinal"]
            .as_u64()
            .unwrap(),
        last_ordinal
    );

    // The nested resume's own `control.checkpoint()` calls span the closed
    // interval `[first_ordinal, last_ordinal]`. Before the control-threading
    // fix, the nested resume was passed `None` for `control`; a naive "does
    // cancelling at ordinal N abort the job at all" check alone would *not*
    // have caught that defect (see `run_cancellation_scenario`'s own doc
    // comment for why -- the shared counter still eventually reaches N at
    // some later, unrelated checkpoint and aborts there instead). The
    // `baseline_uncancelled_run_matches_ts_oracle_and_fires_the_nested_resume`
    // test above carries the decisive total-call-count pin that does catch
    // it; this test additionally confirms every ordinal in the resume's own
    // window still aborts (necessary, once the count pin above holds, for
    // every individual ordinal in range to correspond to a real checkpoint
    // call somewhere in the job).
    let (at_first, _) = run_cancellation_scenario(&request, &settings, Some(first_ordinal));
    assert_cancelled(&at_first, "cancelled at the nested resume's first call");

    let (at_last, _) = run_cancellation_scenario(&request, &settings, Some(last_ordinal));
    assert_cancelled(&at_last, "cancelled at the nested resume's last call");

    let midpoint = first_ordinal + (last_ordinal - first_ordinal) / 2;
    let (at_midpoint, _) = run_cancellation_scenario(&request, &settings, Some(midpoint));
    assert_cancelled(&at_midpoint, "cancelled mid-way through the nested resume");

    // Sanity control: cancelling one call before the resume begins also
    // aborts (the outer control threading was never broken) -- confirms the
    // counting scheme itself is wired correctly, not just the fixed path.
    let (just_before, _) = run_cancellation_scenario(&request, &settings, Some(first_ordinal - 1));
    assert_cancelled(&just_before, "cancelled one call before the nested resume");
}
