//! Differential-vector test for
//! `crates/irregular-nesting-native/src/geometry/free_material.rs`.
//!
//! Loads `tests/vectors/free-material.json`, generated by
//! `scripts/rust-parity/dump-free-material.ts` from the REAL production
//! `freeMaterialService.ts` (`createFreeMaterialService('union-then-difference')`
//! == `FreeMaterialServiceLive`, `createFreeMaterialService('direct-difference')`,
//! and `extendFreeMaterial`), and asserts this crate's Rust port
//! (`compute_free_material`/`compute_free_material_live`/`extend_free_material`)
//! reproduces every recorded snapshot (region/hole order and every boundary
//! point) and every typed-error `(operation, message)` pair exactly, plus
//! every bit-exact `f64` coordinate (via `to_bits()`).

use std::fs;

use irregular_nesting_native::domain::{
    FreeMaterialRegion, FreeMaterialSnapshot, IrregularBounds, IrregularGeometrySettings,
    IrregularPlacedPiece, IrregularPlacement, IrregularPoint, IrregularPolygon, IrregularTransform,
    IrregularTransformCandidate, IrregularTransformReason, PieceId, SheetSpec,
    TransformedCollisionGeometry,
};
use irregular_nesting_native::geometry::free_material::{
    compute_free_material, compute_free_material_live, extend_free_material,
    ComputeFreeMaterialInput, ExtendFreeMaterialInput, FreeMaterialOperation,
};
use serde_json::Value;

fn load_vectors() -> Value {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/vectors/free-material.json"
    );
    let raw = fs::read_to_string(path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&raw).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

fn parse_f64_bits(hex: &str) -> f64 {
    let stripped = hex
        .strip_prefix("0x")
        .unwrap_or_else(|| panic!("bit-pattern hex must start with 0x, got {hex}"));
    let bits = u64::from_str_radix(stripped, 16)
        .unwrap_or_else(|err| panic!("invalid bit-pattern hex {hex}: {err}"));
    f64::from_bits(bits)
}

fn decode_point(value: &Value) -> IrregularPoint {
    let x = parse_f64_bits(value["x"].as_str().expect("point.x present"));
    let y = parse_f64_bits(value["y"].as_str().expect("point.y present"));
    IrregularPoint::new(x, y)
}

fn decode_points(value: &Value) -> Vec<IrregularPoint> {
    value
        .as_array()
        .expect("points array present")
        .iter()
        .map(decode_point)
        .collect()
}

fn decode_polygon(value: &Value) -> IrregularPolygon {
    IrregularPolygon::new(decode_points(value))
}

fn decode_sheet(value: &Value) -> SheetSpec {
    SheetSpec {
        width: parse_f64_bits(value["width"].as_str().expect("sheet.width present")),
        height: parse_f64_bits(value["height"].as_str().expect("sheet.height present")),
        label: value["label"]
            .as_str()
            .expect("sheet.label present")
            .to_string(),
    }
}

fn bounds_of(points: &[IrregularPoint]) -> IrregularBounds {
    let min_x = points.iter().map(|p| p.x).fold(f64::INFINITY, f64::min);
    let min_y = points.iter().map(|p| p.y).fold(f64::INFINITY, f64::min);
    let max_x = points.iter().map(|p| p.x).fold(f64::NEG_INFINITY, f64::max);
    let max_y = points.iter().map(|p| p.y).fold(f64::NEG_INFINITY, f64::max);
    IrregularBounds::new(min_x, min_y, max_x, max_y)
}

/// Reconstructs an `IrregularPlacedPiece` from the vector file's recorded
/// `pieceId`/`points`/`translateX`/`translateY`/`mirrored` fields. Every
/// other `IrregularPlacedPiece` field (`rotationDeg`, the transform
/// candidate's `index`/`reason`, and `bounds`) is never read by
/// `free_material`'s algorithm (only `collision_geometry.polygon.points` and
/// `placement.transform.{translate_x,translate_y}` are), so those are filled
/// with arbitrary valid placeholder values here, matching this crate's
/// established convention (see `transforms_vectors.rs`'s
/// `full_optimizer_settings` doc comment for the same pattern).
fn decode_placed_piece(value: &Value) -> IrregularPlacedPiece {
    let piece_id = PieceId::new(value["pieceId"].as_str().expect("pieceId present"));
    let points = decode_points(&value["points"]);
    let translate_x = parse_f64_bits(value["translateX"].as_str().expect("translateX present"));
    let translate_y = parse_f64_bits(value["translateY"].as_str().expect("translateY present"));
    let mirrored = value["mirrored"].as_bool().expect("mirrored present");
    let bounds = bounds_of(&points);
    let polygon = IrregularPolygon::new(points);

    IrregularPlacedPiece {
        placement: IrregularPlacement {
            piece_id: None,
            source_piece_id: piece_id.clone(),
            placement_reference: None,
            transform: IrregularTransform {
                translate_x,
                translate_y,
                rotation_deg: 0.0,
                mirrored,
            },
        },
        collision_geometry: TransformedCollisionGeometry {
            source_piece_id: piece_id,
            transform: IrregularTransformCandidate {
                index: 0.0,
                rotation_deg: 0.0,
                mirrored,
                reason: IrregularTransformReason::Configured,
            },
            polygon,
            bounds,
        },
    }
}

fn decode_snapshot(value: &Value) -> FreeMaterialSnapshot {
    let sheet = decode_sheet(&value["sheet"]);
    let regions = value["regions"]
        .as_array()
        .expect("regions array present")
        .iter()
        .map(|region| FreeMaterialRegion {
            boundary: decode_polygon(&region["boundary"]),
            holes: region["holes"]
                .as_array()
                .expect("holes array present")
                .iter()
                .map(decode_polygon)
                .collect(),
        })
        .collect();
    let diagnostics_count = value["diagnosticsCount"]
        .as_u64()
        .expect("diagnosticsCount present");
    assert_eq!(
        diagnostics_count, 0,
        "freeMaterialService.ts's own construction always leaves diagnostics empty"
    );
    FreeMaterialSnapshot {
        sheet,
        regions,
        diagnostics: Vec::new(),
    }
}

fn parse_operation(raw: &str) -> FreeMaterialOperation {
    match raw {
        "union-then-difference" => FreeMaterialOperation::UnionThenDifference,
        "direct-difference" => FreeMaterialOperation::DirectDifference,
        other => panic!("unrecognized FreeMaterialOperation: {other}"),
    }
}

fn geometry_settings() -> IrregularGeometrySettings {
    // Never read by `free_material`'s algorithm (see
    // `ComputeFreeMaterialInput`'s doc comment); an arbitrary valid value.
    IrregularGeometrySettings {
        flattening_sag_tolerance_mm: 0.25,
        clearance_safety_margin_mm: 0.25,
        geometry_backend_id: "free-material-vectors".to_string(),
        geometry_backend_version: "0".to_string(),
    }
}

fn assert_snapshot_eq(actual: &FreeMaterialSnapshot, expected: &FreeMaterialSnapshot, label: &str) {
    assert_eq!(
        actual.sheet, expected.sheet,
        "{label}: sheet mismatch (rust={:?} ts={:?})",
        actual.sheet, expected.sheet
    );
    assert_eq!(
        actual.regions.len(),
        expected.regions.len(),
        "{label}: region count mismatch"
    );
    for (region_index, (actual_region, expected_region)) in actual
        .regions
        .iter()
        .zip(expected.regions.iter())
        .enumerate()
    {
        assert_points_eq(
            &actual_region.boundary.points,
            &expected_region.boundary.points,
            &format!("{label} region {region_index} boundary"),
        );
        assert_eq!(
            actual_region.holes.len(),
            expected_region.holes.len(),
            "{label} region {region_index}: hole count mismatch"
        );
        for (hole_index, (actual_hole, expected_hole)) in actual_region
            .holes
            .iter()
            .zip(expected_region.holes.iter())
            .enumerate()
        {
            assert_points_eq(
                &actual_hole.points,
                &expected_hole.points,
                &format!("{label} region {region_index} hole {hole_index}"),
            );
        }
    }
    assert!(
        actual.diagnostics.is_empty() && expected.diagnostics.is_empty(),
        "{label}: diagnostics must always be empty"
    );
}

fn assert_points_eq(actual: &[IrregularPoint], expected: &[IrregularPoint], label: &str) {
    assert_eq!(
        actual.len(),
        expected.len(),
        "{label}: point count mismatch"
    );
    for (index, (actual_point, expected_point)) in actual.iter().zip(expected.iter()).enumerate() {
        assert_eq!(
            actual_point.x.to_bits(),
            expected_point.x.to_bits(),
            "{label} point {index}: x mismatch: rust={} ts={}",
            actual_point.x,
            expected_point.x
        );
        assert_eq!(
            actual_point.y.to_bits(),
            expected_point.y.to_bits(),
            "{label} point {index}: y mismatch: rust={} ts={}",
            actual_point.y,
            expected_point.y
        );
    }
}

#[test]
fn compute_free_material_matches_ts_production_oracle_over_the_full_matrix() {
    let file = load_vectors();

    let generating_commit = file["generatingCommit"]
        .as_str()
        .expect("generatingCommit header present");
    assert!(
        !generating_commit.is_empty(),
        "vectors file must record its generating commit (ruling R14)"
    );

    let case_count = file["computeCaseCount"]
        .as_u64()
        .expect("computeCaseCount header present") as usize;
    let cases = file["computeCases"]
        .as_array()
        .expect("computeCases present");
    assert_eq!(
        cases.len(),
        case_count,
        "case count header must match actual cases"
    );

    let mut union_then_difference_live_checked = 0usize;

    for case in cases {
        let case_label = case["caseLabel"].as_str().expect("caseLabel present");
        let operation = parse_operation(case["operation"].as_str().expect("operation present"));
        let sheet = decode_sheet(&case["sheet"]);
        let placed: Vec<IrregularPlacedPiece> = case["placed"]
            .as_array()
            .expect("placed array present")
            .iter()
            .map(decode_placed_piece)
            .collect();

        let input = ComputeFreeMaterialInput {
            sheet: sheet.clone(),
            placed,
            settings: geometry_settings(),
        };

        let outcome = &case["outcome"];
        let ok = outcome["ok"].as_bool().expect("outcome.ok present");

        let result = compute_free_material(&input, operation);

        if ok {
            let expected_snapshot = decode_snapshot(&outcome["snapshot"]);
            let actual_snapshot = result
                .unwrap_or_else(|err| panic!("case {case_label}: expected success, got {err:?}"));
            assert_snapshot_eq(&actual_snapshot, &expected_snapshot, case_label);

            // Every `union-then-difference` case is also the production
            // `FreeMaterialServiceLive` path; cross-check
            // `compute_free_material_live` reproduces the identical snapshot.
            if operation == FreeMaterialOperation::UnionThenDifference {
                let live_snapshot = compute_free_material_live(&input).unwrap_or_else(|err| {
                    panic!("case {case_label}: compute_free_material_live failed: {err:?}")
                });
                assert_snapshot_eq(
                    &live_snapshot,
                    &expected_snapshot,
                    &format!("{case_label} (live)"),
                );
                union_then_difference_live_checked += 1;
            }
        } else {
            let expected_operation = outcome["operation"]
                .as_str()
                .expect("outcome.operation present");
            let expected_message = outcome["message"]
                .as_str()
                .expect("outcome.message present");
            let error = result
                .err()
                .unwrap_or_else(|| panic!("case {case_label}: expected failure, got success"));
            assert_eq!(
                error.operation, expected_operation,
                "case {case_label}: error operation mismatch"
            );
            assert_eq!(
                error.message, expected_message,
                "case {case_label}: error message mismatch"
            );
        }
    }

    assert!(
        union_then_difference_live_checked >= 100,
        "expected a substantial number of union-then-difference/live cases, got {union_then_difference_live_checked}"
    );
}

#[test]
fn extend_free_material_matches_ts_production_oracle_over_parent_chains() {
    let file = load_vectors();

    let chain_count = file["extendChainCount"]
        .as_u64()
        .expect("extendChainCount header present") as usize;
    let step_vector_count = file["extendStepVectorCount"]
        .as_u64()
        .expect("extendStepVectorCount header present") as usize;
    let chains = file["extendChains"]
        .as_array()
        .expect("extendChains present");
    assert_eq!(
        chains.len(),
        chain_count,
        "chain count header must match actual chains"
    );

    let mut checked_steps = 0usize;

    for chain in chains {
        let chain_label = chain["chainLabel"].as_str().expect("chainLabel present");
        let steps = chain["steps"].as_array().expect("steps array present");

        for step in steps {
            let step_label = step["stepLabel"].as_str().expect("stepLabel present");
            let parent = decode_snapshot(&step["parent"]);
            let placed = decode_placed_piece(&step["placed"]);
            let outcome = &step["outcome"];
            let ok = outcome["ok"].as_bool().expect("outcome.ok present");

            let input = ExtendFreeMaterialInput {
                parent,
                placed,
                settings: geometry_settings(),
            };
            let result = extend_free_material(&input);

            if ok {
                let expected_snapshot = decode_snapshot(&outcome["snapshot"]);
                let actual_snapshot = result.unwrap_or_else(|err| {
                    panic!("chain {chain_label} step {step_label}: expected success, got {err:?}")
                });
                assert_snapshot_eq(&actual_snapshot, &expected_snapshot, step_label);
            } else {
                let expected_operation = outcome["operation"]
                    .as_str()
                    .expect("outcome.operation present");
                let expected_message = outcome["message"]
                    .as_str()
                    .expect("outcome.message present");
                let error = result.err().unwrap_or_else(|| {
                    panic!("chain {chain_label} step {step_label}: expected failure, got success")
                });
                assert_eq!(error.operation, expected_operation);
                assert_eq!(error.message, expected_message);
            }
            checked_steps += 1;
        }
    }

    assert_eq!(
        checked_steps, step_vector_count,
        "checked step count must match the header's extendStepVectorCount"
    );
}

#[test]
fn extend_free_material_matches_ts_production_oracle_for_malformed_geometry() {
    let file = load_vectors();

    let case_count = file["extendMalformedCaseCount"]
        .as_u64()
        .expect("extendMalformedCaseCount header present") as usize;
    let cases = file["extendMalformedCases"]
        .as_array()
        .expect("extendMalformedCases present");
    assert_eq!(
        cases.len(),
        case_count,
        "extend malformed case count header must match actual cases"
    );
    assert!(
        !cases.is_empty(),
        "expected at least one malformed extend case"
    );

    for case in cases {
        let case_label = case["caseLabel"].as_str().expect("caseLabel present");
        let parent = decode_snapshot(&case["parent"]);
        let placed = decode_placed_piece(&case["placed"]);
        let outcome = &case["outcome"];
        assert!(
            !outcome["ok"].as_bool().expect("outcome.ok present"),
            "case {case_label}: every recorded extend malformed case must be a failure"
        );
        let expected_operation = outcome["operation"]
            .as_str()
            .expect("outcome.operation present");
        let expected_message = outcome["message"]
            .as_str()
            .expect("outcome.message present");

        let input = ExtendFreeMaterialInput {
            parent,
            placed,
            settings: geometry_settings(),
        };
        let error = extend_free_material(&input)
            .err()
            .unwrap_or_else(|| panic!("case {case_label}: expected failure, got success"));
        assert_eq!(error.operation, expected_operation);
        assert_eq!(error.message, expected_message);
    }
}

#[test]
fn total_vector_count_meets_the_task_spec_floor() {
    let file = load_vectors();
    let total = file["totalVectorCount"]
        .as_u64()
        .expect("totalVectorCount header present");
    assert!(
        total >= 300,
        "expected >= 300 free-material vectors per the task spec, got {total}"
    );
}
