//! Differential-vector test for
//! `crates/irregular-nesting-native/src/search/gap_regions.rs` and
//! `crates/irregular-nesting-native/src/search/strict_family.rs`.
//!
//! Loads `tests/vectors/gap-family.json`, generated by
//! `scripts/rust-parity/dump-gap-family.ts` from the REAL production
//! `deriveCanonicalIntrinsicGapRegions`/`candidateContainedInIntrinsicGap`
//! (`src/workers/algorithm/irregular/intrinsicGapRegions.ts`) and
//! `groupIntrinsicCollisionFamilies`/`intrinsicCollisionFamilyKey`
//! (`src/workers/algorithm/irregular/intrinsicStrictFamilyPortfolio.ts`),
//! and asserts this crate's Rust port reproduces every recorded outcome
//! exactly: full ordered gap-region lists (kind, boundary/hole grid paths,
//! `areaMm2`, exact `doubledAreaGrid2` BigInt string, `aabb`, `canonicalKey`)
//! bit-exact via `to_bits()`; every `candidateContainedInIntrinsicGap`
//! boolean; every collision-family grouping (key, member order,
//! `firstBaselineIndex`, measurements) and every standalone
//! `intrinsicCollisionFamilyKey` string, byte-exact.

use std::fs;

use irregular_nesting_native::domain::{
    CollisionGeometry, DxfGeometryEntityType, DxfGeometrySummary, ImportedPiece, IrregularBounds,
    IrregularPlacedPiece, IrregularPlacement, IrregularPoint, IrregularPolygon,
    IrregularPreparedPiece, IrregularTransform, IrregularTransformCandidate,
    IrregularTransformReason, PieceId, Rect, SourceFileId, TransformedCollisionGeometry,
};
use irregular_nesting_native::search::gap_regions::{
    candidate_contained_in_intrinsic_gap, derive_canonical_intrinsic_gap_regions,
    CanonicalIntrinsicGapRegionKind,
};
use irregular_nesting_native::search::strict_family::{
    group_intrinsic_collision_families, intrinsic_collision_family_key,
};
use serde_json::Value;

fn load_vectors() -> Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/vectors/gap-family.json");
    let raw = fs::read_to_string(path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&raw).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

fn parse_f64_bits(hex: &str) -> f64 {
    let stripped = hex
        .strip_prefix("0x")
        .unwrap_or_else(|| panic!("bit-pattern hex must start with 0x, got {hex}"));
    let bits = u64::from_str_radix(stripped, 16)
        .unwrap_or_else(|err| panic!("invalid bit-pattern hex {hex}: {err}"));
    f64::from_bits(bits)
}

fn decode_point(value: &Value) -> IrregularPoint {
    let x = parse_f64_bits(value["x"].as_str().expect("point.x present"));
    let y = parse_f64_bits(value["y"].as_str().expect("point.y present"));
    IrregularPoint::new(x, y)
}

fn decode_points(value: &Value) -> Vec<IrregularPoint> {
    value
        .as_array()
        .expect("points array present")
        .iter()
        .map(decode_point)
        .collect()
}

fn assert_points_eq(actual: &[IrregularPoint], expected: &[IrregularPoint], label: &str) {
    assert_eq!(
        actual.len(),
        expected.len(),
        "{label}: point count mismatch"
    );
    for (index, (a, e)) in actual.iter().zip(expected.iter()).enumerate() {
        assert_eq!(
            a.x.to_bits(),
            e.x.to_bits(),
            "{label} point {index}: x mismatch (rust={} ts={})",
            a.x,
            e.x
        );
        assert_eq!(
            a.y.to_bits(),
            e.y.to_bits(),
            "{label} point {index}: y mismatch (rust={} ts={})",
            a.y,
            e.y
        );
    }
}

/// Reconstructs an `IrregularPlacedPiece` from the vector file's recorded
/// `pieceId`/`points`/`translateX`/`translateY`. Every other field
/// (`rotationDeg`, the transform candidate's `index`/`reason`, `bounds`) is
/// never read by `gap_regions`'s algorithm (only `collision_geometry.polygon
/// .points` and `placement.transform.{translate_x,translate_y}` are), so
/// those are filled with arbitrary valid placeholder values here, matching
/// this crate's established convention (see `free_material_vectors.rs`'s
/// `decode_placed_piece` doc comment for the same pattern).
fn decode_placed_piece(value: &Value) -> IrregularPlacedPiece {
    let piece_id = PieceId::new(value["pieceId"].as_str().expect("pieceId present"));
    let points = decode_points(&value["points"]);
    let translate_x = parse_f64_bits(value["translateX"].as_str().expect("translateX present"));
    let translate_y = parse_f64_bits(value["translateY"].as_str().expect("translateY present"));
    let polygon = IrregularPolygon::new(points);

    IrregularPlacedPiece {
        placement: IrregularPlacement {
            piece_id: None,
            source_piece_id: piece_id.clone(),
            placement_reference: None,
            transform: IrregularTransform {
                translate_x,
                translate_y,
                rotation_deg: 0.0,
                mirrored: false,
            },
        },
        collision_geometry: TransformedCollisionGeometry {
            source_piece_id: piece_id,
            transform: IrregularTransformCandidate {
                index: 0.0,
                rotation_deg: 0.0,
                mirrored: false,
                reason: IrregularTransformReason::Configured,
            },
            polygon,
            bounds: IrregularBounds::new(0.0, 0.0, 1.0, 1.0),
        },
    }
}

fn decode_placed_pieces(value: &Value) -> Vec<IrregularPlacedPiece> {
    value
        .as_array()
        .expect("placed array present")
        .iter()
        .map(decode_placed_piece)
        .collect()
}

/// Reconstructs a `TransformedCollisionGeometry` from `movingPoints` for
/// `candidate_contained_in_intrinsic_gap`'s `moving` argument -- only
/// `polygon.points` is ever read.
fn decode_moving(points: &Value) -> TransformedCollisionGeometry {
    TransformedCollisionGeometry {
        source_piece_id: PieceId::new("moving-probe"),
        transform: IrregularTransformCandidate {
            index: 0.0,
            rotation_deg: 0.0,
            mirrored: false,
            reason: IrregularTransformReason::Configured,
        },
        polygon: IrregularPolygon::new(decode_points(points)),
        bounds: IrregularBounds::new(0.0, 0.0, 1.0, 1.0),
    }
}

/// Reconstructs an `IrregularPreparedPiece` from the vector file's recorded
/// `interchangeabilityKey`/`sourceId`/`points`. Every other field is never
/// read by `strict_family`'s production-live functions (only
/// `interchangeability_key`, `source.id`, and
/// `collision_geometry.collision_polygon.points` are), so those are filled
/// with arbitrary valid placeholder values, matching this crate's
/// established convention.
fn decode_prepared_piece(value: &Value) -> IrregularPreparedPiece {
    let source_id = PieceId::new(value["sourceId"].as_str().expect("sourceId present"));
    let interchangeability_key = value["interchangeabilityKey"]
        .as_str()
        .map(|s| s.to_string());
    let points = decode_points(&value["points"]);
    let polygon = IrregularPolygon::new(points.clone());

    IrregularPreparedPiece {
        piece_id: Some(source_id.clone()),
        interchangeability_key,
        source: ImportedPiece {
            id: source_id.clone(),
            source_file_id: SourceFileId::new("source-file"),
            source_layer: None,
            label: "vector-piece".to_string(),
            real_bounds: Rect {
                x: 0.0,
                y: 0.0,
                width: 1.0,
                height: 1.0,
            },
            geometry: DxfGeometrySummary {
                entity_type: DxfGeometryEntityType::PresetShape,
                closed: true,
                segments: vec![],
            },
            warnings: vec![],
        },
        allow_mirror: true,
        collision_geometry: CollisionGeometry {
            source_piece_id: source_id,
            source_bounds: IrregularBounds::new(0.0, 0.0, 1.0, 1.0),
            sampled_points: vec![],
            convex_hull: polygon.clone(),
            collision_polygon: polygon,
            placement_reference: IrregularPoint::new(0.0, 0.0),
            diagnostics: vec![],
        },
        transforms: vec![],
        priority_order_key: None,
    }
}

fn decode_prepared_pieces(value: &Value) -> Vec<IrregularPreparedPiece> {
    value
        .as_array()
        .expect("pieces array present")
        .iter()
        .map(decode_prepared_piece)
        .collect()
}

fn decode_kind(raw: &str) -> CanonicalIntrinsicGapRegionKind {
    match raw {
        "enclosed-cavity" => CanonicalIntrinsicGapRegionKind::EnclosedCavity,
        "hull-open-gap" => CanonicalIntrinsicGapRegionKind::HullOpenGap,
        other => panic!("unrecognized gap region kind: {other}"),
    }
}

fn decode_grid_points(value: &Value) -> Vec<IrregularPoint> {
    decode_points(value)
}

#[test]
fn derive_canonical_intrinsic_gap_regions_matches_ts_production_oracle() {
    let file = load_vectors();
    let case_count = file["gapRegionCaseCount"]
        .as_u64()
        .expect("gapRegionCaseCount header present") as usize;
    let cases = file["gapRegionCases"]
        .as_array()
        .expect("gapRegionCases present");
    assert_eq!(
        cases.len(),
        case_count,
        "gap region case count header mismatch"
    );

    for case in cases {
        let case_label = case["caseLabel"].as_str().expect("caseLabel present");
        let placed = decode_placed_pieces(&case["placed"]);
        let outcome = &case["outcome"];
        let ok = outcome["ok"].as_bool().expect("outcome.ok present");

        let actual = derive_canonical_intrinsic_gap_regions(&placed);

        if !ok {
            assert!(
                actual.is_none(),
                "case {case_label}: expected None, got Some({} regions)",
                actual.map(|r| r.len()).unwrap_or(0)
            );
            continue;
        }

        let actual_regions =
            actual.unwrap_or_else(|| panic!("case {case_label}: expected Some(regions), got None"));
        let expected_regions = outcome["regions"]
            .as_array()
            .expect("outcome.regions present");
        assert_eq!(
            actual_regions.len(),
            expected_regions.len(),
            "case {case_label}: region count mismatch"
        );

        for (index, (actual_region, expected_region)) in actual_regions
            .iter()
            .zip(expected_regions.iter())
            .enumerate()
        {
            let label = format!("{case_label} region {index}");
            let expected_kind = decode_kind(
                expected_region["kind"]
                    .as_str()
                    .expect("region.kind present"),
            );
            assert_eq!(actual_region.kind, expected_kind, "{label}: kind mismatch");

            let actual_boundary: Vec<IrregularPoint> = actual_region
                .boundary
                .iter()
                .map(|p| IrregularPoint::new(p.x, p.y))
                .collect();
            assert_points_eq(
                &actual_boundary,
                &decode_grid_points(&expected_region["boundary"]),
                &format!("{label} boundary"),
            );

            let expected_holes = expected_region["holes"]
                .as_array()
                .expect("region.holes present");
            assert_eq!(
                actual_region.holes.len(),
                expected_holes.len(),
                "{label}: hole count mismatch"
            );
            for (hole_index, (actual_hole, expected_hole)) in actual_region
                .holes
                .iter()
                .zip(expected_holes.iter())
                .enumerate()
            {
                let actual_hole_points: Vec<IrregularPoint> = actual_hole
                    .iter()
                    .map(|p| IrregularPoint::new(p.x, p.y))
                    .collect();
                assert_points_eq(
                    &actual_hole_points,
                    &decode_grid_points(expected_hole),
                    &format!("{label} hole {hole_index}"),
                );
            }

            let expected_area_mm2 = parse_f64_bits(
                expected_region["areaMm2"]
                    .as_str()
                    .expect("areaMm2 present"),
            );
            assert_eq!(
                actual_region.area_mm2.to_bits(),
                expected_area_mm2.to_bits(),
                "{label}: areaMm2 mismatch (rust={} ts={})",
                actual_region.area_mm2,
                expected_area_mm2
            );

            let expected_doubled_area_grid2 = expected_region["doubledAreaGrid2"]
                .as_str()
                .expect("doubledAreaGrid2 present");
            assert_eq!(
                actual_region.doubled_area_grid2, expected_doubled_area_grid2,
                "{label}: doubledAreaGrid2 mismatch"
            );

            let expected_aabb = &expected_region["aabb"];
            let expected_min_x =
                parse_f64_bits(expected_aabb["minX"].as_str().expect("aabb.minX present"));
            let expected_min_y =
                parse_f64_bits(expected_aabb["minY"].as_str().expect("aabb.minY present"));
            let expected_max_x =
                parse_f64_bits(expected_aabb["maxX"].as_str().expect("aabb.maxX present"));
            let expected_max_y =
                parse_f64_bits(expected_aabb["maxY"].as_str().expect("aabb.maxY present"));
            assert_eq!(
                actual_region.aabb.min_x.to_bits(),
                expected_min_x.to_bits(),
                "{label}: aabb.minX mismatch"
            );
            assert_eq!(
                actual_region.aabb.min_y.to_bits(),
                expected_min_y.to_bits(),
                "{label}: aabb.minY mismatch"
            );
            assert_eq!(
                actual_region.aabb.max_x.to_bits(),
                expected_max_x.to_bits(),
                "{label}: aabb.maxX mismatch"
            );
            assert_eq!(
                actual_region.aabb.max_y.to_bits(),
                expected_max_y.to_bits(),
                "{label}: aabb.maxY mismatch"
            );

            let expected_canonical_key = expected_region["canonicalKey"]
                .as_str()
                .expect("canonicalKey present");
            assert_eq!(
                actual_region.canonical_key, expected_canonical_key,
                "{label}: canonicalKey mismatch"
            );
        }
    }
}

#[test]
fn candidate_contained_in_intrinsic_gap_matches_ts_production_oracle() {
    let file = load_vectors();
    let case_count = file["containmentCaseCount"]
        .as_u64()
        .expect("containmentCaseCount header present") as usize;
    let cases = file["containmentCases"]
        .as_array()
        .expect("containmentCases present");
    assert_eq!(
        cases.len(),
        case_count,
        "containment case count header mismatch"
    );

    let mut true_checked = 0usize;
    let mut false_checked = 0usize;

    for case in cases {
        let case_label = case["caseLabel"].as_str().expect("caseLabel present");
        let placed = decode_placed_pieces(&case["placed"]);
        let region_index = case["regionIndex"].as_u64().expect("regionIndex present") as usize;
        let moving = decode_moving(&case["movingPoints"]);
        let anchor = decode_point(&case["anchor"]);
        let expected = case["expected"].as_bool().expect("expected present");

        let regions = derive_canonical_intrinsic_gap_regions(&placed)
            .unwrap_or_else(|| panic!("case {case_label}: expected Some(regions)"));
        let region = regions.get(region_index).unwrap_or_else(|| {
            panic!("case {case_label}: regionIndex {region_index} out of range")
        });

        let actual = candidate_contained_in_intrinsic_gap(&moving, anchor, region);
        assert_eq!(
            actual, expected,
            "case {case_label}: containment mismatch (rust={actual} ts={expected})"
        );

        if expected {
            true_checked += 1;
        } else {
            false_checked += 1;
        }
    }

    assert!(
        true_checked >= 10,
        "expected several true containment cases, got {true_checked}"
    );
    assert!(
        false_checked >= 100,
        "expected many false containment cases, got {false_checked}"
    );
}

#[test]
fn intrinsic_collision_family_key_matches_ts_production_oracle() {
    let file = load_vectors();
    let case_count = file["familyKeyCaseCount"]
        .as_u64()
        .expect("familyKeyCaseCount header present") as usize;
    let cases = file["familyKeyCases"]
        .as_array()
        .expect("familyKeyCases present");
    assert_eq!(
        cases.len(),
        case_count,
        "family key case count header mismatch"
    );

    for case in cases {
        let case_label = case["caseLabel"].as_str().expect("caseLabel present");
        let piece = decode_prepared_piece(&case["piece"]);
        let expected_key = case["key"].as_str().expect("key present");

        let actual_key = intrinsic_collision_family_key(&piece);
        assert_eq!(
            actual_key, expected_key,
            "case {case_label}: family key mismatch"
        );
    }
}

#[test]
fn group_intrinsic_collision_families_matches_ts_production_oracle() {
    let file = load_vectors();
    let case_count = file["familyGroupCaseCount"]
        .as_u64()
        .expect("familyGroupCaseCount header present") as usize;
    let cases = file["familyGroupCases"]
        .as_array()
        .expect("familyGroupCases present");
    assert_eq!(
        cases.len(),
        case_count,
        "family group case count header mismatch"
    );

    let mut largest_case_family_count = 0usize;

    for case in cases {
        let case_label = case["caseLabel"].as_str().expect("caseLabel present");
        let pieces = decode_prepared_pieces(&case["pieces"]);
        let expected_families = case["families"].as_array().expect("families present");

        let actual_families = group_intrinsic_collision_families(&pieces);
        largest_case_family_count = largest_case_family_count.max(actual_families.len());
        assert_eq!(
            actual_families.len(),
            expected_families.len(),
            "case {case_label}: family count mismatch"
        );

        for (index, (actual_family, expected_family)) in actual_families
            .iter()
            .zip(expected_families.iter())
            .enumerate()
        {
            let label = format!("{case_label} family {index}");
            let expected_key = expected_family["key"].as_str().expect("family.key present");
            assert_eq!(actual_family.key, expected_key, "{label}: key mismatch");

            let expected_member_ids: Vec<&str> = expected_family["memberSourceIds"]
                .as_array()
                .expect("memberSourceIds present")
                .iter()
                .map(|v| v.as_str().expect("memberSourceIds entries are strings"))
                .collect();
            let actual_member_ids: Vec<&str> = actual_family
                .members
                .iter()
                .map(|member| member.source.id.as_str())
                .collect();
            assert_eq!(
                actual_member_ids, expected_member_ids,
                "{label}: member order/identity mismatch"
            );

            let expected_first_baseline_index = expected_family["firstBaselineIndex"]
                .as_f64()
                .expect("firstBaselineIndex present");
            assert_eq!(
                actual_family.first_baseline_index, expected_first_baseline_index,
                "{label}: firstBaselineIndex mismatch"
            );

            let expected_collision_area_mm2 = parse_f64_bits(
                expected_family["collisionAreaMm2"]
                    .as_str()
                    .expect("collisionAreaMm2 present"),
            );
            assert_eq!(
                actual_family.collision_area_mm2.to_bits(),
                expected_collision_area_mm2.to_bits(),
                "{label}: collisionAreaMm2 mismatch"
            );

            let expected_maximum_side_mm = parse_f64_bits(
                expected_family["maximumSideMm"]
                    .as_str()
                    .expect("maximumSideMm present"),
            );
            assert_eq!(
                actual_family.maximum_side_mm.to_bits(),
                expected_maximum_side_mm.to_bits(),
                "{label}: maximumSideMm mismatch"
            );

            let expected_aspect_ratio = parse_f64_bits(
                expected_family["aspectRatio"]
                    .as_str()
                    .expect("aspectRatio present"),
            );
            assert_eq!(
                actual_family.aspect_ratio.to_bits(),
                expected_aspect_ratio.to_bits(),
                "{label}: aspectRatio mismatch"
            );
        }
    }

    assert!(
        largest_case_family_count >= 10,
        "expected at least one case with many families (the full mixed61 layout), got max {largest_case_family_count}"
    );
}

#[test]
fn total_vector_count_meets_the_task_spec_floor() {
    let file = load_vectors();
    let total = file["totalVectorCount"]
        .as_u64()
        .expect("totalVectorCount header present");
    assert!(
        total >= 350,
        "expected >= 350 gap-family vectors per the task spec, got {total}"
    );
    let generating_commit = file["generatingCommit"]
        .as_str()
        .expect("generatingCommit header present");
    assert!(
        !generating_commit.is_empty(),
        "vectors file must record its generating commit (ruling R14)"
    );
}
