//! Differential-vector test for `geometry::hash` (ruling R14).
//!
//! Loads `tests/vectors/hash.json`, generated by
//! `scripts/rust-parity/dump-predicates.ts` from Node's real
//! `crypto.createHash('sha256').update(input).digest('hex')` -- the exact
//! primitive every `src/workers/algorithm/irregular/*.ts` identity-hash call
//! site uses -- and asserts this crate's `geometry::hash::sha256_hex`
//! reproduces every recorded digest byte-for-byte.

use irregular_nesting_native::geometry::hash::sha256_hex;
use serde::Deserialize;
use std::fs;
use std::path::Path;

// Only the fields this test actually reads are declared; serde ignores the
// vector file's other header fields (`generatedByScript`, `sourcePrimitive`,
// `description`) by default.
#[derive(Deserialize)]
struct VectorFile {
    #[serde(rename = "generatingCommit")]
    generating_commit: String,
    #[serde(rename = "caseCount")]
    case_count: usize,
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Case {
    category: String,
    input: String,
    #[serde(rename = "sha256Hex")]
    sha256_hex: String,
}

fn load_vectors() -> VectorFile {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/vectors/hash.json");
    let raw = fs::read_to_string(&path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display()));
    serde_json::from_str(&raw).unwrap_or_else(|err| panic!("malformed hash.json: {err}"))
}

#[test]
fn sha256_hex_matches_node_crypto_oracle() {
    let file = load_vectors();

    assert!(
        !file.generating_commit.is_empty(),
        "vectors file must record its generating commit (ruling R14)"
    );
    assert_eq!(
        file.cases.len(),
        file.case_count,
        "caseCount header must match the actual number of cases"
    );
    assert!(
        file.cases.len() >= 15,
        "expected a representative spread of sha256 vectors, got {}",
        file.cases.len()
    );

    for case in &file.cases {
        assert_eq!(
            case.sha256_hex.len(),
            64,
            "category={} digest must be 64 hex chars",
            case.category
        );
        assert!(
            case.sha256_hex
                .chars()
                .all(|c| c.is_ascii_hexdigit() && !c.is_ascii_uppercase()),
            "category={} digest must be lowercase hex",
            case.category
        );

        let actual = sha256_hex(&case.input);
        assert_eq!(
            actual,
            case.sha256_hex,
            "category={} sha256_hex(input) mismatch for input of length {}",
            case.category,
            case.input.len()
        );
    }
}
