//! Bit-exact Node/V8 `Math.hypot` parity vectors.
//!
//! The committed corpus is generated by
//! `scripts/rust-parity/dump-js-hypot.ts`. Finite and infinite results compare
//! by raw binary64 bits. NaN payloads compare by classification because their
//! payload bits are not portable across runtimes.

use irregular_nesting_native::js_number::js_math::hypot;
use serde::Deserialize;

const VECTORS_JSON: &str = include_str!("vectors/js-hypot.json");

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Meta {
    area: String,
    node_version: String,
    v8_version: String,
    seed: u32,
    source_sha256: String,
    corpus_sha256: String,
    vector_count: usize,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct HypotVector {
    x_bits: String,
    y_bits: String,
    expected_bits: String,
    #[serde(rename = "expectedIsNaN")]
    expected_is_nan: bool,
}

#[derive(Deserialize)]
struct VectorFile {
    meta: Meta,
    cases: Vec<HypotVector>,
}

fn bits(hex: &str) -> u64 {
    u64::from_str_radix(hex, 16)
        .unwrap_or_else(|error| panic!("invalid binary64 bit pattern {hex:?}: {error}"))
}

#[test]
fn custom_hypot_matches_committed_node_v8_oracle() {
    let file: VectorFile =
        serde_json::from_str(VECTORS_JSON).expect("tests/vectors/js-hypot.json must parse");

    assert_eq!(file.meta.area, "js-hypot");
    assert!(file.meta.node_version.starts_with('v'));
    assert!(!file.meta.v8_version.is_empty());
    assert_eq!(file.meta.seed, 0x5eed_c0de);
    assert_eq!(file.meta.source_sha256.len(), 64);
    assert_eq!(file.meta.corpus_sha256.len(), 64);
    assert_eq!(file.meta.vector_count, 21_696);
    assert_eq!(file.cases.len(), 21_696);

    for (index, vector) in file.cases.iter().enumerate() {
        let x = f64::from_bits(bits(&vector.x_bits));
        let y = f64::from_bits(bits(&vector.y_bits));
        let actual = hypot(x, y);
        if vector.expected_is_nan {
            assert!(
                actual.is_nan(),
                "case {index}: expected NaN, got {actual:?}"
            );
        } else {
            assert_eq!(
                actual.to_bits(),
                bits(&vector.expected_bits),
                "case {index}: hypot({x:?}, {y:?}) produced {actual:?}"
            );
        }
    }
}
