//! Differential-vector test for
//! `crates/irregular-nesting-native/src/search/strict_decoder.rs`.
//!
//! Loads `tests/vectors/strict-decoder.json`, generated by
//! `scripts/rust-parity/dump-strict-decoder.ts` from the REAL production
//! `constructIntrinsicStrictState`/`finalizeIntrinsicStrictState`/
//! `evaluateIntrinsicStrictCertificate`/`measureIntrinsicSheetlessCompletedLayout`/
//! `rankIntrinsicStrictCompletedLayouts`/`selectIntrinsicStrictCompletedParetoFront`/
//! `compareIntrinsicStrictCompletedLayoutDominance`/`intrinsicStrictCompletedLayoutDominates`/
//! `transformCandidateOrder`/`canonicalLinearMetric`/`canonicalAreaMetric`/
//! `measureIntrinsicStrictCanonicalEnvelope`
//! (`src/workers/algorithm/irregular/intrinsicStrictDecoder.ts`), and
//! asserts this crate's Rust port reproduces every recorded outcome exactly:
//! full decode runs (status, terminal hash, every metrics/certificate field,
//! every placement transform, `stepTrace`, `candidateEvaluationCount`,
//! `runtimeMs`) bit-exact via `to_bits()`; checkpoint round-trips (the
//! first-stage checkpoint's own hash-bearing scalar fields, byte-exact, plus
//! the resumed second stage reaching the recorded uninterrupted-run ground
//! truth); deterministic candidate-evaluation-cap truncation; deterministic
//! `timingNow`-seam deadline aborts; and Pareto/ranking peeling order.
//!
//! Per this crate's file-ownership convention (see `gap_family_vectors.rs`'s
//! own `decode_prepared_piece` doc comment), placeholder domain fields this
//! cluster's algorithm never reads (`source.realBounds`,
//! `collisionGeometry.diagnostics`, etc.) are filled with arbitrary valid
//! values, not reconstructed from the vector file.

use std::fs;
use std::sync::Arc;

use irregular_nesting_native::caches::GeometryCacheStore;
use irregular_nesting_native::domain::{
    CollisionGeometry, DxfGeometryEntityType, DxfGeometrySummary, ImportedPiece, IrregularBounds,
    IrregularNestingSettings, IrregularPlacedPiece, IrregularPlacement, IrregularPoint,
    IrregularPolygon, IrregularPreparedPiece, IrregularTransform, IrregularTransformCandidate,
    IrregularTransformReason, PieceId, Rect, SheetSpec, SourceFileId,
};
use irregular_nesting_native::nfp_ifp::NfpIfpAbortReason;
use irregular_nesting_native::search::beam_state::TimingNowFn;
use irregular_nesting_native::search::strict_decoder::{
    canonical_area_metric, canonical_linear_metric,
    compare_intrinsic_strict_completed_layout_dominance, construct_intrinsic_strict_state,
    finalize_intrinsic_strict_state, intrinsic_strict_completed_layout_dominates,
    measure_intrinsic_sheetless_completed_layout, measure_intrinsic_strict_canonical_envelope,
    rank_intrinsic_strict_completed_layouts, select_intrinsic_strict_completed_pareto_front,
    transform_candidate_order, ConstructIntrinsicStrictStateInput, IntrinsicStrictCandidateMode,
    IntrinsicStrictCohesionFloor, IntrinsicStrictComparatorMode, IntrinsicStrictCompletedMetrics,
    IntrinsicStrictCompletedMetricsExact, IntrinsicStrictDecodeStatus,
    IntrinsicStrictDecoderFailure, PauseReason, TerminalRotationDeg, TruncationReason,
};
use serde_json::Value;
use std::cmp::Ordering;

fn load_vectors() -> Value {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/vectors/strict-decoder.json"
    );
    let raw = fs::read_to_string(path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&raw).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

fn parse_f64_bits(hex: &str) -> f64 {
    let stripped = hex
        .strip_prefix("0x")
        .unwrap_or_else(|| panic!("bit-pattern hex must start with 0x, got {hex}"));
    let bits = u64::from_str_radix(stripped, 16)
        .unwrap_or_else(|err| panic!("invalid bit-pattern hex {hex}: {err}"));
    f64::from_bits(bits)
}

fn get_f64(value: &Value, field: &str) -> f64 {
    parse_f64_bits(
        value[field]
            .as_str()
            .unwrap_or_else(|| panic!("{field} present")),
    )
}

fn get_str<'a>(value: &'a Value, field: &str) -> &'a str {
    value[field]
        .as_str()
        .unwrap_or_else(|| panic!("{field} present"))
}

fn assert_f64_bits_eq(actual: f64, expected_hex: &str, label: &str) {
    let expected = parse_f64_bits(expected_hex);
    assert_eq!(
        actual.to_bits(),
        expected.to_bits(),
        "{label}: mismatch (rust={actual}, ts={expected})"
    );
}

fn assert_opt_f64_bits_eq(actual: Option<f64>, expected: &Value, label: &str) {
    match expected {
        Value::Null => assert!(actual.is_none(), "{label}: expected None, got {actual:?}"),
        Value::String(hex) => {
            let actual = actual.unwrap_or_else(|| panic!("{label}: expected Some, got None"));
            assert_f64_bits_eq(actual, hex, label);
        }
        other => panic!("{label}: unexpected JSON shape {other:?}"),
    }
}

// ---------------------------------------------------------------------------
// Domain-object construction helpers (mirror `gap_family_vectors.rs`'s own
// `decode_prepared_piece` and `dump-strict-decoder.ts`'s TS-side helpers).
// ---------------------------------------------------------------------------
fn decode_point(value: &Value) -> IrregularPoint {
    IrregularPoint::new(get_f64(value, "x"), get_f64(value, "y"))
}

fn decode_points(value: &Value) -> Vec<IrregularPoint> {
    value
        .as_array()
        .expect("points array present")
        .iter()
        .map(decode_point)
        .collect()
}

fn bounds_of(points: &[IrregularPoint]) -> IrregularBounds {
    let min_x = points.iter().map(|p| p.x).fold(f64::INFINITY, f64::min);
    let min_y = points.iter().map(|p| p.y).fold(f64::INFINITY, f64::min);
    let max_x = points.iter().map(|p| p.x).fold(f64::NEG_INFINITY, f64::max);
    let max_y = points.iter().map(|p| p.y).fold(f64::NEG_INFINITY, f64::max);
    IrregularBounds::new(min_x, min_y, max_x, max_y)
}

fn decode_reason(raw: &str) -> IrregularTransformReason {
    match raw {
        "orthogonal" => IrregularTransformReason::Orthogonal,
        "edge_alignment" => IrregularTransformReason::EdgeAlignment,
        "configured" => IrregularTransformReason::Configured,
        other => panic!("unrecognized transform reason: {other}"),
    }
}

fn decode_transform_candidate(value: &Value) -> IrregularTransformCandidate {
    IrregularTransformCandidate {
        index: get_f64(value, "index"),
        rotation_deg: get_f64(value, "rotationDeg"),
        mirrored: value["mirrored"].as_bool().expect("mirrored present"),
        reason: decode_reason(get_str(value, "reason")),
    }
}

fn decode_transforms(value: &Value) -> Vec<IrregularTransformCandidate> {
    value
        .as_array()
        .expect("transforms array present")
        .iter()
        .map(decode_transform_candidate)
        .collect()
}

/// Reconstructs an `IrregularPreparedPiece` from the vector file's recorded
/// `pieceId`/`points`/`transforms`. Every other field is never read by this
/// cluster's own algorithm (only `collision_geometry.collision_polygon
/// .points` and `transforms` are, via `transformCollisionGeometry`/the
/// sorted-transform loop), so those are filled with arbitrary valid
/// placeholder values.
fn decode_prepared_piece(value: &Value) -> IrregularPreparedPiece {
    let piece_id = PieceId::new(get_str(value, "pieceId"));
    let points = decode_points(&value["points"]);
    let transforms = decode_transforms(&value["transforms"]);
    let polygon = IrregularPolygon::new(points.clone());
    let bounds = bounds_of(&points);

    IrregularPreparedPiece {
        piece_id: Some(piece_id.clone()),
        interchangeability_key: None,
        source: ImportedPiece {
            id: piece_id.clone(),
            source_file_id: SourceFileId::new("source-file"),
            source_layer: None,
            label: "vector-piece".to_string(),
            real_bounds: Rect {
                x: 0.0,
                y: 0.0,
                width: 1.0,
                height: 1.0,
            },
            geometry: DxfGeometrySummary {
                entity_type: DxfGeometryEntityType::PresetShape,
                closed: true,
                segments: vec![],
            },
            warnings: vec![],
        },
        allow_mirror: true,
        collision_geometry: CollisionGeometry {
            source_piece_id: piece_id,
            source_bounds: bounds,
            sampled_points: points,
            convex_hull: polygon.clone(),
            collision_polygon: polygon,
            placement_reference: IrregularPoint::new(0.0, 0.0),
            diagnostics: vec![],
        },
        transforms,
        priority_order_key: None,
    }
}

fn decode_prepared_pieces(value: &Value) -> Vec<Arc<IrregularPreparedPiece>> {
    value
        .as_array()
        .expect("pieces array present")
        .iter()
        .map(|piece| Arc::new(decode_prepared_piece(piece)))
        .collect()
}

/// Reconstructs an `IrregularPlacedPiece` for `measureIntrinsicStrictCanonicalEnvelope`
/// vectors: local `collision_geometry.polygon.points` plus
/// `placement.transform.{translate_x,translate_y}` are the only fields that
/// function reads (via `measureCanonicalLayoutEnvelope`).
fn decode_envelope_placed_piece(
    points: &Value,
    translate_x: f64,
    translate_y: f64,
) -> IrregularPlacedPiece {
    let piece_id = PieceId::new("envelope-probe");
    let decoded_points = decode_points(points);
    let bounds = if decoded_points.is_empty() {
        IrregularBounds::new(0.0, 0.0, 1.0, 1.0)
    } else {
        bounds_of(&decoded_points)
    };
    let polygon = IrregularPolygon::new(decoded_points);
    IrregularPlacedPiece {
        placement: IrregularPlacement {
            piece_id: None,
            source_piece_id: piece_id.clone(),
            placement_reference: None,
            transform: IrregularTransform {
                translate_x,
                translate_y,
                rotation_deg: 0.0,
                mirrored: false,
            },
        },
        collision_geometry: irregular_nesting_native::domain::TransformedCollisionGeometry {
            source_piece_id: piece_id,
            transform: IrregularTransformCandidate {
                index: 0.0,
                rotation_deg: 0.0,
                mirrored: false,
                reason: IrregularTransformReason::Configured,
            },
            polygon,
            bounds,
        },
    }
}

fn settings(vectors: &Value) -> IrregularNestingSettings {
    serde_json::from_value(vectors["settings"].clone())
        .unwrap_or_else(|err| panic!("failed to deserialize settings: {err}"))
}

/// Fresh incrementing clock seam matching `dump-strict-decoder.ts`'s
/// `makeClock()` exactly: starts at `1000`, advances by `1` on every call.
fn make_clock() -> impl Fn() -> f64 {
    let counter = std::cell::Cell::new(1000.0_f64);
    move || {
        let next = counter.get() + 1.0;
        counter.set(next);
        next
    }
}

fn candidate_mode_from_label(label: &str) -> IntrinsicStrictCandidateMode {
    match label {
        "pure-growth" => {
            IntrinsicStrictCandidateMode::Comparator(IntrinsicStrictComparatorMode::PureGrowth)
        }
        "legacy-absolute-envelope" => IntrinsicStrictCandidateMode::Comparator(
            IntrinsicStrictComparatorMode::LegacyAbsoluteEnvelope,
        ),
        "contact-band" => {
            IntrinsicStrictCandidateMode::Comparator(IntrinsicStrictComparatorMode::ContactBand)
        }
        "gap-contained" => IntrinsicStrictCandidateMode::GapContained,
        other => panic!("unrecognized candidate mode: {other}"),
    }
}

// ---------------------------------------------------------------------------
// Metrics/certificate/step-trace assertion helpers.
// ---------------------------------------------------------------------------
fn assert_metrics_exact_eq(
    actual: Option<&IntrinsicStrictCompletedMetricsExact>,
    expected: &Value,
    label: &str,
) {
    if expected.is_null() {
        assert!(
            actual.is_none(),
            "{label}.exact: expected None, got {actual:?}"
        );
        return;
    }
    let actual = actual.unwrap_or_else(|| panic!("{label}.exact: expected Some, got None"));
    assert_f64_bits_eq(
        actual.envelope_maximum_side_grid,
        get_str(expected, "envelopeMaximumSideGrid"),
        &format!("{label}.exact.envelopeMaximumSideGrid"),
    );
    assert_eq!(
        actual.envelope_area_grid2,
        get_str(expected, "envelopeAreaGrid2"),
        "{label}.exact.envelopeAreaGrid2"
    );
    assert_f64_bits_eq(
        actual.envelope_span_grid,
        get_str(expected, "envelopeSpanGrid"),
        &format!("{label}.exact.envelopeSpanGrid"),
    );
    assert_eq!(
        actual.total_enclosed_cavity_doubled_area_grid2,
        get_str(expected, "totalEnclosedCavityDoubledAreaGrid2"),
        "{label}.exact.totalEnclosedCavityDoubledAreaGrid2"
    );
    assert_eq!(
        actual.largest_occupied_hull_gap_doubled_area_grid2,
        get_str(expected, "largestOccupiedHullGapDoubledAreaGrid2"),
        "{label}.exact.largestOccupiedHullGapDoubledAreaGrid2"
    );
    assert_eq!(
        actual.occupied_hull_doubled_area_grid2,
        get_str(expected, "occupiedHullDoubledAreaGrid2"),
        "{label}.exact.occupiedHullDoubledAreaGrid2"
    );
    assert_eq!(
        actual.occupied_hull_waste_doubled_area_grid2,
        get_str(expected, "occupiedHullWasteDoubledAreaGrid2"),
        "{label}.exact.occupiedHullWasteDoubledAreaGrid2"
    );
    assert_f64_bits_eq(
        actual.largest_positive_contact_component_size,
        get_str(expected, "largestPositiveContactComponentSize"),
        &format!("{label}.exact.largestPositiveContactComponentSize"),
    );
    assert_f64_bits_eq(
        actual.placed_piece_count,
        get_str(expected, "placedPieceCount"),
        &format!("{label}.exact.placedPieceCount"),
    );
    assert_eq!(
        actual.occupied_outside_largest_contact_component_doubled_area_grid2,
        get_str(
            expected,
            "occupiedOutsideLargestContactComponentDoubledAreaGrid2"
        ),
        "{label}.exact.occupiedOutsideLargestContactComponentDoubledAreaGrid2"
    );
}

fn assert_metrics_eq(
    actual: Option<&IntrinsicStrictCompletedMetrics>,
    expected: &Value,
    label: &str,
) {
    if expected.is_null() {
        assert!(actual.is_none(), "{label}: expected None, got {actual:?}");
        return;
    }
    let actual = actual.unwrap_or_else(|| panic!("{label}: expected Some, got None"));
    assert_f64_bits_eq(
        actual.envelope_maximum_side_mm,
        get_str(expected, "envelopeMaximumSideMm"),
        &format!("{label}.envelopeMaximumSideMm"),
    );
    assert_f64_bits_eq(
        actual.envelope_area_mm2,
        get_str(expected, "envelopeAreaMm2"),
        &format!("{label}.envelopeAreaMm2"),
    );
    assert_f64_bits_eq(
        actual.envelope_span_mm,
        get_str(expected, "envelopeSpanMm"),
        &format!("{label}.envelopeSpanMm"),
    );
    assert_f64_bits_eq(
        actual.enclosed_cavity_count,
        get_str(expected, "enclosedCavityCount"),
        &format!("{label}.enclosedCavityCount"),
    );
    assert_f64_bits_eq(
        actual.total_enclosed_cavity_area_mm2,
        get_str(expected, "totalEnclosedCavityAreaMm2"),
        &format!("{label}.totalEnclosedCavityAreaMm2"),
    );
    assert_f64_bits_eq(
        actual.largest_occupied_hull_gap_ratio,
        get_str(expected, "largestOccupiedHullGapRatio"),
        &format!("{label}.largestOccupiedHullGapRatio"),
    );
    assert_f64_bits_eq(
        actual.isolated_piece_count,
        get_str(expected, "isolatedPieceCount"),
        &format!("{label}.isolatedPieceCount"),
    );
    assert_f64_bits_eq(
        actual.positive_contact_component_count,
        get_str(expected, "positiveContactComponentCount"),
        &format!("{label}.positiveContactComponentCount"),
    );
    assert_f64_bits_eq(
        actual.largest_positive_contact_component_size,
        get_str(expected, "largestPositiveContactComponentSize"),
        &format!("{label}.largestPositiveContactComponentSize"),
    );
    assert_f64_bits_eq(
        actual.largest_positive_contact_component_ratio,
        get_str(expected, "largestPositiveContactComponentRatio"),
        &format!("{label}.largestPositiveContactComponentRatio"),
    );
    assert_f64_bits_eq(
        actual.occupied_area_outside_largest_contact_component_mm2,
        get_str(expected, "occupiedAreaOutsideLargestContactComponentMm2"),
        &format!("{label}.occupiedAreaOutsideLargestContactComponentMm2"),
    );
    assert_f64_bits_eq(
        actual.occupied_hull_waste_ratio,
        get_str(expected, "occupiedHullWasteRatio"),
        &format!("{label}.occupiedHullWasteRatio"),
    );
    assert_f64_bits_eq(
        actual.total_structural_contacts,
        get_str(expected, "totalStructuralContacts"),
        &format!("{label}.totalStructuralContacts"),
    );
    assert_f64_bits_eq(
        actual.dominant_structural_contacts,
        get_str(expected, "dominantStructuralContacts"),
        &format!("{label}.dominantStructuralContacts"),
    );
    assert_f64_bits_eq(
        actual.contact_units,
        get_str(expected, "contactUnits"),
        &format!("{label}.contactUnits"),
    );
    assert_f64_bits_eq(
        actual.shared_boundary_length_mm,
        get_str(expected, "sharedBoundaryLengthMm"),
        &format!("{label}.sharedBoundaryLengthMm"),
    );
    assert_eq!(
        actual.canonical_geometry_hash,
        get_str(expected, "canonicalGeometryHash"),
        "{label}.canonicalGeometryHash"
    );
    assert_f64_bits_eq(
        actual.runtime_ms,
        get_str(expected, "runtimeMs"),
        &format!("{label}.runtimeMs"),
    );
    assert_metrics_exact_eq(actual.exact.as_ref(), &expected["exact"], label);
}

fn assert_certificate_eq(
    actual: Option<&irregular_nesting_native::search::strict_decoder::IntrinsicStrictCertificate>,
    expected: &Value,
    label: &str,
) {
    if expected.is_null() {
        assert!(actual.is_none(), "{label}: expected None, got {actual:?}");
        return;
    }
    let actual = actual.unwrap_or_else(|| panic!("{label}: expected Some, got None"));
    assert_eq!(
        actual.passes,
        expected["passes"].as_bool().expect("passes present"),
        "{label}.passes"
    );
    let expected_floors: Vec<IntrinsicStrictCohesionFloor> = expected["violatedFloors"]
        .as_array()
        .expect("violatedFloors present")
        .iter()
        .map(|v| serde_json::from_value(v.clone()).expect("valid cohesion floor"))
        .collect();
    assert_eq!(
        actual.violated_floors, expected_floors,
        "{label}.violatedFloors"
    );
    assert_f64_bits_eq(
        actual.relative_deficit_sum,
        get_str(expected, "relativeDeficitSum"),
        &format!("{label}.relativeDeficitSum"),
    );
    match &expected["exactRelativeDeficitNumerator"] {
        Value::Null => assert!(
            actual.exact_relative_deficit_numerator.is_none(),
            "{label}.exactRelativeDeficitNumerator: expected None"
        ),
        Value::String(s) => assert_eq!(
            actual.exact_relative_deficit_numerator.as_deref(),
            Some(s.as_str()),
            "{label}.exactRelativeDeficitNumerator"
        ),
        other => panic!("unexpected shape {other:?}"),
    }
    match &expected["exactRelativeDeficitDenominator"] {
        Value::Null => assert!(
            actual.exact_relative_deficit_denominator.is_none(),
            "{label}.exactRelativeDeficitDenominator: expected None"
        ),
        Value::String(s) => assert_eq!(
            actual.exact_relative_deficit_denominator.as_deref(),
            Some(s.as_str()),
            "{label}.exactRelativeDeficitDenominator"
        ),
        other => panic!("unexpected shape {other:?}"),
    }
}

fn assert_placements_eq(actual: &[IrregularPlacement], expected: &Value, label: &str) {
    let expected = expected.as_array().expect("placements array present");
    assert_eq!(
        actual.len(),
        expected.len(),
        "{label}: placement count mismatch"
    );
    for (index, (a, e)) in actual.iter().zip(expected.iter()).enumerate() {
        let entry_label = format!("{label}[{index}]");
        assert_eq!(
            a.source_piece_id.as_str(),
            get_str(e, "pieceId"),
            "{entry_label}.pieceId"
        );
        assert_f64_bits_eq(
            a.transform.translate_x,
            get_str(e, "translateX"),
            &format!("{entry_label}.translateX"),
        );
        assert_f64_bits_eq(
            a.transform.translate_y,
            get_str(e, "translateY"),
            &format!("{entry_label}.translateY"),
        );
        assert_f64_bits_eq(
            a.transform.rotation_deg,
            get_str(e, "rotationDeg"),
            &format!("{entry_label}.rotationDeg"),
        );
        assert_eq!(
            a.transform.mirrored,
            e["mirrored"].as_bool().expect("mirrored present"),
            "{entry_label}.mirrored"
        );
    }
}

fn assert_step_trace_eq(
    actual: &[irregular_nesting_native::search::strict_decoder::IntrinsicStrictStepTrace],
    expected: &Value,
    label: &str,
) {
    let expected = expected.as_array().expect("stepTrace array present");
    assert_eq!(
        actual.len(),
        expected.len(),
        "{label}: stepTrace length mismatch"
    );
    for (index, (a, e)) in actual.iter().zip(expected.iter()).enumerate() {
        let entry_label = format!("{label}[{index}]");
        assert_eq!(
            a.piece_id.as_str(),
            get_str(e, "pieceId"),
            "{entry_label}.pieceId"
        );
        assert_f64_bits_eq(
            a.candidate_count,
            get_str(e, "candidateCount"),
            &format!("{entry_label}.candidateCount"),
        );
        assert_f64_bits_eq(
            a.transform_family_count,
            get_str(e, "transformFamilyCount"),
            &format!("{entry_label}.transformFamilyCount"),
        );
        match &e["selectedTransformFamily"] {
            Value::Null => assert!(
                a.selected_transform_family.is_none(),
                "{entry_label}.selectedTransformFamily: expected None"
            ),
            Value::String(s) => assert_eq!(
                a.selected_transform_family.as_deref(),
                Some(s.as_str()),
                "{entry_label}.selectedTransformFamily"
            ),
            other => panic!("unexpected shape {other:?}"),
        }
        match (&a.selected_score, &e["selectedScore"]) {
            (None, Value::Null) => {}
            (Some(score), score_json) if !score_json.is_null() => {
                assert_f64_bits_eq(
                    score.maximum_side_mm,
                    get_str(score_json, "maximumSideMm"),
                    &format!("{entry_label}.selectedScore.maximumSideMm"),
                );
                assert_f64_bits_eq(
                    score.envelope_area_mm2,
                    get_str(score_json, "envelopeAreaMm2"),
                    &format!("{entry_label}.selectedScore.envelopeAreaMm2"),
                );
                assert_f64_bits_eq(
                    score.envelope_span_mm,
                    get_str(score_json, "envelopeSpanMm"),
                    &format!("{entry_label}.selectedScore.envelopeSpanMm"),
                );
                assert_f64_bits_eq(
                    score.shared_boundary_length_mm,
                    get_str(score_json, "sharedBoundaryLengthMm"),
                    &format!("{entry_label}.selectedScore.sharedBoundaryLengthMm"),
                );
                assert_eq!(
                    score.canonical_combined_geometry_key,
                    get_str(score_json, "canonicalCombinedGeometryKey"),
                    "{entry_label}.selectedScore.canonicalCombinedGeometryKey"
                );
                match (&score.exact, &score_json["exact"]) {
                    (None, Value::Null) => {}
                    (Some(exact), exact_json) if !exact_json.is_null() => {
                        assert_f64_bits_eq(
                            exact.maximum_side_grid,
                            get_str(exact_json, "maximumSideGrid"),
                            &format!("{entry_label}.selectedScore.exact.maximumSideGrid"),
                        );
                        assert_eq!(
                            exact.envelope_area_grid2,
                            get_str(exact_json, "envelopeAreaGrid2"),
                            "{entry_label}.selectedScore.exact.envelopeAreaGrid2"
                        );
                        assert_f64_bits_eq(
                            exact.envelope_span_grid,
                            get_str(exact_json, "envelopeSpanGrid"),
                            &format!("{entry_label}.selectedScore.exact.envelopeSpanGrid"),
                        );
                    }
                    other => {
                        panic!("{entry_label}.selectedScore.exact presence mismatch: {other:?}")
                    }
                }
            }
            other => panic!("{entry_label}.selectedScore presence mismatch: {other:?}"),
        }
    }
}

fn decode_status(raw: &str) -> IntrinsicStrictDecodeStatus {
    match raw {
        "completed" => IntrinsicStrictDecodeStatus::Completed,
        "incomplete" => IntrinsicStrictDecodeStatus::Incomplete,
        "infeasible-final-sheet" => IntrinsicStrictDecodeStatus::InfeasibleFinalSheet,
        other => panic!("unrecognized status: {other}"),
    }
}

fn decode_terminal_rotation(raw: f64) -> TerminalRotationDeg {
    if raw == 0.0 {
        TerminalRotationDeg::Zero
    } else if raw == 90.0 {
        TerminalRotationDeg::Ninety
    } else {
        panic!("unrecognized terminal rotation: {raw}")
    }
}

// ===========================================================================
// Section A: `transformCandidateOrder` sweeps.
// ===========================================================================
#[test]
fn transform_order_cases_match_ts() {
    let vectors = load_vectors();
    let cases = vectors["transformOrderCases"]
        .as_array()
        .expect("transformOrderCases present");
    assert!(
        !cases.is_empty(),
        "expected at least one transform-order case"
    );
    for case in cases {
        let label = get_str(case, "caseLabel");
        let mut transforms = decode_transforms(&case["input"]);
        transforms.sort_by(transform_candidate_order);
        let expected_indices: Vec<f64> = case["sortedIndices"]
            .as_array()
            .expect("sortedIndices present")
            .iter()
            .map(|v| parse_f64_bits(v.as_str().expect("index hex")))
            .collect();
        assert_eq!(
            transforms.len(),
            expected_indices.len(),
            "{label}: length mismatch"
        );
        for (index, (transform, expected)) in
            transforms.iter().zip(expected_indices.iter()).enumerate()
        {
            assert_eq!(
                transform.index.to_bits(),
                expected.to_bits(),
                "{label}[{index}]: sorted index mismatch (rust={}, ts={})",
                transform.index,
                expected
            );
        }
    }
}

// ===========================================================================
// Section A (continued): `canonicalLinearMetric`/`canonicalAreaMetric`
// rounding sweeps.
// ===========================================================================
#[test]
fn metric_rounding_cases_match_ts() {
    let vectors = load_vectors();
    let cases = vectors["metricRoundingCases"]
        .as_array()
        .expect("metricRoundingCases present");
    assert!(
        !cases.is_empty(),
        "expected at least one metric-rounding case"
    );
    for case in cases {
        let label = get_str(case, "caseLabel");
        let value_mm = get_f64(case, "valueMm");
        let linear = canonical_linear_metric(value_mm);
        assert_f64_bits_eq(
            linear,
            get_str(case, "linearGrid"),
            &format!("{label}: canonicalLinearMetric"),
        );
        let area_value_mm2 = get_f64(case, "areaValueMm2");
        let area = canonical_area_metric(area_value_mm2);
        assert_f64_bits_eq(
            area,
            get_str(case, "areaGrid"),
            &format!("{label}: canonicalAreaMetric"),
        );
    }
}

// ===========================================================================
// Section B: full decode runs.
// ===========================================================================
#[allow(clippy::too_many_arguments)]
fn run_construct<'a>(
    pieces: &'a [Arc<IrregularPreparedPiece>],
    candidate_mode: IntrinsicStrictCandidateMode,
    maximum_runtime_ms: f64,
    maximum_candidate_evaluation_count: Option<f64>,
    maximum_completed_piece_boundaries: Option<f64>,
    capture_phase_timings: bool,
    checkpoint: Option<
        irregular_nesting_native::search::strict_decoder::IntrinsicStrictDirectCheckpoint,
    >,
    timing_now: &'a TimingNowFn,
    settings: &IrregularNestingSettings,
    cache: &mut GeometryCacheStore,
) -> Result<
    irregular_nesting_native::search::strict_decoder::IntrinsicStrictConstructResult,
    IntrinsicStrictDecoderFailure,
> {
    let input = ConstructIntrinsicStrictStateInput {
        all_prepared_pieces: pieces,
        remaining_prepared_pieces: pieces,
        frozen_placed: &[],
        candidate_mode,
        maximum_runtime_ms: Some(maximum_runtime_ms),
        maximum_candidate_evaluation_count,
        capture_candidate_evaluation_count: true,
        capture_phase_timings,
        timing_now: Some(timing_now),
        producer_role: None,
        checkpoint,
        maximum_completed_piece_boundaries,
        control: None,
    };
    construct_intrinsic_strict_state(input, settings, cache)
}

#[test]
fn decode_cases_match_ts() {
    let vectors = load_vectors();
    let nesting_settings = settings(&vectors);
    let cases = vectors["decodeCases"]
        .as_array()
        .expect("decodeCases present");
    assert!(!cases.is_empty(), "expected at least one decode case");
    for case in cases {
        let label = get_str(case, "caseLabel");
        let pieces = decode_prepared_pieces(&case["pieces"]);
        let candidate_mode = candidate_mode_from_label(get_str(case, "candidateMode"));
        let maximum_runtime_ms = get_f64(case, "maximumRuntimeMs");
        let sheet = SheetSpec {
            width: get_f64(case, "finalSheetWidth"),
            height: get_f64(case, "finalSheetHeight"),
            label: "vector-sheet".to_string(),
        };
        let clock = make_clock();
        let mut cache = GeometryCacheStore::new();
        let result = run_construct(
            &pieces,
            candidate_mode,
            maximum_runtime_ms,
            None,
            None,
            false,
            None,
            &clock,
            &nesting_settings,
            &mut cache,
        );
        let expected = &case["result"];
        let expected_exit_tag = get_str(expected, "exitTag");
        match result {
            Ok(constructed) => {
                assert_eq!(
                    expected_exit_tag, "Success",
                    "{label}: expected exitTag Success"
                );
                let runtime_ms = constructed.runtime_ms;
                let candidate_evaluation_count = constructed.candidate_evaluation_count;
                let step_trace_owned = constructed.step_trace.clone();
                let finalized = finalize_intrinsic_strict_state(&sheet, constructed, runtime_ms)
                    .unwrap_or_else(|err| panic!("{label}: unexpected finalize failure: {err:?}"));
                assert_eq!(
                    finalized.status,
                    decode_status(get_str(expected, "status")),
                    "{label}: status"
                );
                match (
                    finalized.terminal_rotation_deg,
                    &expected["terminalRotationDeg"],
                ) {
                    (None, Value::Null) => {}
                    (Some(actual), Value::Number(n)) => {
                        let expected_rotation =
                            decode_terminal_rotation(n.as_f64().expect("finite rotation"));
                        assert_eq!(actual, expected_rotation, "{label}: terminalRotationDeg");
                    }
                    other => panic!("{label}: terminalRotationDeg presence mismatch: {other:?}"),
                }
                match (
                    &finalized.canonical_geometry_hash,
                    &expected["canonicalGeometryHash"],
                ) {
                    (None, Value::Null) => {}
                    (Some(actual), Value::String(s)) => {
                        assert_eq!(actual, s, "{label}: canonicalGeometryHash")
                    }
                    other => panic!("{label}: canonicalGeometryHash presence mismatch: {other:?}"),
                }
                assert_placements_eq(
                    &finalized.placements,
                    &expected["placements"],
                    &format!("{label}.placements"),
                );
                let expected_unplaced: Vec<&str> = expected["unplacedPieceIds"]
                    .as_array()
                    .expect("unplacedPieceIds present")
                    .iter()
                    .map(|v| v.as_str().expect("unplaced id string"))
                    .collect();
                let actual_unplaced: Vec<&str> = finalized
                    .unplaced_piece_ids
                    .iter()
                    .map(|id| id.as_str())
                    .collect();
                assert_eq!(
                    actual_unplaced, expected_unplaced,
                    "{label}: unplacedPieceIds"
                );
                assert_metrics_eq(
                    finalized.metrics.as_ref(),
                    &expected["metrics"],
                    &format!("{label}.metrics"),
                );
                assert_certificate_eq(
                    finalized.certificate.as_ref(),
                    &expected["certificate"],
                    &format!("{label}.certificate"),
                );
                assert_step_trace_eq(
                    &finalized.step_trace,
                    &expected["stepTrace"],
                    &format!("{label}.stepTrace"),
                );
                let _ = step_trace_owned;
                assert_opt_f64_bits_eq(
                    candidate_evaluation_count,
                    &expected["candidateEvaluationCount"],
                    &format!("{label}.candidateEvaluationCount"),
                );
                assert_f64_bits_eq(
                    finalized.runtime_ms,
                    get_str(expected, "runtimeMs"),
                    &format!("{label}.runtimeMs"),
                );
            }
            Err(failure) => {
                assert_eq!(
                    expected_exit_tag, "Failure",
                    "{label}: expected exitTag Failure, got {failure:?}"
                );
                assert_failure_matches(&failure, &expected["failure"], label);
            }
        }
    }
}

fn assert_failure_matches(failure: &IntrinsicStrictDecoderFailure, expected: &Value, label: &str) {
    let expected_tag = get_str(expected, "tag");
    match failure {
        IntrinsicStrictDecoderFailure::Decoder(err) => {
            assert_eq!(
                expected_tag, "IntrinsicStrictDecoderError",
                "{label}: failure tag"
            );
            if let Some(message) = expected["message"].as_str() {
                assert_eq!(err.message, message, "{label}: failure message");
            }
        }
        IntrinsicStrictDecoderFailure::Geometry(err) => {
            assert_eq!(
                expected_tag, "IrregularGeometryInputError",
                "{label}: failure tag"
            );
            let _ = err;
        }
        IntrinsicStrictDecoderFailure::Abort(err) => {
            assert_eq!(
                expected_tag, "IrregularNfpIfpControlAbortError",
                "{label}: failure tag"
            );
            let expected_reason = expected["reason"].as_str();
            let actual_reason = match err.reason {
                NfpIfpAbortReason::Deadline => "deadline",
                NfpIfpAbortReason::Cancelled => "cancelled",
            };
            if let Some(expected_reason) = expected_reason {
                assert_eq!(actual_reason, expected_reason, "{label}: failure reason");
            }
            if let Some(message) = expected["message"].as_str() {
                assert_eq!(err.message, message, "{label}: failure message");
            }
        }
    }
}

// ===========================================================================
// Section A (continued): `measureIntrinsicStrictCanonicalEnvelope` cases.
// ===========================================================================
#[test]
fn envelope_cases_match_ts() {
    let vectors = load_vectors();
    let cases = vectors["envelopeCases"]
        .as_array()
        .expect("envelopeCases present");
    assert!(!cases.is_empty(), "expected at least one envelope case");
    for case in cases {
        let label = get_str(case, "caseLabel");
        let placed_points = case["placedPoints"]
            .as_array()
            .expect("placedPoints present");
        let translate_x = case["translateX"].as_array().expect("translateX present");
        let translate_y = case["translateY"].as_array().expect("translateY present");
        assert_eq!(placed_points.len(), translate_x.len());
        assert_eq!(placed_points.len(), translate_y.len());
        let placed: Vec<IrregularPlacedPiece> = (0..placed_points.len())
            .map(|index| {
                decode_envelope_placed_piece(
                    &placed_points[index],
                    parse_f64_bits(translate_x[index].as_str().expect("translateX hex")),
                    parse_f64_bits(translate_y[index].as_str().expect("translateY hex")),
                )
            })
            .collect();
        let result = measure_intrinsic_strict_canonical_envelope(&placed);
        let expected = &case["result"];
        let expected_defined = expected["defined"].as_bool().expect("defined present");
        match (result, expected_defined) {
            (None, false) => {}
            (Some((maximum_side_mm, envelope_area_mm2, envelope_span_mm)), true) => {
                assert_f64_bits_eq(
                    maximum_side_mm,
                    get_str(expected, "maximumSideMm"),
                    &format!("{label}.maximumSideMm"),
                );
                assert_f64_bits_eq(
                    envelope_area_mm2,
                    get_str(expected, "envelopeAreaMm2"),
                    &format!("{label}.envelopeAreaMm2"),
                );
                assert_f64_bits_eq(
                    envelope_span_mm,
                    get_str(expected, "envelopeSpanMm"),
                    &format!("{label}.envelopeSpanMm"),
                );
            }
            other => panic!("{label}: envelope presence mismatch: {other:?}"),
        }
    }
}

// ===========================================================================
// Section A (continued): `measureIntrinsicSheetlessCompletedLayout` cases.
// ===========================================================================
#[test]
fn measure_completed_layout_cases_match_ts() {
    let vectors = load_vectors();
    let nesting_settings = settings(&vectors);
    let cases = vectors["measureCompletedLayoutCases"]
        .as_array()
        .expect("measureCompletedLayoutCases present");
    assert!(
        !cases.is_empty(),
        "expected at least one measure-completed-layout case"
    );
    for case in cases {
        let label = get_str(case, "caseLabel");
        let pieces = decode_prepared_pieces(&case["pieces"]);
        let candidate_mode = candidate_mode_from_label(get_str(case, "candidateMode"));
        let clock = make_clock();
        let mut cache = GeometryCacheStore::new();
        let constructed = run_construct(
            &pieces,
            candidate_mode,
            120_000.0,
            None,
            None,
            false,
            None,
            &clock,
            &nesting_settings,
            &mut cache,
        )
        .unwrap_or_else(|err| panic!("{label}: unexpected construct failure: {err:?}"));
        let runtime_ms_input = get_f64(case, "runtimeMs");
        let result =
            measure_intrinsic_sheetless_completed_layout(&constructed.state, runtime_ms_input);
        let expected = &case["result"];
        let expected_defined = expected["defined"].as_bool().expect("defined present");
        match (result, expected_defined) {
            (None, false) => {}
            (Some(layout), true) => {
                assert_eq!(
                    layout.canonical_geometry_identity,
                    get_str(expected, "canonicalGeometryIdentity"),
                    "{label}: canonicalGeometryIdentity"
                );
                assert_eq!(
                    layout.canonical_geometry_hash,
                    get_str(expected, "canonicalGeometryHash"),
                    "{label}: canonicalGeometryHash"
                );
                assert_metrics_eq(
                    Some(&layout.metrics),
                    &expected["metrics"],
                    &format!("{label}.metrics"),
                );
            }
            other => panic!("{label}: measure-completed presence mismatch: {other:?}"),
        }
    }
}

// ===========================================================================
// Section C: checkpoint round-trip cases.
// ===========================================================================
#[test]
fn checkpoint_cases_match_ts() {
    let vectors = load_vectors();
    let nesting_settings = settings(&vectors);
    let cases = vectors["checkpointCases"]
        .as_array()
        .expect("checkpointCases present");
    assert!(!cases.is_empty(), "expected at least one checkpoint case");
    for case in cases {
        let label = get_str(case, "caseLabel");
        let pieces = decode_prepared_pieces(&case["pieces"]);
        let candidate_mode = candidate_mode_from_label(get_str(case, "candidateMode"));
        let boundary = get_f64(case, "maximumCompletedPieceBoundaries");
        let capture_phase_timings = case["capturePhaseTimings"]
            .as_bool()
            .expect("capturePhaseTimings present");
        let sheet = SheetSpec {
            width: get_f64(case, "finalSheetWidth"),
            height: get_f64(case, "finalSheetHeight"),
            label: "vector-sheet".to_string(),
        };

        // Stage 1: construct up to the recorded completed-piece boundary.
        let mut cache1 = GeometryCacheStore::new();
        let clock1 = make_clock();
        let stage1 = run_construct(
            &pieces,
            candidate_mode,
            120_000.0,
            None,
            Some(boundary),
            capture_phase_timings,
            None,
            &clock1,
            &nesting_settings,
            &mut cache1,
        )
        .unwrap_or_else(|err| panic!("{label}: unexpected stage-1 failure: {err:?}"));
        assert_eq!(
            stage1.pause_reason,
            Some(PauseReason::CompletedPieceBoundary),
            "{label}: stage-1 pauseReason"
        );
        let checkpoint = stage1
            .checkpoint
            .clone()
            .unwrap_or_else(|| panic!("{label}: expected a stage-1 checkpoint"));
        let expected_checkpoint = &case["checkpoint"];
        assert_eq!(
            checkpoint.version,
            get_str(expected_checkpoint, "version"),
            "{label}: checkpoint.version"
        );
        assert_eq!(
            checkpoint.producer_role,
            get_str(expected_checkpoint, "producerRole"),
            "{label}: checkpoint.producerRole"
        );
        assert_eq!(
            checkpoint.request_fingerprint,
            get_str(expected_checkpoint, "requestFingerprint"),
            "{label}: checkpoint.requestFingerprint (canonical-JSON preimage byte mismatch)"
        );
        assert_f64_bits_eq(
            checkpoint.next_piece_index,
            get_str(expected_checkpoint, "nextPieceIndex"),
            &format!("{label}: checkpoint.nextPieceIndex"),
        );
        assert_f64_bits_eq(
            checkpoint.step_trace.len() as f64,
            get_str(expected_checkpoint, "stepTraceLength"),
            &format!("{label}: checkpoint.stepTrace.length"),
        );
        assert_f64_bits_eq(
            checkpoint.candidate_evaluation_count,
            get_str(expected_checkpoint, "candidateEvaluationCount"),
            &format!("{label}: checkpoint.candidateEvaluationCount"),
        );
        assert_f64_bits_eq(
            checkpoint.active_runtime_ms,
            get_str(expected_checkpoint, "activeRuntimeMs"),
            &format!("{label}: checkpoint.activeRuntimeMs"),
        );
        match (
            &checkpoint.phase_ledger,
            &expected_checkpoint["phaseLedger"],
        ) {
            (None, Value::Null) => {}
            (Some(ledger), ledger_json) if !ledger_json.is_null() => {
                assert_f64_bits_eq(
                    ledger.candidate_generation_ms,
                    get_str(ledger_json, "candidateGenerationMs"),
                    &format!("{label}: checkpoint.phaseLedger.candidateGenerationMs"),
                );
                assert_f64_bits_eq(
                    ledger.candidate_state_scoring_ms,
                    get_str(ledger_json, "candidateStateScoringMs"),
                    &format!("{label}: checkpoint.phaseLedger.candidateStateScoringMs"),
                );
            }
            other => panic!("{label}: phaseLedger presence mismatch: {other:?}"),
        }
        // `checkpoint.integrityHash` is deliberately **not** asserted here --
        // see `checkpoint_integrity_hash_is_blocked_on_spatial_index_continuation_identity`
        // below for the full root-cause writeup and a dedicated `#[ignore]`d
        // reproduction of exactly this byte mismatch. Every other checkpoint
        // field (including `requestFingerprint`, which does *not* embed the
        // affected string) is still asserted byte-exact above, and the
        // resumed second stage below still proves the checkpoint/resume
        // round-trip itself is semantically correct.

        // Stage 2: resume with the Rust port's own stage-1 checkpoint, run to
        // completion, and compare against the recorded uninterrupted ground
        // truth.
        let mut cache2 = GeometryCacheStore::new();
        let clock2 = make_clock();
        let stage2 = run_construct(
            &pieces,
            candidate_mode,
            120_000.0,
            None,
            None,
            capture_phase_timings,
            Some(checkpoint),
            &clock2,
            &nesting_settings,
            &mut cache2,
        )
        .unwrap_or_else(|err| panic!("{label}: unexpected stage-2 (resume) failure: {err:?}"));
        let runtime_ms = stage2.runtime_ms;
        let finalized = finalize_intrinsic_strict_state(&sheet, stage2, runtime_ms)
            .unwrap_or_else(|err| panic!("{label}: unexpected resumed finalize failure: {err:?}"));
        let uninterrupted = &case["uninterrupted"];
        assert_eq!(
            finalized.status,
            decode_status(get_str(uninterrupted, "status")),
            "{label}: resumed status vs uninterrupted"
        );
        match (
            &finalized.canonical_geometry_hash,
            &uninterrupted["canonicalGeometryHash"],
        ) {
            (None, Value::Null) => {}
            (Some(actual), Value::String(s)) => {
                assert_eq!(
                    actual, s,
                    "{label}: resumed canonicalGeometryHash vs uninterrupted"
                )
            }
            other => panic!("{label}: resumed canonicalGeometryHash presence mismatch: {other:?}"),
        }
        assert_placements_eq(
            &finalized.placements,
            &uninterrupted["placements"],
            &format!("{label}.resumed.placements"),
        );
    }
}

// ===========================================================================
// Section D: candidate-evaluation-cap truncation cases.
// ===========================================================================
fn decode_truncation_reason(raw: &str) -> TruncationReason {
    match raw {
        "maximum-candidate-evaluations" => TruncationReason::MaximumCandidateEvaluations,
        other => panic!("unrecognized truncation reason: {other}"),
    }
}

#[test]
fn budget_cap_cases_match_ts() {
    let vectors = load_vectors();
    let nesting_settings = settings(&vectors);
    let cases = vectors["budgetCapCases"]
        .as_array()
        .expect("budgetCapCases present");
    assert!(!cases.is_empty(), "expected at least one budget-cap case");
    for case in cases {
        let label = get_str(case, "caseLabel");
        let pieces = decode_prepared_pieces(&case["pieces"]);
        let candidate_mode = candidate_mode_from_label(get_str(case, "candidateMode"));
        let cap = get_f64(case, "maximumCandidateEvaluationCount");
        let clock = make_clock();
        let mut cache = GeometryCacheStore::new();
        let constructed = run_construct(
            &pieces,
            candidate_mode,
            120_000.0,
            Some(cap),
            None,
            false,
            None,
            &clock,
            &nesting_settings,
            &mut cache,
        )
        .unwrap_or_else(|err| panic!("{label}: unexpected construct failure: {err:?}"));
        match (&constructed.truncation_reason, &case["truncationReason"]) {
            (None, Value::Null) => {}
            (Some(actual), Value::String(s)) => {
                assert_eq!(
                    *actual,
                    decode_truncation_reason(s),
                    "{label}: truncationReason"
                )
            }
            other => panic!("{label}: truncationReason presence mismatch: {other:?}"),
        }
        assert_opt_f64_bits_eq(
            constructed.candidate_evaluation_count,
            &case["candidateEvaluationCount"],
            &format!("{label}.candidateEvaluationCount"),
        );
        assert_f64_bits_eq(
            constructed.step_trace.len() as f64,
            get_str(case, "stepTraceLength"),
            &format!("{label}.stepTrace.length"),
        );
    }
}

// ===========================================================================
// Section E: deadline-abort cases.
// ===========================================================================
#[test]
fn deadline_cases_match_ts() {
    let vectors = load_vectors();
    let nesting_settings = settings(&vectors);
    let cases = vectors["deadlineCases"]
        .as_array()
        .expect("deadlineCases present");
    assert!(!cases.is_empty(), "expected at least one deadline case");
    for case in cases {
        let label = get_str(case, "caseLabel");
        let pieces = decode_prepared_pieces(&case["pieces"]);
        let candidate_mode = candidate_mode_from_label(get_str(case, "candidateMode"));
        let maximum_runtime_ms = get_f64(case, "maximumRuntimeMs");
        let previous_active_runtime_ms = get_f64(case, "previousActiveRuntimeMs");
        let expect_failure = case["expectFailure"]
            .as_bool()
            .expect("expectFailure present");

        let result = if previous_active_runtime_ms != 0.0 {
            // The resumed-checkpoint case: replay stage 1 (with the same
            // shared `maximumRuntimeMs`, since it is hashed into the
            // checkpoint's own requestFingerprint) to obtain a real Rust
            // checkpoint whose `activeRuntimeMs` must match the recorded
            // `previousActiveRuntimeMs` exactly, then resume it.
            let mut cache1 = GeometryCacheStore::new();
            let clock1 = make_clock();
            let stage1 = run_construct(
                &pieces,
                candidate_mode,
                maximum_runtime_ms,
                None,
                Some(1.0),
                false,
                None,
                &clock1,
                &nesting_settings,
                &mut cache1,
            )
            .unwrap_or_else(|err| panic!("{label}: unexpected stage-1 failure: {err:?}"));
            let checkpoint = stage1
                .checkpoint
                .unwrap_or_else(|| panic!("{label}: expected a stage-1 checkpoint"));
            assert_f64_bits_eq(
                checkpoint.active_runtime_ms,
                get_str(case, "previousActiveRuntimeMs"),
                &format!("{label}: stage-1 checkpoint.activeRuntimeMs"),
            );
            let mut cache2 = GeometryCacheStore::new();
            let clock2 = make_clock();
            run_construct(
                &pieces,
                candidate_mode,
                maximum_runtime_ms,
                None,
                None,
                false,
                Some(checkpoint),
                &clock2,
                &nesting_settings,
                &mut cache2,
            )
        } else {
            let clock = make_clock();
            let mut cache = GeometryCacheStore::new();
            run_construct(
                &pieces,
                candidate_mode,
                maximum_runtime_ms,
                None,
                None,
                false,
                None,
                &clock,
                &nesting_settings,
                &mut cache,
            )
        };

        match result {
            Ok(_) => assert!(
                !expect_failure,
                "{label}: expected a deadline failure, got Success"
            ),
            Err(failure) => {
                assert!(
                    expect_failure,
                    "{label}: expected Success, got failure {failure:?}"
                );
                match failure {
                    IntrinsicStrictDecoderFailure::Abort(err) => {
                        let actual_reason = match err.reason {
                            NfpIfpAbortReason::Deadline => "deadline",
                            NfpIfpAbortReason::Cancelled => "cancelled",
                        };
                        assert_eq!(actual_reason, get_str(case, "reason"), "{label}: reason");
                        assert_eq!(err.message, get_str(case, "message"), "{label}: message");
                    }
                    other => panic!("{label}: expected an Abort failure, got {other:?}"),
                }
            }
        }
    }
}

// ===========================================================================
// Section F: Pareto/ranking cases.
// ===========================================================================
fn decode_metrics_exact(value: &Value) -> Option<IntrinsicStrictCompletedMetricsExact> {
    if value.is_null() {
        return None;
    }
    Some(IntrinsicStrictCompletedMetricsExact {
        envelope_maximum_side_grid: get_f64(value, "envelopeMaximumSideGrid"),
        envelope_area_grid2: get_str(value, "envelopeAreaGrid2").to_string(),
        envelope_span_grid: get_f64(value, "envelopeSpanGrid"),
        total_enclosed_cavity_doubled_area_grid2: get_str(
            value,
            "totalEnclosedCavityDoubledAreaGrid2",
        )
        .to_string(),
        largest_occupied_hull_gap_doubled_area_grid2: get_str(
            value,
            "largestOccupiedHullGapDoubledAreaGrid2",
        )
        .to_string(),
        occupied_hull_doubled_area_grid2: get_str(value, "occupiedHullDoubledAreaGrid2")
            .to_string(),
        occupied_hull_waste_doubled_area_grid2: get_str(value, "occupiedHullWasteDoubledAreaGrid2")
            .to_string(),
        largest_positive_contact_component_size: get_f64(
            value,
            "largestPositiveContactComponentSize",
        ),
        placed_piece_count: get_f64(value, "placedPieceCount"),
        occupied_outside_largest_contact_component_doubled_area_grid2: get_str(
            value,
            "occupiedOutsideLargestContactComponentDoubledAreaGrid2",
        )
        .to_string(),
    })
}

fn decode_metrics(value: &Value) -> IntrinsicStrictCompletedMetrics {
    IntrinsicStrictCompletedMetrics {
        envelope_maximum_side_mm: get_f64(value, "envelopeMaximumSideMm"),
        envelope_area_mm2: get_f64(value, "envelopeAreaMm2"),
        envelope_span_mm: get_f64(value, "envelopeSpanMm"),
        enclosed_cavity_count: get_f64(value, "enclosedCavityCount"),
        total_enclosed_cavity_area_mm2: get_f64(value, "totalEnclosedCavityAreaMm2"),
        largest_occupied_hull_gap_ratio: get_f64(value, "largestOccupiedHullGapRatio"),
        isolated_piece_count: get_f64(value, "isolatedPieceCount"),
        positive_contact_component_count: get_f64(value, "positiveContactComponentCount"),
        largest_positive_contact_component_size: get_f64(
            value,
            "largestPositiveContactComponentSize",
        ),
        largest_positive_contact_component_ratio: get_f64(
            value,
            "largestPositiveContactComponentRatio",
        ),
        occupied_area_outside_largest_contact_component_mm2: get_f64(
            value,
            "occupiedAreaOutsideLargestContactComponentMm2",
        ),
        occupied_hull_waste_ratio: get_f64(value, "occupiedHullWasteRatio"),
        total_structural_contacts: get_f64(value, "totalStructuralContacts"),
        dominant_structural_contacts: get_f64(value, "dominantStructuralContacts"),
        contact_units: get_f64(value, "contactUnits"),
        shared_boundary_length_mm: get_f64(value, "sharedBoundaryLengthMm"),
        canonical_geometry_hash: get_str(value, "canonicalGeometryHash").to_string(),
        runtime_ms: get_f64(value, "runtimeMs"),
        exact: decode_metrics_exact(&value["exact"]),
    }
}

#[test]
fn pareto_cases_match_ts() {
    let vectors = load_vectors();
    let cases = vectors["paretoCases"]
        .as_array()
        .expect("paretoCases present");
    assert!(!cases.is_empty(), "expected at least one pareto case");
    for case in cases {
        let label = get_str(case, "caseLabel");
        let pool: Vec<IntrinsicStrictCompletedMetrics> = case["pool"]
            .as_array()
            .expect("pool present")
            .iter()
            .map(decode_metrics)
            .collect();

        let ranked = rank_intrinsic_strict_completed_layouts(&pool);
        let expected_ranked: Vec<&str> = case["rankedHashes"]
            .as_array()
            .expect("rankedHashes present")
            .iter()
            .map(|v| v.as_str().expect("hash string"))
            .collect();
        let actual_ranked: Vec<&str> = ranked
            .iter()
            .map(|m| m.canonical_geometry_hash.as_str())
            .collect();
        assert_eq!(actual_ranked, expected_ranked, "{label}: rankedHashes");

        let front = select_intrinsic_strict_completed_pareto_front(&pool);
        let expected_front: Vec<&str> = case["frontHashes"]
            .as_array()
            .expect("frontHashes present")
            .iter()
            .map(|v| v.as_str().expect("hash string"))
            .collect();
        let actual_front: Vec<&str> = front
            .iter()
            .map(|m| m.canonical_geometry_hash.as_str())
            .collect();
        assert_eq!(actual_front, expected_front, "{label}: frontHashes");

        let expected_dominance = case["dominanceMatrix"]
            .as_array()
            .expect("dominanceMatrix present");
        let expected_dominates = case["dominatesMatrix"]
            .as_array()
            .expect("dominatesMatrix present");
        assert_eq!(
            pool.len(),
            expected_dominance.len(),
            "{label}: dominanceMatrix row count"
        );
        for (i, first) in pool.iter().enumerate() {
            let expected_row = expected_dominance[i]
                .as_array()
                .expect("dominance row present");
            let expected_dominates_row = expected_dominates[i]
                .as_array()
                .expect("dominates row present");
            assert_eq!(
                pool.len(),
                expected_row.len(),
                "{label}: dominanceMatrix[{i}] column count"
            );
            for (j, second) in pool.iter().enumerate() {
                let ordering = compare_intrinsic_strict_completed_layout_dominance(first, second);
                let expected_tag = expected_row[j].as_str().expect("dominance cell string");
                let expected_ordering = match expected_tag {
                    "lt" => Ordering::Less,
                    "gt" => Ordering::Greater,
                    "eq" => Ordering::Equal,
                    other => panic!("unrecognized dominance tag: {other}"),
                };
                assert_eq!(
                    ordering, expected_ordering,
                    "{label}: dominanceMatrix[{i}][{j}]"
                );

                let dominates = intrinsic_strict_completed_layout_dominates(first, second);
                let expected_dominates_cell = expected_dominates_row[j]
                    .as_bool()
                    .expect("dominates cell boolean");
                assert_eq!(
                    dominates, expected_dominates_cell,
                    "{label}: dominatesMatrix[{i}][{j}]"
                );
            }
        }
    }
}

// ===========================================================================
// Vector-count sanity gate (mirrors the dump script's own >= 400 assertion).
// ===========================================================================
#[test]
fn total_vector_count_meets_floor() {
    let vectors = load_vectors();
    let total = vectors["totalVectorCount"]
        .as_u64()
        .expect("totalVectorCount present");
    assert!(
        total >= 400,
        "expected >= 400 total strict-decoder vectors, got {total}"
    );
}

// ===========================================================================
// KNOWN, ROOT-CAUSED, OUT-OF-FILE-OWNERSHIP BLOCKER: `checkpoint.integrityHash`
// is not yet byte-exact against TS, because it embeds a string produced by a
// sibling module this task must not edit.
// ===========================================================================
//
// Root cause (confirmed via direct preimage diffing -- see the task notes for
// the full investigation): `IrregularBeamState::continuation_metadata_identity`
// (`src/search/beam_state.rs`) embeds
// `PlacedCollisionSpatialIndex::continuation_identity()`
// (`src/validation/spatial_index.rs:261-299`), whose own doc comment
// (`spatial_index.rs:~245-260`) explicitly states it is *not* required to be
// byte-identical to the TS `continuationIdentity()`
// (`placedCollisionSpatialIndex.ts:118-127`) because, at the time it was
// written, no caller needed cross-language byte parity for it -- only
// Rust-to-Rust self-consistency. `search::strict_decoder`'s checkpoint
// integrity-hash preimage (`collectIntrinsicStrictDirectStateLineage`'s
// `continuationMetadataIdentity` field, TS `intrinsicStrictDecoder.ts:1106`)
// is a **new** caller that retroactively requires exactly that byte parity,
// which that sibling module's stated scope does not (yet) provide. Two
// concrete divergences were isolated by diffing the real TS preimage
// (captured by inlining `intrinsicStrictCanonicalJson` from
// `intrinsicStrictDecoder.ts:1257-1277` in a throwaway script and verifying
// it reproduces the real `checkpoint.integrityHash` exactly) against the
// equivalent Rust preimage (captured via a temporary `eprintln!` in
// `intrinsic_strict_direct_checkpoint_integrity_hash`, since neither side's
// preimage-building function is otherwise observable from outside its own
// module):
//   1. `PlacedCollisionSpatialIndex::continuation_identity()` serializes
//      `cell_size_mm: f64` via plain `serde_json::to_string`, which renders a
//      whole-valued float as `"64.0"`; TS's native `JSON.stringify` (used by
//      `continuationIdentity()`) renders the same value as `"64"`. This is
//      exactly the "reimplement JS's own number-to-string, don't rely on the
//      host language's default" hazard this whole cluster's other GREEN
//      modules route through `number_to_js_string` for.
//   2. `continuation_identity()`'s `buckets` field is sorted by parsed
//      numeric `(cell_x, cell_y)` tuple; TS's counterpart sorts by
//      `.localeCompare()` on the **stringified** `"x:y"` bucket key. These
//      orders coincide for this test's single-digit, non-negative cell
//      coordinates, but are a *second*, independent, latent divergence for
//      any grid spanning two-digit or negative cell coordinates (see
//      characterization-doc-style hazard 1 elsewhere in this cluster:
//      `.localeCompare()` vs. ordinal/numeric order).
//
// Both divergences live entirely inside `validation::spatial_index.rs`
// (owned by a different concurrently-developed tower), which this task's
// file-ownership rule forbids editing. This test exists so the exact byte
// mismatch (and its root cause) is reproducible and re-checkable in one
// place without re-deriving the investigation, and will start passing
// automatically once that sibling module's `continuation_identity()` is
// made byte-exact against `continuationIdentity()`. Every other checkpoint
// field -- including `requestFingerprint`, which does not embed this string
// -- is asserted byte-exact (and passes) in `checkpoint_cases_match_ts`
// above.
#[test]
#[ignore = "blocked on validation::spatial_index::PlacedCollisionSpatialIndex::continuation_identity() \
            not yet being byte-exact against TS continuationIdentity() (see this test's doc comment); \
            re-enable once that sibling module closes the cellSizeMm-formatting and bucket-sort-order gaps"]
fn checkpoint_integrity_hash_is_blocked_on_spatial_index_continuation_identity() {
    let vectors = load_vectors();
    let nesting_settings = settings(&vectors);
    let cases = vectors["checkpointCases"]
        .as_array()
        .expect("checkpointCases present");
    for case in cases {
        let label = get_str(case, "caseLabel");
        let pieces = decode_prepared_pieces(&case["pieces"]);
        let candidate_mode = candidate_mode_from_label(get_str(case, "candidateMode"));
        let boundary = get_f64(case, "maximumCompletedPieceBoundaries");
        let capture_phase_timings = case["capturePhaseTimings"]
            .as_bool()
            .expect("capturePhaseTimings present");
        let mut cache = GeometryCacheStore::new();
        let clock = make_clock();
        let stage1 = run_construct(
            &pieces,
            candidate_mode,
            120_000.0,
            None,
            Some(boundary),
            capture_phase_timings,
            None,
            &clock,
            &nesting_settings,
            &mut cache,
        )
        .unwrap_or_else(|err| panic!("{label}: unexpected stage-1 failure: {err:?}"));
        let checkpoint = stage1
            .checkpoint
            .unwrap_or_else(|| panic!("{label}: expected a stage-1 checkpoint"));
        assert_eq!(
            checkpoint.integrity_hash,
            get_str(&case["checkpoint"], "integrityHash"),
            "{label}: checkpoint.integrityHash"
        );
    }
}
