//! Differential-vector test for `crates/irregular-nesting-native/src/transforms`
//! (`generator::generate_transforms`, `rotate::transform_and_snap_point`).
//!
//! Loads `tests/vectors/transforms.json`, generated by
//! `scripts/rust-parity/dump-transforms.ts` from the REAL production
//! `TransformGeneratorLive.generateTransforms` (`transformGenerator.ts`) and
//! `computeTransformedCollisionGeometry` (`core/transformCollisionGeometryCore.ts`),
//! and asserts this crate's Rust port reproduces every recorded candidate
//! list (order, reason, rotation, mirrored, and the assigned index) and every
//! rotated/mirrored/grid-snapped point coordinate exactly (bit-for-bit `f64`
//! via `to_bits()`).

use std::fs;

use irregular_nesting_native::domain::{
    CollisionGeometry, IrregularBounds, IrregularGeometrySettings, IrregularOptimizerSettings,
    IrregularPlacementPolicyId, IrregularPoint, IrregularPolygon, IrregularTransformReason,
    PieceId,
};
use irregular_nesting_native::transforms::generator::{
    generate_transforms, GenerateTransformsInput,
};
use irregular_nesting_native::transforms::rotate::transform_and_snap_point;
use serde::Deserialize;
use serde_json::Value;

fn load_vectors() -> Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/vectors/transforms.json");
    let raw = fs::read_to_string(path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&raw).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

fn parse_f64_bits(hex: &str) -> f64 {
    let stripped = hex
        .strip_prefix("0x")
        .unwrap_or_else(|| panic!("bit-pattern hex must start with 0x, got {hex}"));
    let bits = u64::from_str_radix(stripped, 16)
        .unwrap_or_else(|err| panic!("invalid bit-pattern hex {hex}: {err}"));
    f64::from_bits(bits)
}

#[derive(Deserialize)]
struct PointBits {
    x: String,
    y: String,
}

impl PointBits {
    fn to_point(&self) -> IrregularPoint {
        IrregularPoint::new(parse_f64_bits(&self.x), parse_f64_bits(&self.y))
    }
}

#[derive(Deserialize)]
struct RecordedSettings {
    #[serde(rename = "transformCap")]
    transform_cap: f64,
    #[serde(rename = "transformMinimumEdgeLengthMm")]
    transform_minimum_edge_length_mm: String,
    #[serde(rename = "transformAngleDeduplicationToleranceDeg")]
    transform_angle_deduplication_tolerance_deg: String,
    #[serde(rename = "configuredRotationEnabled")]
    configured_rotation_enabled: bool,
    #[serde(rename = "edgeAlignmentEnabled")]
    edge_alignment_enabled: bool,
    #[serde(rename = "configuredRotationDeg")]
    configured_rotation_deg: Vec<String>,
    #[serde(rename = "intrinsicSharedArchiveEnabled")]
    intrinsic_shared_archive_enabled: bool,
    #[serde(rename = "placementPolicyId")]
    placement_policy_id: String,
    #[serde(rename = "gaEnabled")]
    ga_enabled: bool,
    #[serde(rename = "baselineOnly")]
    baseline_only: bool,
    #[serde(rename = "gaTimeBudgetMs")]
    ga_time_budget_ms: f64,
    #[serde(rename = "gaGenerationBudget")]
    ga_generation_budget: f64,
    #[serde(rename = "gaEvaluationBudget")]
    ga_evaluation_budget: f64,
}

fn placement_policy_id(raw: &str) -> IrregularPlacementPolicyId {
    match raw {
        "balanced-compactness" => IrregularPlacementPolicyId::BalancedCompactness,
        "short-side-fill" => IrregularPlacementPolicyId::ShortSideFill,
        "edge-contact-then-balanced-compactness" => {
            IrregularPlacementPolicyId::EdgeContactThenBalancedCompactness
        }
        other => panic!("unrecognized placementPolicyId: {other}"),
    }
}

/// Every other `IrregularOptimizerSettings` field this crate's domain type
/// requires but `generate_transforms`'s algorithm never reads -- filled with
/// arbitrary valid placeholder values (this test never asserts anything
/// about them).
fn full_optimizer_settings(recorded: &RecordedSettings) -> IrregularOptimizerSettings {
    IrregularOptimizerSettings {
        order_window: 1.0,
        beam_width: 1.0,
        local_candidate_fanout: 4.0,
        local_repair_budget: 0.0,
        intrinsic_shared_archive_enabled: recorded.intrinsic_shared_archive_enabled,
        intrinsic_objective_profile_id:
            irregular_nesting_native::domain::IntrinsicObjectiveProfileId::Compact,
        transform_cap: recorded.transform_cap,
        transform_minimum_edge_length_mm: parse_f64_bits(
            &recorded.transform_minimum_edge_length_mm,
        ),
        transform_angle_deduplication_tolerance_deg: parse_f64_bits(
            &recorded.transform_angle_deduplication_tolerance_deg,
        ),
        configured_rotation_enabled: recorded.configured_rotation_enabled,
        edge_alignment_enabled: recorded.edge_alignment_enabled,
        configured_rotation_deg: recorded
            .configured_rotation_deg
            .iter()
            .map(|bits| parse_f64_bits(bits))
            .collect(),
        ga_enabled: recorded.ga_enabled,
        baseline_only: recorded.baseline_only,
        ga_population: 8.0,
        ga_generation_budget: recorded.ga_generation_budget,
        ga_evaluation_budget: recorded.ga_evaluation_budget,
        ga_time_budget_ms: recorded.ga_time_budget_ms,
        ga_seed: "transforms-vectors".to_string(),
        priority_order_mutation_enabled: true,
        transform_preference_mutation_enabled: true,
        placement_policy_mutation_enabled: true,
        placement_policy_id: placement_policy_id(&recorded.placement_policy_id),
        placement_policy_ids:
            irregular_nesting_native::domain::default_irregular_placement_policy_ids(),
    }
}

fn reason_from_str(raw: &str) -> IrregularTransformReason {
    match raw {
        "orthogonal" => IrregularTransformReason::Orthogonal,
        "edge_alignment" => IrregularTransformReason::EdgeAlignment,
        "configured" => IrregularTransformReason::Configured,
        other => panic!("unrecognized transform reason: {other}"),
    }
}

#[test]
fn generate_transforms_matches_ts_production_oracle_over_the_full_matrix() {
    let file = load_vectors();

    let generating_commit = file["generatingCommit"]
        .as_str()
        .expect("generatingCommit header present");
    assert!(
        !generating_commit.is_empty(),
        "vectors file must record its generating commit (ruling R14)"
    );

    let case_count = file["generateTransformsCaseCount"]
        .as_u64()
        .expect("generateTransformsCaseCount header present") as usize;
    let cases = file["generateTransformsCases"]
        .as_array()
        .expect("generateTransformsCases present");
    assert_eq!(
        cases.len(),
        case_count,
        "case count header must match actual cases"
    );
    assert!(
        cases.len() >= 300,
        "expected >= 300 generateTransforms cases per the task spec, got {}",
        cases.len()
    );

    let mut checked_candidates = 0usize;

    for case in cases {
        let case_label = case["caseLabel"].as_str().expect("caseLabel present");
        let ok = case["ok"].as_bool().expect("ok present");
        assert!(
            ok,
            "case {case_label}: every deliberately-constructed dump-transforms.ts case is expected to succeed"
        );

        let points: Vec<IrregularPoint> =
            serde_json::from_value::<Vec<PointBits>>(case["points"].clone())
                .unwrap_or_else(|err| panic!("case {case_label}: malformed points: {err}"))
                .iter()
                .map(PointBits::to_point)
                .collect();
        let recorded_settings: RecordedSettings = serde_json::from_value(case["settings"].clone())
            .unwrap_or_else(|err| panic!("case {case_label}: malformed settings: {err}"));
        let sag_mm = parse_f64_bits(case["sagMm"].as_str().expect("sagMm present"));
        let allow_rotation = case["allowRotation"]
            .as_bool()
            .expect("allowRotation present");
        let allow_mirror = case["allowMirror"].as_bool().expect("allowMirror present");

        let input = GenerateTransformsInput {
            geometry: CollisionGeometry {
                source_piece_id: PieceId::new("dump-transforms-piece"),
                source_bounds: IrregularBounds::new(0.0, 0.0, 10.0, 10.0),
                sampled_points: points.clone(),
                convex_hull: IrregularPolygon::new(points.clone()),
                collision_polygon: IrregularPolygon::new(points),
                placement_reference: IrregularPoint::new(0.0, 0.0),
                diagnostics: vec![],
            },
            allow_rotation,
            allow_mirror,
            geometry_settings: IrregularGeometrySettings {
                flattening_sag_tolerance_mm: sag_mm,
                clearance_safety_margin_mm: sag_mm,
                geometry_backend_id: "transforms-vectors".to_string(),
                geometry_backend_version: "0".to_string(),
            },
            settings: full_optimizer_settings(&recorded_settings),
        };

        let result = generate_transforms(&input)
            .unwrap_or_else(|err| panic!("case {case_label}: generate_transforms failed: {err:?}"));

        let expected_candidates = case["candidates"]
            .as_array()
            .unwrap_or_else(|| panic!("case {case_label}: missing candidates array"));

        assert_eq!(
            result.len(),
            expected_candidates.len(),
            "case {case_label}: candidate count mismatch"
        );

        for (index, (actual, expected)) in result.iter().zip(expected_candidates.iter()).enumerate()
        {
            let expected_index = expected["index"].as_f64().expect("index present");
            let expected_rotation_deg = parse_f64_bits(
                expected["rotationDeg"]
                    .as_str()
                    .expect("rotationDeg present"),
            );
            let expected_mirrored = expected["mirrored"].as_bool().expect("mirrored present");
            let expected_reason =
                reason_from_str(expected["reason"].as_str().expect("reason present"));

            assert_eq!(
                actual.index, expected_index,
                "case {case_label} candidate {index}: index mismatch"
            );
            assert_eq!(
                actual.rotation_deg.to_bits(),
                expected_rotation_deg.to_bits(),
                "case {case_label} candidate {index}: rotationDeg mismatch: rust={} ts={}",
                actual.rotation_deg,
                expected_rotation_deg
            );
            assert_eq!(
                actual.mirrored, expected_mirrored,
                "case {case_label} candidate {index}: mirrored mismatch"
            );
            assert_eq!(
                actual.reason, expected_reason,
                "case {case_label} candidate {index}: reason mismatch"
            );
            checked_candidates += 1;
        }
    }

    assert!(
        checked_candidates >= 300,
        "expected >= 300 total candidate vectors checked, got {checked_candidates}"
    );
}

#[test]
fn transform_and_snap_point_matches_ts_production_oracle_over_real_and_synthetic_rings() {
    let file = load_vectors();

    let rotation_case_count = file["rotationCaseCount"]
        .as_u64()
        .expect("rotationCaseCount present") as usize;
    let rotation_vector_count = file["rotationVectorCount"]
        .as_u64()
        .expect("rotationVectorCount present") as usize;
    let cases = file["rotationCases"]
        .as_array()
        .expect("rotationCases present");
    assert_eq!(
        cases.len(),
        rotation_case_count,
        "rotation case count header must match actual cases"
    );
    assert!(
        rotation_vector_count >= 300,
        "expected >= 300 rotated-point vectors per the task spec, got {rotation_vector_count}"
    );

    let mut checked_points = 0usize;

    for case in cases {
        let case_label = case["caseLabel"].as_str().expect("caseLabel present");
        let ok = case["ok"].as_bool().expect("ok present");
        assert!(
            ok,
            "case {case_label}: every deliberately-constructed rotation case is expected to succeed"
        );

        let rotation_deg = case["rotationDeg"].as_f64().expect("rotationDeg present");
        let mirrored = case["mirrored"].as_bool().expect("mirrored present");

        let input_points: Vec<IrregularPoint> =
            serde_json::from_value::<Vec<PointBits>>(case["inputPoints"].clone())
                .unwrap_or_else(|err| panic!("case {case_label}: malformed inputPoints: {err}"))
                .iter()
                .map(PointBits::to_point)
                .collect();
        let expected_output_points: Vec<PointBits> =
            serde_json::from_value(case["outputPoints"].clone())
                .unwrap_or_else(|err| panic!("case {case_label}: malformed outputPoints: {err}"));

        assert_eq!(
            input_points.len(),
            expected_output_points.len(),
            "case {case_label}: input/output point count mismatch"
        );

        for (point_index, (input_point, expected)) in input_points
            .iter()
            .zip(expected_output_points.iter())
            .enumerate()
        {
            let actual = transform_and_snap_point(*input_point, mirrored, rotation_deg).unwrap_or_else(|| {
                panic!("case {case_label} point {point_index}: expected the point to fit the canonical grid")
            });
            let expected_x = parse_f64_bits(&expected.x);
            let expected_y = parse_f64_bits(&expected.y);
            assert_eq!(
                actual.x.to_bits(),
                expected_x.to_bits(),
                "case {case_label} point {point_index}: x mismatch: rust={} ts={}",
                actual.x,
                expected_x
            );
            assert_eq!(
                actual.y.to_bits(),
                expected_y.to_bits(),
                "case {case_label} point {point_index}: y mismatch: rust={} ts={}",
                actual.y,
                expected_y
            );
            checked_points += 1;
        }
    }

    assert_eq!(
        checked_points, rotation_vector_count,
        "checked point count must match the header's rotationVectorCount"
    );
    assert!(
        checked_points >= 300,
        "expected >= 300 rotated-point vectors checked, got {checked_points}"
    );
}
