//! Differential-vector test for `crates/irregular-nesting-native/src/validation`
//! (`placement::assess_placement`,
//! `spatial_index::{make_placed_collision_spatial_index,
//! make_empty_placed_collision_spatial_index}`,
//! `sat::measure_convex_sat_penetration`).
//!
//! Loads `tests/vectors/validation.json`, generated by
//! `scripts/rust-parity/dump-validation.ts` from the REAL production
//! `assessPlacement` (`placementValidation.ts`),
//! `makePlacedCollisionSpatialIndex`/`makeEmptyPlacedCollisionSpatialIndex`
//! (`placedCollisionSpatialIndex.ts`), and `measureConvexSatPenetration`
//! (`convexSatPenetration.ts`), and asserts this crate's Rust port reproduces
//! every recorded legality verdict, spatial-index query ordering (ordinal
//! order, byte-for-byte), and `matches()` boolean exactly (bit-for-bit `f64`
//! via `to_bits()`, exact strings). SAT `depth`/`translation` use
//! `assert_close`'s documented, measured bounded tolerance instead of pure
//! `to_bits()` equality (see that function's doc comment and `sat.rs`'s
//! module doc "Trig bit-parity" section) -- `assessPlacement` and the
//! spatial index have no such tolerance and remain 100% bit-exact.

use std::fs;
use std::sync::Arc;

use irregular_nesting_native::domain::{
    IrregularBounds, IrregularPlacedPiece, IrregularPlacement, IrregularPoint, IrregularPolygon,
    IrregularTransform, IrregularTransformCandidate, IrregularTransformReason, PieceId, SheetSpec,
    TransformedCollisionGeometry,
};
use irregular_nesting_native::validation::placement::{
    assess_placement, AssessPlacementInput, AssessPlacementOutcome,
};
use irregular_nesting_native::validation::sat::measure_convex_sat_penetration;
use irregular_nesting_native::validation::spatial_index::{
    make_empty_placed_collision_spatial_index, make_placed_collision_spatial_index,
    PlacedCollisionSpatialIndex,
};
use serde::Deserialize;

fn load_vectors() -> VectorFile {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/vectors/validation.json");
    let raw = fs::read_to_string(path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    serde_json::from_str(&raw).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"))
}

fn parse_f64_bits(hex: &str) -> f64 {
    let stripped = hex
        .strip_prefix("0x")
        .unwrap_or_else(|| panic!("bit-pattern hex must start with 0x, got {hex}"));
    let bits = u64::from_str_radix(stripped, 16)
        .unwrap_or_else(|err| panic!("invalid bit-pattern hex {hex}: {err}"));
    f64::from_bits(bits)
}

// ---------------------------------------------------------------------------
// Vector file shape, mirroring `scripts/rust-parity/dump-validation.ts`'s
// output exactly.
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
struct VectorFile {
    #[serde(rename = "generatingCommit")]
    #[allow(dead_code)]
    generating_commit: String,
    #[serde(rename = "totalVectorCount")]
    total_vector_count: usize,
    #[serde(rename = "assessPlacement")]
    assess_placement: AssessPlacementSection,
    #[serde(rename = "spatialIndex")]
    spatial_index: SpatialIndexSection,
    sat: SatSection,
}

#[derive(Deserialize)]
struct EncodedPoint {
    x: String,
    y: String,
}

fn decode_point(p: &EncodedPoint) -> IrregularPoint {
    IrregularPoint::new(parse_f64_bits(&p.x), parse_f64_bits(&p.y))
}

fn decode_points(points: &[EncodedPoint]) -> Vec<IrregularPoint> {
    points.iter().map(decode_point).collect()
}

#[derive(Deserialize)]
struct EncodedBounds {
    #[serde(rename = "minX")]
    min_x: String,
    #[serde(rename = "minY")]
    min_y: String,
    #[serde(rename = "maxX")]
    max_x: String,
    #[serde(rename = "maxY")]
    max_y: String,
}

fn decode_bounds(b: &EncodedBounds) -> IrregularBounds {
    IrregularBounds::new(
        parse_f64_bits(&b.min_x),
        parse_f64_bits(&b.min_y),
        parse_f64_bits(&b.max_x),
        parse_f64_bits(&b.max_y),
    )
}

// --- Section 1: assessPlacement -------------------------------------------

#[derive(Deserialize)]
struct AssessPlacementSection {
    #[serde(rename = "caseCount")]
    case_count: usize,
    cases: Vec<AssessPlacementCase>,
}

#[derive(Deserialize)]
struct EncodedSheet {
    width: String,
    height: String,
}

#[derive(Deserialize)]
#[serde(tag = "kind")]
enum EncodedOutcome {
    #[serde(rename = "legal")]
    Legal,
    #[serde(rename = "illegal")]
    Illegal { message: String },
    #[serde(rename = "failure")]
    Failure { operation: String, message: String },
}

#[derive(Deserialize)]
struct AssessPlacementCase {
    #[serde(rename = "caseLabel")]
    case_label: String,
    #[serde(rename = "enforceSheetBounds")]
    enforce_sheet_bounds: bool,
    sheet: Option<EncodedSheet>,
    #[serde(rename = "movingPolygon")]
    moving_polygon: Vec<EncodedPoint>,
    #[serde(rename = "candidatePoint")]
    candidate_point: EncodedPoint,
    #[serde(rename = "placedPolygons")]
    placed_polygons: Vec<Vec<EncodedPoint>>,
    #[serde(rename = "placedTranslations")]
    placed_translations: Vec<EncodedPoint>,
    #[serde(rename = "useIndex")]
    use_index: bool,
    #[serde(rename = "indexCellSizeMm")]
    index_cell_size_mm: Option<String>,
    outcome: EncodedOutcome,
}

fn placeholder_piece_id(label: &str, ordinal: usize) -> PieceId {
    PieceId::new(format!("validation-vectors-{label}-{ordinal}"))
}

fn build_placed_piece(
    label: &str,
    ordinal: usize,
    points: Vec<IrregularPoint>,
    translate_x: f64,
    translate_y: f64,
) -> Arc<IrregularPlacedPiece> {
    let piece_id = placeholder_piece_id(label, ordinal);
    // Bounds on `collision_geometry` are never read by `assess_placement` --
    // it always recomputes bounds itself via `translate_polygon_with_bounds`
    // -- so an arbitrary degenerate placeholder is safe here.
    let bounds = IrregularBounds::new(0.0, 0.0, 0.0, 0.0);
    Arc::new(IrregularPlacedPiece {
        placement: IrregularPlacement {
            piece_id: None,
            source_piece_id: piece_id.clone(),
            placement_reference: None,
            transform: IrregularTransform {
                translate_x,
                translate_y,
                rotation_deg: 0.0,
                mirrored: false,
            },
        },
        collision_geometry: TransformedCollisionGeometry {
            source_piece_id: piece_id,
            transform: IrregularTransformCandidate {
                index: 0.0,
                rotation_deg: 0.0,
                mirrored: false,
                reason: IrregularTransformReason::Orthogonal,
            },
            polygon: IrregularPolygon::new(points),
            bounds,
        },
    })
}

#[test]
fn assess_placement_matches_ts_oracle() {
    let vectors = load_vectors();
    assert_eq!(
        vectors.assess_placement.cases.len(),
        vectors.assess_placement.case_count
    );

    for case in &vectors.assess_placement.cases {
        let sheet_spec = case.sheet.as_ref().map(|s| SheetSpec {
            width: parse_f64_bits(&s.width),
            height: parse_f64_bits(&s.height),
            label: "validation-vectors-sheet".to_string(),
        });

        let placed_arcs: Vec<Arc<IrregularPlacedPiece>> = case
            .placed_polygons
            .iter()
            .zip(case.placed_translations.iter())
            .enumerate()
            .map(|(index, (polygon, translation))| {
                build_placed_piece(
                    &case.case_label,
                    index,
                    decode_points(polygon),
                    parse_f64_bits(&translation.x),
                    parse_f64_bits(&translation.y),
                )
            })
            .collect();

        let index: Option<PlacedCollisionSpatialIndex> = if case.use_index {
            let cell_size = case
                .index_cell_size_mm
                .as_ref()
                .map(|hex| parse_f64_bits(hex));
            Some(make_placed_collision_spatial_index(&placed_arcs, cell_size))
        } else {
            None
        };

        let moving_points = decode_points(&case.moving_polygon);
        let moving_geometry = TransformedCollisionGeometry {
            source_piece_id: PieceId::new("validation-vectors-moving"),
            transform: IrregularTransformCandidate {
                index: 0.0,
                rotation_deg: 0.0,
                mirrored: false,
                reason: IrregularTransformReason::Orthogonal,
            },
            polygon: IrregularPolygon::new(moving_points),
            bounds: IrregularBounds::new(0.0, 0.0, 0.0, 0.0),
        };

        let candidate_point = decode_point(&case.candidate_point);

        let input = AssessPlacementInput {
            sheet: sheet_spec.as_ref(),
            placed: &placed_arcs,
            placed_collision_index: index.as_ref(),
            moving: &moving_geometry,
            candidate_point,
        };

        let outcome = assess_placement(&input, case.enforce_sheet_bounds);

        match (&outcome, &case.outcome) {
            (AssessPlacementOutcome::Assessment(assessment), EncodedOutcome::Legal) => {
                assert!(
                    assessment.legal,
                    "case {}: expected legal, got illegal: {}",
                    case.case_label, assessment.message
                );
                assert_eq!(
                    assessment.message, "",
                    "case {}: legal message must be empty",
                    case.case_label
                );
            }
            (
                AssessPlacementOutcome::Assessment(assessment),
                EncodedOutcome::Illegal { message },
            ) => {
                assert!(
                    !assessment.legal,
                    "case {}: expected illegal, got legal",
                    case.case_label
                );
                assert_eq!(
                    &assessment.message, message,
                    "case {}: illegal message mismatch",
                    case.case_label
                );
            }
            (
                AssessPlacementOutcome::Failure(err),
                EncodedOutcome::Failure { operation, message },
            ) => {
                assert_eq!(
                    &err.operation, operation,
                    "case {}: failure operation mismatch",
                    case.case_label
                );
                assert_eq!(
                    &err.message, message,
                    "case {}: failure message mismatch",
                    case.case_label
                );
            }
            _ => panic!(
                "case {}: outcome kind mismatch (rust outcome: {:?})",
                case.case_label, outcome
            ),
        }
    }
}

// --- Section 2: spatial index sequences ------------------------------------

#[derive(Deserialize)]
struct SpatialIndexSection {
    #[serde(rename = "caseCount")]
    case_count: usize,
    cases: Vec<SpatialIndexSequenceCase>,
}

#[derive(Deserialize)]
struct EncodedIndexPiece {
    polygon: Vec<EncodedPoint>,
    #[serde(rename = "translateX")]
    translate_x: String,
    #[serde(rename = "translateY")]
    translate_y: String,
}

#[derive(Deserialize)]
struct EncodedQuery {
    #[allow(dead_code)]
    label: String,
    bounds: Option<EncodedBounds>,
    #[serde(rename = "resultOrdinals")]
    result_ordinals: Vec<usize>,
}

#[derive(Deserialize)]
struct EncodedMatchesCheck {
    label: String,
    result: bool,
}

#[derive(Deserialize)]
struct SpatialIndexSequenceCase {
    #[serde(rename = "caseLabel")]
    case_label: String,
    #[serde(rename = "cellSizeMm")]
    cell_size_mm: String,
    #[serde(rename = "pieceCount")]
    piece_count: usize,
    pieces: Vec<EncodedIndexPiece>,
    #[serde(rename = "pieceBounds")]
    piece_bounds: Vec<EncodedBounds>,
    #[serde(rename = "pieceValid")]
    piece_valid: Vec<bool>,
    queries: Vec<EncodedQuery>,
    #[serde(rename = "matchesChecks")]
    matches_checks: Vec<EncodedMatchesCheck>,
}

#[test]
fn spatial_index_sequences_match_ts_oracle() {
    let vectors = load_vectors();
    assert_eq!(
        vectors.spatial_index.cases.len(),
        vectors.spatial_index.case_count
    );

    for case in &vectors.spatial_index.cases {
        let cell_size_mm = parse_f64_bits(&case.cell_size_mm);
        let piece_arcs: Vec<Arc<IrregularPlacedPiece>> = case
            .pieces
            .iter()
            .enumerate()
            .map(|(index, piece)| {
                build_placed_piece(
                    &case.case_label,
                    index,
                    decode_points(&piece.polygon),
                    parse_f64_bits(&piece.translate_x),
                    parse_f64_bits(&piece.translate_y),
                )
            })
            .collect();

        assert_eq!(
            piece_arcs.len(),
            case.piece_count,
            "case {}: piece count mismatch",
            case.case_label
        );

        let index = make_placed_collision_spatial_index(&piece_arcs, Some(cell_size_mm));

        assert_eq!(
            index.size(),
            case.piece_count,
            "case {}: index size mismatch",
            case.case_label
        );

        // Cross-check per-entry validity and (for valid entries) bounds
        // against the TS oracle's own recorded `makeEntry` output, in
        // ordinal order.
        for (ordinal, entry) in index.entries().iter().enumerate() {
            let expected_valid = case.piece_valid[ordinal];
            let actual_valid = matches!(
                entry.validation,
                irregular_nesting_native::validation::spatial_index::PlacedCollisionValidation::Valid(_)
            );
            assert_eq!(
                actual_valid, expected_valid,
                "case {} entry {ordinal}: validity mismatch",
                case.case_label
            );
            if expected_valid {
                if let irregular_nesting_native::validation::spatial_index::PlacedCollisionValidation::Valid(valid) =
                    &entry.validation
                {
                    let expected_bounds = decode_bounds(&case.piece_bounds[ordinal]);
                    assert_eq!(
                        valid.polygon_with_bounds.bounds, expected_bounds,
                        "case {} entry {ordinal}: bounds mismatch",
                        case.case_label
                    );
                }
            }
        }

        for query in &case.queries {
            let bounds = query.bounds.as_ref().map(decode_bounds);
            let result = index.query(bounds.as_ref());
            let actual_ordinals: Vec<usize> = result.iter().map(|entry| entry.ordinal).collect();
            assert_eq!(
                actual_ordinals, query.result_ordinals,
                "case {} query {}: ordinal order mismatch",
                case.case_label, query.label
            );
        }

        for check in &case.matches_checks {
            let actual = match check.label.as_str() {
                "same-array" => index.matches(&piece_arcs),
                "empty-array" => index.matches(&[]),
                "truncated" => {
                    let truncated_len = piece_arcs.len().saturating_sub(1);
                    index.matches(&piece_arcs[..truncated_len])
                }
                "reordered" => {
                    let mut reordered = piece_arcs.clone();
                    reordered.reverse();
                    index.matches(&reordered)
                }
                "structural-copy" | "non-empty-array" => {
                    let copies: Vec<Arc<IrregularPlacedPiece>> = case
                        .pieces
                        .iter()
                        .enumerate()
                        .map(|(index, piece)| {
                            build_placed_piece(
                                &format!("{}-copy", case.case_label),
                                index,
                                decode_points(&piece.polygon),
                                parse_f64_bits(&piece.translate_x),
                                parse_f64_bits(&piece.translate_y),
                            )
                        })
                        .collect();
                    if check.label == "non-empty-array" {
                        // The TS "non-empty-array" case (only emitted for the
                        // empty-index fixture) checks a single fresh piece
                        // against an empty index.
                        index.matches(&[Arc::clone(copies.first().unwrap_or(&build_placed_piece(
                            "non-empty-fallback",
                            0,
                            vec![
                                IrregularPoint::new(0.0, 0.0),
                                IrregularPoint::new(1.0, 0.0),
                                IrregularPoint::new(1.0, 1.0),
                            ],
                            0.0,
                            0.0,
                        )))])
                    } else {
                        index.matches(&copies)
                    }
                }
                other => panic!("unknown matches-check label: {other}"),
            };
            assert_eq!(
                actual, check.result,
                "case {} matches-check {}: result mismatch",
                case.case_label, check.label
            );
        }
    }
}

#[test]
fn empty_index_helper_matches_ts_oracle_shape() {
    let index = make_empty_placed_collision_spatial_index(None);
    assert_eq!(index.size(), 0);
    assert!(index.entries().is_empty());
    assert!(index.query(None).is_empty());
    assert!(index.matches(&[]));
}

// --- Section 3: SAT penetration --------------------------------------------

#[derive(Deserialize)]
struct SatSection {
    #[serde(rename = "caseCount")]
    case_count: usize,
    cases: Vec<SatCase>,
}

#[derive(Deserialize)]
struct EncodedSatResult {
    depth: String,
    translation: EncodedPoint,
}

#[derive(Deserialize)]
struct SatCase {
    #[serde(rename = "caseLabel")]
    case_label: String,
    first: Vec<EncodedPoint>,
    second: Vec<EncodedPoint>,
    result: Option<EncodedSatResult>,
}

/// Bounded-tolerance comparison for `measure_convex_sat_penetration`'s
/// `f64` outputs, mirroring `transforms::flattening`'s documented,
/// *measured* (not assumed) trig-parity tolerance pattern.
///
/// `sat.rs`'s module doc ("Trig bit-parity") records the measurement behind
/// this: `polygon_axes`'s `hypot`-based edge normalization is not
/// guaranteed bit-identical to V8's `Math.hypot` (stage0-rulings.md R21),
/// and even after switching to `libm::hypot` (the better-tracking choice,
/// also measured), 20 of this file's 269 SAT cases still diverge from the
/// TS oracle by a handful of ULPs -- max observed `1.78e-15` absolute /
/// `4.91e-15` relative. `1e-9` below is the same round-number bound
/// `transforms::flattening` uses for its own residual trig gap, chosen for
/// cross-module consistency; it is ~6 orders of magnitude looser than the
/// measured maximum, so it still catches a real regression while absorbing
/// the documented, irreducible cross-runtime `hypot` divergence. This
/// module has zero production callers (see `sat.rs`'s liveness note), so no
/// downstream legality/comparator/hash consumes this tolerance -- the "no
/// tolerances deciding legality" hard rule does not apply here.
fn assert_close(actual: f64, expected: f64, case_label: &str, field: &str) {
    const TOLERANCE: f64 = 1e-9;
    if actual.to_bits() == expected.to_bits() {
        return;
    }
    let diff = (actual - expected).abs();
    assert!(
        diff <= TOLERANCE,
        "case {case_label}: {field} mismatch beyond tolerance: actual={actual:e} expected={expected:e} diff={diff:e}"
    );
}

#[test]
fn sat_penetration_matches_ts_oracle() {
    let vectors = load_vectors();
    assert_eq!(vectors.sat.cases.len(), vectors.sat.case_count);

    for case in &vectors.sat.cases {
        let first = decode_points(&case.first);
        let second = decode_points(&case.second);
        let actual = measure_convex_sat_penetration(&first, &second);

        match (&actual, &case.result) {
            (None, None) => {}
            (Some(actual_result), Some(expected)) => {
                let expected_depth = parse_f64_bits(&expected.depth);
                assert_close(
                    actual_result.depth,
                    expected_depth,
                    &case.case_label,
                    "depth",
                );
                let expected_translation = decode_point(&expected.translation);
                assert_close(
                    actual_result.translation.x,
                    expected_translation.x,
                    &case.case_label,
                    "translation.x",
                );
                assert_close(
                    actual_result.translation.y,
                    expected_translation.y,
                    &case.case_label,
                    "translation.y",
                );
            }
            _ => panic!(
                "case {}: presence mismatch (rust: {:?}, expected: {})",
                case.case_label,
                actual,
                if case.result.is_some() {
                    "Some"
                } else {
                    "None"
                }
            ),
        }
    }
}

#[test]
fn total_vector_count_is_at_least_500() {
    let vectors = load_vectors();
    assert!(
        vectors.total_vector_count >= 500,
        "expected >= 500 total validation vectors, got {}",
        vectors.total_vector_count
    );
}
