//! Standalone (no Node/N-API) profiling runner for the Mixed-61 `2000x2700`
//! Compact case -- the preregistered performance contract's primary gate
//! (`docs/planning/rust-irregular-backend/performance-contract.md` C1).
//!
//! Loads the prepared `NestingRequest` + `IrregularNestingSettings` from
//! `tests/vectors/mixed61-2000x2700-compact-request.json` (generated by
//! `scripts/rust-parity/dump-mixed61-2000x2700-request.ts` via the real,
//! unmodified TS `preparePieces` step -- see that script's own top doc) in
//! the exact JSON shape `tests/coordinator_vectors.rs`'s `decode_request`
//! uses, then calls `result::coordinator::compute_irregular_nesting`
//! directly in a pure Rust process. This gives a profiler (perf, samply,
//! valgrind/callgrind, etc.) a clean, single-purpose target with none of the
//! N-API/libuv/Node startup or marshalling overhead the `.node` addon path
//! carries.
//!
//! Usage:
//!   cargo build --release --example run_mixed61
//!   ./target/release/examples/run_mixed61 [--repeat N]
//!
//! Prints wall-clock elapsed time and the result's placed/unplaced counts so
//! a run can be sanity-checked against the known acceptance values (61
//! placed, 0 unplaced) without needing the TS oracle.

use std::fs;
use std::time::Instant;

use irregular_nesting_native::boundary::parallel::JobPool;
use irregular_nesting_native::caches::GeometryCacheStore;
use irregular_nesting_native::canonical_grid::layout::canonical_collision_layout_identity;
use irregular_nesting_native::domain::{
    DxfGeometryEntityType, DxfGeometrySegment, DxfGeometrySummary, DxfLineSegment, ImportedPiece,
    IrregularNestingSettings, PieceId, Rect, SheetSpec, SourceFileId,
};
use irregular_nesting_native::result::coordinator::{
    compute_irregular_nesting, ComputeIrregularNestingOptions,
};
use irregular_nesting_native::result::{HistoryMode, NestingOptions, NestingRequest};
use irregular_nesting_native::search::layout_scorer::FreeMaterialCache;
use irregular_nesting_native::search::sort_pieces::{CutRowRef, PreparedPiece, RectWith};
use serde_json::Value;
use sha2::{Digest, Sha256};

fn decode_imported_piece(value: &Value) -> ImportedPiece {
    // The fixture only ever contains line segments (enforced by the dump
    // script), so a hand-rolled decode is sufficient here without pulling in
    // the full `DxfGeometrySegment` serde-tagged union machinery for arcs.
    let segments = value["geometry"]["segments"]
        .as_array()
        .expect("segments array")
        .iter()
        .map(|segment| {
            DxfGeometrySegment::Line(DxfLineSegment {
                x1: segment["x1"].as_f64().expect("x1"),
                y1: segment["y1"].as_f64().expect("y1"),
                x2: segment["x2"].as_f64().expect("x2"),
                y2: segment["y2"].as_f64().expect("y2"),
                bulge: None,
                source_curve: None,
            })
        })
        .collect();
    ImportedPiece {
        id: PieceId::new(value["id"].as_str().expect("id")),
        source_file_id: SourceFileId::new(value["sourceFileId"].as_str().expect("sourceFileId")),
        source_layer: None,
        label: value["label"].as_str().expect("label").to_string(),
        real_bounds: decode_rect(&value["realBounds"]),
        geometry: DxfGeometrySummary {
            entity_type: DxfGeometryEntityType::PresetShape,
            closed: value["geometry"]["closed"].as_bool().expect("closed"),
            segments,
        },
        warnings: Vec::new(),
    }
}

fn decode_rect(value: &Value) -> Rect {
    Rect {
        x: value["x"].as_f64().expect("x"),
        y: value["y"].as_f64().expect("y"),
        width: value["width"].as_f64().expect("width"),
        height: value["height"].as_f64().expect("height"),
    }
}

fn decode_prepared_piece(value: &Value) -> PreparedPiece {
    let padded = &value["paddedBounds"];
    PreparedPiece {
        id: PieceId::new(value["id"].as_str().expect("id")),
        source_piece_id: PieceId::new(value["sourcePieceId"].as_str().expect("sourcePieceId")),
        interchangeability_key: value["interchangeabilityKey"]
            .as_str()
            .map(|s| s.to_string()),
        real_bounds: decode_rect(&value["realBounds"]),
        padded_bounds: RectWith {
            rect: decode_rect(padded),
            longest_edge: padded["longestEdge"].as_f64().expect("longestEdge"),
            area: padded["area"].as_f64().expect("area"),
            imbalance: padded["imbalance"].as_f64().expect("imbalance"),
        },
        padding: value["padding"].as_f64().expect("padding"),
        allow_rotation: value["allowRotation"].as_bool().expect("allowRotation"),
        allow_mirror: value["allowMirror"].as_bool().expect("allowMirror"),
        cut_row_ref: None::<CutRowRef>,
    }
}

fn decode_request(root: &Value) -> (NestingRequest, IrregularNestingSettings) {
    let request_value = &root["request"];
    let settings: IrregularNestingSettings = serde_json::from_value(request_value["settings"].clone())
        .unwrap_or_else(|err| panic!("failed to decode IrregularNestingSettings: {err}"));
    let sheet: SheetSpec = serde_json::from_value(request_value["sheet"].clone())
        .unwrap_or_else(|err| panic!("failed to decode SheetSpec: {err}"));
    let pieces: Vec<PreparedPiece> = request_value["pieces"]
        .as_array()
        .expect("pieces array")
        .iter()
        .map(decode_prepared_piece)
        .collect();
    let source_pieces: Vec<ImportedPiece> = request_value["sourcePieces"]
        .as_array()
        .expect("sourcePieces array")
        .iter()
        .map(decode_imported_piece)
        .collect();
    let history_mode = match request_value["historyMode"].as_str().expect("historyMode") {
        "stream" => HistoryMode::Stream,
        "final" => HistoryMode::Final,
        "off" => HistoryMode::Off,
        other => panic!("unknown historyMode {other}"),
    };
    let request = NestingRequest {
        sheet,
        padding: request_value["padding"].as_f64().expect("padding"),
        pieces,
        source_pieces,
        options: NestingOptions {
            allow_global_rotation: request_value["allowGlobalRotation"]
                .as_bool()
                .expect("allowGlobalRotation"),
            allow_global_mirror: request_value["allowGlobalMirror"].as_bool(),
            history_mode,
            irregular_settings: None,
        },
    };
    (request, settings)
}

fn to_hex(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        out.push_str(&format!("{byte:02x}"));
    }
    out
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let repeat: usize = args
        .windows(2)
        .find(|window| window[0] == "--repeat")
        .and_then(|window| window[1].parse().ok())
        .unwrap_or(1);
    // `--threads N` installs a job-owned Rayon pool sized to `N` for every
    // repeat iteration, exactly mirroring `boundary::run_job`'s own
    // per-job `JobPool::new`/`.install()` sequence (`boundary::parallel`'s
    // doc) -- this is how `run_mixed61` measures the Stage 4 Rayon sites'
    // effect without going through the N-API/libuv path at all. Omitted or
    // absent: no pool is installed, so every `with_job_pool` call inline-
    // executes on this one thread (`boundary::parallel::with_job_pool`'s
    // documented no-pool-installed fallback) -- the historical, pre-Stage-4
    // single-threaded baseline this file always measured.
    let threads: Option<usize> = args
        .windows(2)
        .find(|window| window[0] == "--threads")
        .and_then(|window| window[1].parse().ok());

    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/vectors/mixed61-2000x2700-compact-request.json"
    );
    let raw = fs::read_to_string(path).unwrap_or_else(|err| panic!("failed to read {path}: {err}"));
    let root: Value = serde_json::from_str(&raw).unwrap_or_else(|err| panic!("failed to parse {path}: {err}"));
    let (request, settings) = decode_request(&root);

    for run in 0..repeat {
        let mut options = ComputeIrregularNestingOptions::default();
        let mut geometry_cache = GeometryCacheStore::new();
        let mut free_material_cache = FreeMaterialCache::new();

        // One fresh job-owned pool per repeat iteration, matching
        // `boundary::run_job` constructing exactly one `JobPool` per job
        // (never reused across jobs, never the ambient global Rayon pool).
        let job_pool = threads.map(|count| JobPool::new(Some(count)));
        let _pool_guard = job_pool.as_ref().map(JobPool::install);

        let started = Instant::now();
        let result = compute_irregular_nesting(
            &request,
            &settings,
            &mut options,
            &mut geometry_cache,
            &mut free_material_cache,
        )
        .unwrap_or_else(|error| panic!("compute_irregular_nesting failed: {error:?}"));
        let elapsed = started.elapsed();

        let placed_owned: Vec<_> = result
            .placed_collision_geometries
            .iter()
            .map(|piece| (**piece).clone())
            .collect();
        let collision_identity_sha256 = canonical_collision_layout_identity(&placed_owned)
            .map(|identity| to_hex(&Sha256::digest(identity.as_bytes())));

        println!(
            "[run_mixed61] run={run} elapsed_ms={:.1} placed={} unplaced={} collision_identity_sha256={}",
            elapsed.as_secs_f64() * 1000.0,
            result.placed_collision_geometries.len(),
            result.unplaced_piece_ids.len(),
            collision_identity_sha256.as_deref().unwrap_or("none"),
        );
    }
}
