//! Rotation/mirror point-application math.
//!
//! TS source: `src/workers/irregular/core/transformCollisionGeometryCore.ts:139-182`
//! (`snapPointToCollisionGrid`, `normalizeRotationDegrees`, `transformPoint`,
//! `normalizeNegativeZero`). See `super`'s module doc for why only this
//! self-contained point-math slice of that file is ported here, and not its
//! surrounding cache/key/resolver/revalidation surface
//! (`computeTransformedCollisionGeometry`, `resolveTransformedCollisionGeometry`),
//! which is owned by `crate::caches::transform_collision_geometry` — import it
//! from there; never re-implement it.
//!
//! # Trig-into-canonical-geometry flag (task-mandated, prominent)
//!
//! [`transform_point`]'s non-axis-aligned branch calls `Math.cos`/`Math.sin`
//! (`transformCollisionGeometryCore.ts:170-171`) on
//! `rotationRad = (rotationDeg * Math.PI) / 180` — real V8/Node libm calls,
//! not any JS-specific ECMA-262 rounding rule (unlike `Math.round`/`Math.sign`
//! in `js_number::js_math`, which really do diverge from Rust's `f64`
//! built-ins). Rust's `f64::cos`/`f64::sin` also delegate to the platform
//! libm, but are **not guaranteed bit-identical to V8's implementation** —
//! different libm versions can legitimately disagree in the last one or two
//! ULPs for the same input.
//!
//! **This matters here more than almost anywhere else in the crate**,
//! because [`transform_point`]'s output feeds `snapPointToCollisionGrid`
//! (composed here as [`transform_and_snap_point`]) — i.e. every non-quarter-turn
//! rotated collision-polygon vertex that becomes part of a piece's placed
//! geometry, which is downstream hashed into canonical checkpoint/history
//! artifacts (`checkpoints::canonical_json`) and compared for exact nesting
//! parity. A one-ULP `cos`/`sin` divergence *before* grid-quantization is
//! usually absorbed by `to_grid_mm`'s millimeter-scale rounding (ties away
//! from zero, `canonical_grid::to_grid_mm`), but is not guaranteed to be for
//! every input near a half-grid-step boundary. The differential vector suite
//! (`tests/vectors/transforms.json`, generated by
//! `scripts/rust-parity/dump-transforms.ts` from the REAL production
//! `computeTransformedCollisionGeometry`) is what actually proves bit-exact
//! agreement for the fixture-scale rotation angles exercised there, not an
//! assumption that "both are IEEE-754 `f64` trig, so they must agree."… If a
//! future fixture or production angle ever fails this vector suite, do not
//! "fix" it by special-casing — that is the signal the migration prompt's
//! §8.1/§8.3 trig-parity risk has become real for this call site and needs
//! its own resolution (e.g. a portable libm crate pinned to match V8, or a
//! documented, ruled-on tolerance), not a silent adaptation of this function.

use crate::domain::IrregularPoint;
use crate::js_number::fold_negative_zero;

/// TS: `transformCollisionGeometryCore.ts:146-149` `normalizeRotationDegrees`.
///
/// Deliberately **not** the same function as
/// `generator::normalize_rotation_deg`: this one has no finite-input guard
/// (no `Option` return) and does not itself fold a resulting `-0` — any `-0`
/// this produces (e.g. for `rotation_deg = -360.0`, whose JS `%` remainder is
/// `-0`) is only folded later, per transformed coordinate, by
/// [`transform_point`]'s `fold_negative_zero` calls — never here. Both
/// functions are kept independent to mirror the TS source's own two
/// independently-named, non-shared functions exactly.
pub fn normalize_rotation_degrees(rotation_deg: f64) -> f64 {
    let remainder = rotation_deg % 360.0;
    if remainder < 0.0 {
        remainder + 360.0
    } else {
        remainder
    }
}

/// TS: `transformCollisionGeometryCore.ts:151-178` `transformPoint`.
///
/// `rotation_deg` is expected to already be normalized to `[0, 360)` (via
/// [`normalize_rotation_degrees`]) by the caller, matching
/// `computeTransformedCollisionGeometry`'s call order
/// (`transformCollisionGeometryCore.ts:77-80`): the four exact quarter-turns
/// take closed-form branches with no trig at all; every other angle falls
/// through to the `cos`/`sin` branch (see this module's top-level doc for the
/// trig-parity risk that branch carries).
pub fn transform_point(point: IrregularPoint, mirrored: bool, rotation_deg: f64) -> IrregularPoint {
    let x = if mirrored { -point.x } else { point.x };
    let y = point.y;

    if rotation_deg == 0.0 {
        IrregularPoint::new(fold_negative_zero(x), fold_negative_zero(y))
    } else if rotation_deg == 90.0 {
        IrregularPoint::new(fold_negative_zero(-y), fold_negative_zero(x))
    } else if rotation_deg == 180.0 {
        IrregularPoint::new(fold_negative_zero(-x), fold_negative_zero(-y))
    } else if rotation_deg == 270.0 {
        IrregularPoint::new(fold_negative_zero(y), fold_negative_zero(-x))
    } else {
        // TS: `(rotationDeg * Math.PI) / 180` -- operator order preserved
        // literally (multiply, then divide) rather than reassociated, since
        // floating-point multiplication/division is not associative.
        let rotation_rad = rotation_deg * std::f64::consts::PI / 180.0;
        let cos = rotation_rad.cos();
        let sin = rotation_rad.sin();
        IrregularPoint::new(
            fold_negative_zero(x * cos - y * sin),
            fold_negative_zero(x * sin + y * cos),
        )
    }
}

/// Composes [`transform_point`] with the canonical-grid quantize/dequantize
/// round-trip, reproducing TS's `snapPointToCollisionGrid`
/// (`transformCollisionGeometryCore.ts:139-144`) applied to
/// `transformPoint`'s result exactly as
/// `computeTransformedCollisionGeometry`'s per-vertex loop
/// (`transformCollisionGeometryCore.ts:77-92`) does — reusing the
/// already-ported `canonical_grid::{to_grid_mm, from_grid}` rather than
/// duplicating that quantization policy.
///
/// `None` means the transformed point does not fit the canonical collision
/// grid (mirrors TS's `undefined` return from `snapPointToCollisionGrid`).
/// This function deliberately does **not** reproduce
/// `computeTransformedCollisionGeometry`'s surrounding boundary
/// re-validation, bounds computation, or cache-key/resolver logic -- see this
/// module's top-level doc for why that surface is out of scope here.
pub fn transform_and_snap_point(
    point: IrregularPoint,
    mirrored: bool,
    rotation_deg: f64,
) -> Option<IrregularPoint> {
    let normalized_rotation_deg = normalize_rotation_degrees(rotation_deg);
    let transformed = transform_point(point, mirrored, normalized_rotation_deg);
    let grid_x = crate::canonical_grid::to_grid_mm(transformed.x)?;
    let grid_y = crate::canonical_grid::to_grid_mm(transformed.y)?;
    Some(IrregularPoint::new(
        fold_negative_zero(crate::canonical_grid::from_grid(grid_x)),
        fold_negative_zero(crate::canonical_grid::from_grid(grid_y)),
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn p(x: f64, y: f64) -> IrregularPoint {
        IrregularPoint::new(x, y)
    }

    #[test]
    fn normalize_rotation_degrees_wraps_negative_and_large_values() {
        assert_eq!(normalize_rotation_degrees(0.0), 0.0);
        assert_eq!(normalize_rotation_degrees(360.0), 0.0);
        assert_eq!(normalize_rotation_degrees(450.0), 90.0);
        assert_eq!(normalize_rotation_degrees(-90.0), 270.0);
    }

    #[test]
    fn normalize_rotation_degrees_does_not_fold_negative_zero() {
        // TS: `-360 % 360 === -0`, and `normalizeRotationDegrees` itself does
        // not fold it (see this function's doc comment) -- only
        // `transformPoint`'s per-coordinate folds do that later.
        let result = normalize_rotation_degrees(-360.0);
        assert_eq!(result.to_bits(), (-0.0_f64).to_bits());
    }

    #[test]
    fn quarter_turns_use_exact_closed_form_branches() {
        let point = p(3.0, 5.0);
        assert_eq!(transform_point(point, false, 0.0), p(3.0, 5.0));
        assert_eq!(transform_point(point, false, 90.0), p(-5.0, 3.0));
        assert_eq!(transform_point(point, false, 180.0), p(-3.0, -5.0));
        assert_eq!(transform_point(point, false, 270.0), p(5.0, -3.0));
    }

    #[test]
    fn mirroring_negates_x_before_rotation() {
        let point = p(3.0, 5.0);
        assert_eq!(transform_point(point, true, 0.0), p(-3.0, 5.0));
        assert_eq!(transform_point(point, true, 90.0), p(-5.0, -3.0));
    }

    #[test]
    fn zero_rotation_folds_negative_zero_coordinates() {
        let result = transform_point(p(-0.0, -0.0), false, 0.0);
        assert_eq!(result.x.to_bits(), 0.0_f64.to_bits());
        assert_eq!(result.y.to_bits(), 0.0_f64.to_bits());
    }

    #[test]
    fn mirroring_at_zero_rotation_folds_a_negated_zero_x() {
        // mirrored: x = -point.x. For point.x = 0.0, -0.0 must fold back to +0.
        let result = transform_point(p(0.0, 1.0), true, 0.0);
        assert_eq!(result.x.to_bits(), 0.0_f64.to_bits());
    }

    #[test]
    fn arbitrary_angle_uses_trig_branch_and_matches_hand_computed_rotation() {
        let point = p(1.0, 0.0);
        let result = transform_point(point, false, 45.0);
        let expected = std::f64::consts::FRAC_1_SQRT_2;
        assert!((result.x - expected).abs() < 1e-15);
        assert!((result.y - expected).abs() < 1e-15);
    }

    #[test]
    fn transform_and_snap_point_snaps_to_the_canonical_grid() {
        // 0.12345 mm rotated by 0 degrees must round-trip through the
        // canonical millimeter grid exactly like `toGridMm`/`fromGrid` alone
        // would (ties away from zero at the 1e-3 mm grid step).
        let result = transform_and_snap_point(p(0.12345, 0.0), false, 0.0)
            .expect("finite point fits the canonical grid");
        assert_eq!(result.x, 0.123);
        assert_eq!(result.y, 0.0);
    }
}
